- renpy/common/00updater.rpy
Add the translation function _() to `raise UpdateError` strings because they are showed to the end user.
Don't know how this can be done in line 1030: `raise UpdateError("While unpacking {}, unknown type {}.".format(info.name, info.type))`
> Add translation function _() in Update 00updater.rpy error messages

- .gitignore
- launcher/game/preferences.rpy
- launcher/game/translations.rpy
I created a specific option in the preference panel to handle this behavior and I subordinated it to the rot13 check.
I think it will be useful to change that check also and to create explicit request to the developer for rot13 option, maybe with just before the export and after the choose of the language name, so it will not be tied to the language name.
> Let choose to developer if strings need to be empty while generating translations

- launcher/game/front_page.rpy
- launcher/game/preferences.rpy
Many power users have no need for the edit shortcuts in the launcher,
and in projects with a large number of script files hitting "edit all
script files" by accident can be annoying
> add toggle to show/hide "Edit File" section

- renpy/main.py
Otherwise, compiling may fail in case there some orphaned (without .rpy) .rpyc with same labels as in other scripts (usually happens on script rename).
The only problem with this i can see is that it may affect .rpyc files in renpy/common. Not sure if that is a real problem and whether or not those files are touched without this change.
> Remove old .rpyc files on "Force Recompile"

- module/setup.py
For instance, this can be used this to compile RAPT without requiring a prior full native build of Ren'Py (a native build is still required to run the APK builder).
> Skip all the ANGLE installation on mobile targets

- renpy/common/00start.rpy
renpy.game.call_memory is deprecated/no longer in source.
> Update 00start.rpy comments

- renpy/exports.py
While this is trivial code, it just makes sense to me that Ren'Py has this (at least, as opposed to not having it). As a complement to renpy.set_physical_size(), anyhow.
> Add renpy.reset_physical_size()

- module/README.txt
- module/setuplib.py
"if not android or ios:" <- this line has redundant "or ios" part, so either it was meant to be "not (android or ios)" or just "not android".. Not sure if this affects anything, but it's better to keep source clean.
Also removed outdated README in module/ directory.
> add missing parentheses in setuplib.py and remove old README

- launcher/game/tl/simplified_chinese/updater.rpy
It should be "每夜版", not "暗黑版".
Old translation means "darkness version", not "nightly".
> Fix Nightly's translation

- renpy/python.py
The reason for this is that otherwise eval function available in
.rpy files is not fully compatible with regular python eval.
> fix (py_)eval: allow evaling code objects

- renpy/exports.py
"The programmatic equivalent of the show screen statement." became "The programmatic equivalent of the call screen statement." for def call_screen
> Typofix on docstring

- renpy/ast.py
Completed the fix for #292: `UserStatement.predict` uses the return value from `UserStatement.call`, but that method did not return anything.
> Fix creator-defined statement prediction

- renpy/config.py
- renpy/text/text.py
- sphinx/source/config.rst
This allows a custom function to for example replace '--' with em-dash and '...' with an actual ellipsis character. While it is possible to instead put those Unicode characters directly in the .rpy file, it is easier to type them as ASCII sequences.
> Custom text replacement hook

- renpy/display/swdraw.py
This fixes a bug where, if you're using the software renderer on Xorg on Debian Jessie,
switching into fullscreen produces an unusable screen (usually, a fullscreen window with
the current screen contents stuck on it; sometimes the game window scaled to full screen
but refusing to accept graphic updates (though clicks ARE passed through to the underlying
game), sometimes the game window drawn actual size in the upper left corner of the screen
with the rest of the screen occupied by the previous screen contents).  This bug was
seen on two different Jessie machines.
The fix doesn't appear to cause problems on my Win8 test machine; I haven't tested it on anything else.  There doesn't seem to be any real performance benefit from the window reuse on Jessie or Win8.
> No longer try to reuse existing windows when switching video modes.

- renpy/common/00action_file.rpy
So that you can quickload a file without having the load confirm prompt show up. I intend to make all prompts optional for my next game so this was a necessary change for me, and it's a convenient option for other devs who might want to do the same.
> Added argument to QuickLoad() to control confirm prompt

- renpy/common/00definitions.rpy
- renpy/defaultstore.py
- renpy/display/transition.py
- renpy/pyanalysis.py
This adds a new transition type, which causes the new scene to "push" the old scene off the screen in one of four directions. It's basically just a special case of CropMove--a combination of a slide in and a slide out applied simultaneously. I couldn't think of a nice way to do it with the tools available, so I made it its own transition, which I thought other people might find useful.
As a side note, because this is code I've written for a MangaGamer project, I'd appreciate it if you could credit them alongside me wherever you credit contributors, should you choose to accept this.
> Add a PushMove transition.

- renpy/color.py
- renpy/text/text.py
- sphinx/source/text.rst
This text tag can be used to just control the opacity of the affected text.
It takes a value between 0.0 and 1.0, corresponding to invisible to fully opaque, respectively. Values can optionally be prefixed by + or - to indicate a change in opacity, as opposed to a total replacement.
> Add {alpha} text tag.

- renpy/common/00preferences.rpy
- sphinx/source/inc/preference_action
These values allow you to operate the mute and volume preferences on any channel instead of only the pre-defined ones in the Preference screen action.
> Add 'mixer <mixer> mute' and 'mixer <mixer> volume' Preference values.

- module/ffdecode.c
Hi,
with the upcoming release of ffmpeg 2.9/3.0 Ren'Py will fail to build from source due to the use of deprecated macros and functionality.  This patch fixes these issues and also works with the current version of ffmpeg.  See also the corresponding Debian bug reports for further information.
https://bugs.debian.org/758365
https://bugs.debian.org/803858
> Replacing deprecated ffmpeg macros and functionality

- module/IMG_savepng.c
Ren'py fails to build from source on Big-endian architectures due to a missing semicolon in module/IMG_savepng.c.
> Fix FTBFS on Big-endian architectures.

- renpy/parser.py
- sphinx/source/changelog.rst
- sphinx/source/displaying_images.rst
When init offset support was added in commit 679f9e31, the default image init
priority was changed from 500 to 990. This changes it back.
> Document the change to the default image init priority

- renpy/common/00compat.rpy
Some pre-6.11 games overwrite `config.layers` entirely and omit "screens", which makes sense given that the screen system wasn't a thing back then.
However, this breaks on modern Ren'Py which expects the layer to be there (see `renpy.get_screen()` et al.). This fix adds compatibility support for games with such old `script_version`s.
> Support pre-6.11 games that overwrite config.layers.

- sphinx/source/udd.rst
The upper def visit() like still looks badly indented.
> Index Fix in UDD Doc

- renpy.sh
This make it easier for people to figure out why their fresh git checkout won't run.
> Clarify error when unable to find platform files.

- sphinx/source/quickstart.rst
The Quickstart had a link to the download page of the old wiki.
(Please check, I'm not sure if this is the correct place to change this.)
> change link to old wiki

- renpy/common/00action_control.rpy
`renpy.showing()` doesn't work as the `screens` layer is not provided, and providing it gives other weird behaviour. Use `renpy.get_screen()` instead, as this works properly.
> Use proper API for determining if screen is showing in Show().

- renpy/ast.py
- renpy/parser.py
- renpy/translation.py
- sphinx/source/label.rst
Originally proposed here: https://lemmasoft.renai.us/forums/viewtopic.php?f=32&t=38122
> When the script is heavy-choice, amount of labels can soon get unmanageable. I think the usual way to avoid name collisions is to use something like "chapter1_episode1_choice1", but it is ugly, verbose and still doesn't guarantee avoidance of collisions, especially when using third-party code.
> 
> To resolve this problem i propose introducing 'local' labels, which can have identical names inside different 'global' labels. Here's how it works:
> 
> ```renpy
> label global_label:             # normal label, nothing changed for its behaviour
>   "..."
> label .a:                       # local label fully identified as global_label.a
>   "..."
>   jump .a                       # local jump, resolved to …
```
> add local/nested labels support

- renpy/common/00keymap.rpy
- renpy/common/_errorhandling.rpym
- renpy/display/layout.py
- renpy/screenlang.py
- renpy/sl2/sldisplayables.py
I figure if "mousewheel" is a child, it might be nice to be able to have "arrowkeys" as a child... but I'm not entirely certain as to the correctness of the script changes.
It works on my end, but it may not be stylistically correct.
> Add "arrowkeys" child to Viewport

- renpy/text/extras.py
Prevents {alpha} from being incorrectly identified as an invalid text tag during Lint scans.
> Add {alpha} to text_tags dict

- renpy/display/transition.py
- sphinx/source/inc/transition
Current example is missing a comma and will crash the game if used.
> Update MultipleTransition documentation example

- renpy/common/00action_other.rpy
- renpy/common/00barvalues.rpy
- renpy/common/00iap.rpy
- renpy/defaultstore.py
- renpy/display/screen.py
- renpy/display/transition.py
- renpy/exports.py
- renpy/ui.py
Fix some typos and edit line lengths (where the changes left the line a
little short).
> Fix some typos in documentation

- renpy/exports.py
I'm pretty sure this is meant to be "delay"?
> Fix typo in pause function docs

- renpy/common/00preferences.rpy
- renpy/display/video.py
- renpy/preferences.py
Video was too taxing for some of our systems and we wanted to be able to fall back to the already defined backup images for movie sprites without deleting the original file paths.
> New preference for forcing fallback images on video sprites

- sphinx/source/config.rst
Fix some spelling errors. Plus, I'm pretty sure hertz (the unit) is written as Hz, since it is named after Hertz (the person).
> Fix some typos in config documentation

- sphinx/source/changelog.rst
In the changelog there was a sentence that ended abruptly:
> Ren'Py can be made to return to the old behavior (in which only translate language style, translate language python, and callbacks are executed) by setti
I changed it back to how it was before 4b06e96d28e30234251271cc405573981c684fd9, where it got cut off for some reason.
> Fix cut off sentence in changelog

- gui/game/screens.rpy
- launcher/game/tl/spanish/common.rpy
- launcher/game/tl/spanish/developer.rpy
- launcher/game/tl/spanish/screens.rpy
- launcher/game/tl/spanish/script.rpym
- Some missing words and strings have been translated (mostly those that the final player will see, not the developer).
(This affects the translation files too)
Some sentences in the gamepad help screen have small typos:
"Advance dialogue and activates the interface."  -> Advances
"Roll back to earlier dialogue."    -> Rolls
"Roll forward to later dialogue."  -> Rolls
"Access the game menu."  -> Accesses
These sentences are the same in the keyboard help screen, but should be translated only once. They are duplicated in the translation files because of the typo.
> Update some strings is Spanish translation / Found some typos in gui/screens.rpy

- renpy/lint.py
- sphinx/source/style_properties.rst
AttributeError: 'FontGroup' object has no attribute 'lstrip'
where FontGroup is mistaken for font path string.
> - Fixes Lint Exception:

- gui/game/options.rpy
- launcher/game/tl/japanese/options.rpy
Now I think all translation issues are over.
> Remove trailing ' from comment for translation

- renpy/ui.py
When a game crashes because of an unclosed layer/widget stack, includes the widget stack in the traceback.
> Include widget stack in traceback when relevant

- help.html
Minor change. I just changed URLs to the Renpy website to use https instead of http.
This will make users go directly to the webpages linked, instead of automatically being redirected to the https version by the website. Should be (very slightly) better for user experience! 😊
> Updated urls linking to renpy.org to use https

- sphinx/source/screens.rst
Some typo and formatting fixes, plus some rephrasing of grid terminology (it seemed to confuse cells vs. columns because spacing looks to be applied both vertically and horizontally).
> vpgrid docs: some typo and formatting fixes, plus some rephrasing of grid terminology

- launcher/game/package_formats.rpy
Previously, as the files got added to the 'archive', if adding a file required more than one parent folder to be created then the build would fail.
> Fixed issue with Directory build option.

- renpy/scriptedit.py
`renpy.scriptedit.insert_line_before` will copy the ending of the line it's being inserted before, defaulting to a DOS newline if it has none.
> id: Use appropriate line endings.

- renpy/text/text.py
0777826d introduces some major regressions, including breaking the
behavior of `{w}` and `{p}` tags, hyperlinks, and ruby text. This commit
correctly copies over the necessary information from `splits_from` in
the `Layout` constructor (as far as I can tell), and preserves the value
of `start_segment` in `Layout` objects so that it can be copied
properly.
> Fix major text segment layout regression.

- renpy/exports.py
Previously, `_with_none` was still in `kwargs` when the screen was shown, so the call would explode unless your screen also happened to have a `_with_none` argument.
Incidentally, [the documentation suggests](https://www.renpy.org/doc/html/screens.html#call-screen) that a `with` after a `call screen` should _just work_, but it doesn't if `config.implicit_with_none` is true — which it is by default!  Not sure if the docs ought to point this out, or if it's planned for `_with_none` to be added to the call automatically someday...?
> call_screen() shouldn't pass along _with_none

- renpy/exports.py
Saying that this returns "None" when an image is showing instead of when it isn't makes this function incredibly confusing at first sight.
> Fix typo in "renpy.get_attributes" doc

- renpy/atl.py
It's possible to use an ATL transform as an interpolation target, but only if all the properties are on the same line:
```
transform truecenter:
xcenter 0.5 ycenter 0.5
transform tocenter:
linear 1.0 truecenter
```
Now you can do this too:
```
transform truecenter:
xcenter 0.5
ycenter 0.5
transform tocenter:
linear 1.0 truecenter
```
> Allow interpolating to any prop-only ATL transform

- tutorial/game/indepth_displayables.rpy
- tutorial/game/tl/piglatin/indepth_displayables.rpy
- tutorial/game/tl/russian/indepth_displayables.rpy
In this small pull request, I replaced Live Composite by Composite in tutorial and its translation, according to your [changelog](https://www.renpy.org/doc/html/changelog.html?highlight=changelog#renpy-6-99-14-3) in version 6-99-14-3.
> LiveComposite replaced by Composite in tutorial and its translations.

- tutorial/game/screens.rpy
- tutorial/game/tl/french/01example.rpy
- tutorial/game/tl/french/common.rpy
- tutorial/game/tl/french/indepth_character.rpy
- tutorial/game/tl/french/indepth_displayables.rpy
- tutorial/game/tl/french/indepth_minigame.rpy
- tutorial/game/tl/french/indepth_style.rpy
- tutorial/game/tl/french/indepth_text.rpy
- tutorial/game/tl/french/indepth_transitions.rpy
- tutorial/game/tl/french/indepth_translations.rpy
- tutorial/game/tl/french/options.rpy
- tutorial/game/tl/french/screens.rpy
- tutorial/game/tl/french/script.rpy
- tutorial/game/tl/french/tutorial_atl.rpy
- tutorial/game/tl/french/tutorial_director.rpy
- tutorial/game/tl/french/tutorial_distribute.rpy
- tutorial/game/tl/french/tutorial_nvlmode.rpy
- tutorial/game/tl/french/tutorial_playing.rpy
- tutorial/game/tl/french/tutorial_quickstart.rpy
- tutorial/game/tl/french/tutorial_screen_displayables.rpy
- tutorial/game/tl/french/tutorial_screens.rpy
- tutorial/game/tl/french/tutorial_video.rpy
This is the french translation of your excellent tutorial. I hope it will be used by the french communauty.
I edited the `screens.rpy` file to add « Français » in the list, between English and Русский as mentioned in comments line 775.
Here is the result of the lint process:
```
﻿Ren'Py 7.0.0.51 lint report, generated at: Tue May 01 18:16:38 2018
Statistics:
The game contains 828 dialogue blocks, containing 16,043 words and 91,747
characters, for an average of 19.4 words and 111 characters per block.
The french translation contains 828 dialogue blocks, containing 17,583 words
and 109,814 characters, for an average of 21.2 words and 133 characters per
block.
The piglatin translation contains 828 dialogue blocks, containing 16,043 words
and 125,049 characters, for an average of 19.4 words …
```
> French translation of the tutorial.

- tutorial/game/tl/french/tutorial_quickstart.rpy
- tutorial/game/tl/russian/indepth_displayables.rpy
- tutorial/game/tl/russian/screens.rpy
- tutorial/game/tl/russian/tutorial_quickstart.rpy
- tutorial/game/tutorial_quickstart.rpy
Transform named 'slightleft', not 'sightleft'. This PQ fix it for all translations (well, not Piglatin. We're antipiglatiners...)
Also, fix one string in Russian.
> Small fix for Tutorial

- sphinx/source/layeredimage.rst
Some corrupted dash characters were introduced in commit https://github.com/renpy/renpy/commit/891eea363cf3e0be2894139eb4f820ece34d783b.
> Corrections to layered image documentation

- sphinx/source/changelog.rst
- sphinx/source/displaying_images.rst
- sphinx/source/incompatible.rst
- sphinx/source/layeredimage.rst
- sphinx/source/style.rst
- sphinx/source/translation.rst
This pull request changes the spelling of "init-time" to the more commonly used "init time."
> Documentation corrections

- renpy/display/render.pyx
Note: I hope unlike #1491 this won't be rewritten followed by a wordless close. That was rude.
> render: typos in docstring

- renpy/character.py
- renpy/common/000window.rpy
- renpy/common/00action_data.rpy
- renpy/common/00console.rpy
- renpy/common/00gallery.rpy
- renpy/common/00nvl_mode.rpy
- renpy/common/00start.rpy
- renpy/common/00style.rpy
- sphinx/source/dialogue.rst
Please verify the capitalization of "true" and "false" in renpy/character.py.
> Typo corrections in documentation

- renpy/exports.py
The screen argument needs to be passed as a keyword.
> game_menu() no longer ignores screen parameter.

- renpy/defaultstore.py
Sometimes I want to use TextButton and/or ImageButton as displayables, but not in a screen. Since vanilla Button is exposed, it seems harmless to expose these two as well.
> Expose ImageButton and TextButton displayables

- renpy/text/text.py
Some tags that require value, when supplied none, raise python's
exceptions which might be hard to interpret.
Added simple checks to those tags to see if the supplied value is
empty. Raises exception that is easier to read than the ones
Python raises.
To a person who doesn't know programming, working on a large project might get them confused if they leave a tag empty and see Python's exceptions which might make this simple problem hard to understand.
It's for #1598
> Add checks for tags that require value

- module/IMG_savepng.c
- module/IMG_savepng.h
- module/core.c
The conflict appears when linking statically, which I do when working on the emscripten port.
(dynamic linking is partially supported in emscripten but not in our case, and it also introduces a performance penalty.)
The 2 functions sets are not exactly the same and do not have the same signatures, hence why I didn't merge them. Note: there is a 3rd set of IMG_SavePNG functions in SDL2_image.
> Rename IMG_SavePNG* to avoid conflict with PygameSDL2's

- module/glcompat.h
- module/setup.py
- module/setuplib.py
- renpy/__init__.py
- renpy/config.py
- renpy/exports.py
- renpy/gl/gldraw.pyx
Here are a few changes to start including emscripten awareness in the Ren'Py code.
They should be safe and not impact the other platforms.
(I have more patches that are more hard-coded; I'm progressively splitting out and modifying them so they can peacefully co-exist.)
> emscripten: detect and start configuring accordingly

- the_question/game/screens.rpy
- tutorial/game/screens.rpy
This will fix crash when trying to open history in these two example projects.
> Add missing history_allow_tags set to tutorial and The question.

- renpy/audio/sound.py
Since renpy.sound is basiacaly a alias of renpy.music, I think set_volume should also have the delay parameter.
> Add delay to renpy.sound.set_volume

- the_question/game/tl/french/screens.rpy
I couldn't find the central point for the translations though. These strings also appear in "Tutorial" and to some extent in "Launcher". Should I replicate the changes there as well?
> Fixes to French translation

- renpy/bootstrap.py
With Emscripten, this tells the browser to stop calling the audio callback.
> Explicitely close audio on quit

- renpy/display/presplash.py
Let me know if that's OK like this.
> emscripten: presplash specific handling

- launcher/game/change_icon.py
- launcher/game/distribute.rpy
- launcher/game/pefile.py
- renpy/common/_developer/developer.rpym
- renpy/display/core.py
- scripts/style_to_statement.py
- scripts/utflf.py
- scripts/zip_size_change.py
- sphinx/source/renpydoc.py
Use the print function in pure Python files.
`launcher/game/distribute.rpy` and `renpy/common/_developer/developer.rpym` both also use the old python2 print statements, but I'm not sure how they get turned into Python code and `from __future__ import print_function` has to be declared at the top of a Python file for it to work properly. So some guidance would be helpful for those two files.
> [Py3] Use print function in pure python files

- launcher/game/EasyDialogsWin.py
- launcher/game/pefile.py
- module/setuplib.py
- renpy/audio/audio.py
- renpy/execution.py
- renpy/loadsave.py
- renpy/main.py
- renpy/parser.py
- renpy/python.py
- renpy/six.py
Yet another attempt at this (#1282 #1101 #1100 #1098).
This PR also includes a [copy of the six library](https://github.com/benjaminp/six) inside the renpy namespace for use in later porting PRs. In this PR, it is used to enable raising exceptions with traceback on Python3, falling back to 3 argument raise on Python2.
> [Py3] Make exceptions both python2 and python3 compatible

- renpy/__init__.py
Emscripten uses static Python modules, for performance and because dynamic linking as no async support.
> update_path: support static Python modules

- module/_renpy.pyx
- module/core.c
- module/renpy.h
- renpy/display/im.py
- renpy/display/module.py
Implements `im.Blur` as a fast Gaussian blur approximation. This is done by combining three passes of a box blur, each of which is done in turn by combining two passes of a linear time one-dimensional blur (existing `xblur` code was refactored and used for this). The final result is a blur method that also operates in linear time. It works with both 32 and 24-bit surfaces, and supports both circular and (symmetrical) elliptical kernels.
Details of the research involved can be found in the material linked in the code comments on the relevant functions, along with a much more detailed explanation that it doesn't make sense to replicate in full here.
Details of usage are documented on the `renpy.display.im.Blur` class.
---
**Examples with Eileen**
<details><summary>Normal</summary> …
> Fast im.Blur implementation

- renpy/display/video.py
While experimenting with Emscripten, which is flagged as 'mobile', I saw a discrepancy between this patched test (renpy.mobile), and https://github.com/renpy/renpy/blob/92e037510861fa79c359ecc4b22e0e48231e3dcb/renpy/audio/audio.py#L722-L725 (renpy.android or renpy.ios).
So I changed the test to only reference platforms with explicit video hardware support, rather than all mobile platforms.
Not high-priority though :)
> hw_video: use consistent platform testing

- renpy/text/text.py
Currently `figure_outlines` uses `scale_outline` to scale both the outline size/width _and_ the outline offsets.
If I understood [this comment](https://github.com/renpy/renpy/issues/1729#issuecomment-465858965) correctly, `scale_outline` purposely ensures that all outlines increase in size in tandem. This makes sense for outline sizes/widths, but less so for the associated offsets.
Switching the offsets to scale using `scale_int` instead eliminates stepping related to positioning while still ensuring that the outlines themselves step together when it comes to sizing.
> Fix positional stepping when scaling outlines

- renpy/character.py
- renpy/display/image.py
The use case for this is long dialogues with many temporary attribute expression changes. Currently the `config.speaking_attribute` is only active when using temporary attributes (believe this is a bug). The combination of the two makes sense, however there's currently no way to suppress the `speaking_attribute` for the odd line where, for example, a character is internally monologuing.
In order for the suppression to be possible, a slight change to tag evaluation was required:
At present all tags become part of a `required` set, then those tags are processed, their positive counterparts are removed from the `optional` set, and they themselves are removed from the `required` set. The missing element here is that negative tags do not check the `required` set for their positive …
> Let temp attrs and speaking attr to work together

- renpy/character.py
Switch back to prepending temporary_attrs with speaking_attribute so
that temporary say attributes have the chance to suppress the
speaking_attribute.
The use case for this is catering for infrequent lines of a character's
internal monologue, for which they are responsible, but do not actively
speak.
Fixes #1738
> Fix speaking_attribute suppression

- renpy/exports.py
renpy.movie_cutscene() can play any Ren'Py compatible movie file, but the documentation had not been updated to reflect this.
> Remove MPEG-1 from renpy.movie_cutscene()

- renpy/parser.py
This allows to do revert correctly even if the lexer has been exhausted before.
> Perform re-create Lexer.eob on revert

- renpy/text/font.py
This allows the BMFont object to understand "kerning" lines embedded within BMFont definitions whereas previously they would be ignored.
The kerning information is added to the existing "self.kerns" property.
I suspect this should have originally been the case as well, given that the entire kerning support system is already in place and kerning support is mentioned in the documentation for BMFonts.
> Add ability to parse kerning messages of BMFont fonts

- renpy/character.py
- renpy/config.py
- sphinx/source/config.rst
Follows from discussion and concept in https://github.com/renpy/renpy/issues/1761#issuecomment-473678693
This provides context to the callback about the incoming image it's affecting with the transition. This can be used in isolation, or with the current state to intelligently utilise a transition based upon the tags/attributes of the image being displayed.
---
For example, this would allow transitions to be selected based on which attributes are/will be changing:
```renpy
init python hide:
dissolve_attrs = {'running', 'walking', 'jumping', 'skipping'}
def example(tag, attrs, mode):
current_attrs = _set(renpy.get_attributes(tag))
future_attrs = _set(attrs)
future_attrs.remove(tag)
changed_attrs = current_attrs ^ future_attrs 
if dissolve_attrs & changed_attrs:
return dissolve, …
```
> Extend say_attribute_transition_callback with canonical tag list

- module/ffmedia.c
[FreeBSD](https://github.com/freebsd/freebsd/commit/2ffad81b1757554bf9413d11af0e92c93a94575b), [DragonFly](https://github.com/DragonFlyBSD/DragonFlyBSD/commit/02b66c54cac986a0bf93435b8d5ae1b17521515b), [OpenBSD](https://github.com/openbsd/src/commit/d88f57029e5acaaaf028633c7fa15c5d7325c5cc) don't support `<malloc.h>`. `aligned_alloc` would work on all platforms but it's C11 while module/setuplib.py currently passes `-std=gnu99`, so use `posix_memalign` for now.
http://beefy8.nyi.freebsd.org/data/head-armv6-default/p494472_s344734/logs/errors/renpy-7.1.3.log
http://www.ipv6proxy.net/go.php?u=http://beefy15.nyi.freebsd.org/data/112armv6-quarterly/499227/logs/errors/renpy-7.2.2.log
http://www.ipv6proxy.net/go.php?u=http://beefy15.nyi.freebsd.org/data/120armv6-quarterly/498627/logs/errors/renp …
> Unbreak ARM build on BSDs

- renpy/loader.py
In python it's possible for a module to meddle with `sys.modules` during it's initialisation, this allows it to dynamically redefine itself on-the-fly, it's not common, but it happens. In vanilla python assignments of imported modules take place after the module is exec'd, however in renpy the opposite is true. This early assignment can lead to a case where the imported module does not match the value in `sys.modules` and subsequent `import`s yield a different result. This is shown in the simple (albeit contrived) test case provided, along with output samples pre- and post-patch.
**game/lib.py**
```py
from sys import modules
from types import ModuleType
mod = modules[__name__] = ModuleType(__name__)
del ModuleType, modules
mod.a = 'hello'
```
**game/script.rpy**
```renpy
init python: …
```
> Keep vanilla python's late import binding

- renpy/sl2/slparser.py
> Raise indention error for misspelled indent after keyword

- renpy/substitutions.py
- sphinx/source/displaying_images.rst
- sphinx/source/text.rst
- sphinx/source/translating_renpy.rst
`str.capitalize` not only uppercases the first character, but also lowercases the remainder of the string. This presents problems in some conditions:
Example:
```py
>>> surname = 'da Silva'
>>> surname.capitalize()
'Da silva'
>>> c = lambda s: s[0].upper() + s[1:] if s else s
>>> c(surname)
'Da Silva'
>>> c('') # value check is so we don't throw on empty string
''
```
```renpy
eileen "Hello, [firstname] [surname]!"
ds "Please, Eileen, just call me [surname!c]."
```
The alternative presented here seems like it should cover most cases where capitalisation is wanted, i.e. beginning of sentences, while providing a better experience when dealing with multipart names and other strings with intentional capitalisation. Another good example might be `the University of Massachusetts`.
Ref: [Initial …
> Capitialise first character only with !c

- renpy/display/screen.py
- sphinx/source/screens.rst
Related to https://github.com/renpy/renpy/issues/1755
The current implementation doesn't seem to fulfil all the "key features" or the original suggestion, specifically:
> - Events such as select and hover should not occur or trigger visual changes
> - The non-interactive screen should not obstruct interactivity with other screens/layers
This PR achieves those aims, however the `sensitive` expression is now eval'd in two separate places. Obviously this isn't ideal, so perhaps there's a better way.
Here's a test case demonstrating and describing expected functionality:
Test Case:
```renpy
image _ = Solid('000e')
image r = Solid('f773', xysize=(320, 240))
image b = Solid('7ff3', xysize=(320, 240))
label main_menu:
$ _confirm_quit = False
return
label start:
scene _
show screen example
while …
```
> Suppress hover/click-capture if screen insensitive

- renpy/common/00keymap.rpy
- sphinx/source/config.rst
> Prevent open IE in Windows if help-file not exists

- renpy/translation/generation.py
In Ren'Py translations, there are comments about the original path containing the translatable string:
```
translate french start_a170b500:
e "You've created a new Ren'Py game."
translate french strings:
old "Eileen"
new "Eileen"
```
The script path is not consistent between translate blocks and single strings.
This patch makes them consistent (and incidentally improves the quality of my PO exporter's output ;)), using Ren'Py function `elide_filename`.
```
script.rpy:27 -> game/script.rpy:27
00accessibility.rpy:76 -> renpy/common/00accessibility.rpy:76
```
> translation: unify base path in string source comments

- launcher/game/tl/french/common.rpy
- launcher/game/tl/french/error.rpy
- the_question/game/tl/french/common.rpy
- tutorial/game/tl/french/common.rpy
Some new common strings (the accessibility menu that pops-up with key 'a' ; some strings from the error screen) are not available in French.
Since these strings can be imported in new games, let's translate them :)
(some other strings are still translated, but that's a more exhaustive job for later)
@maxlefou I think you're the usual translator, do you want to proof-read?
> Update common french translations

- renpy/translation/__init__.py
change_language is called often even if there was no real language change -> better to shortcut it as early as possible
also block_rollback was never called due to the setting of old_language earlier
> shortcut for change_language

- renpy/character.py
- sphinx/source/changelog.rst
- sphinx/source/config.rst
- sphinx/source/incompatible.rst
Fixes #1850.
The proposed solution is alter the behaviour of `handle_say_attributes` to:
- Store the image before state
- Resolve permanent attributes
- Resolve temporary attributes if necessary
- Store the image after state
- Calculate the transition only once, and only if the before and after states differ
This also allows the interface of `say_attribute_transition_callback` to be made more useful by passing down the before and after states, rather than the current API which only passes down the before state. The relevant documentation has been updated to explain and reflect this.
A new value for the `mode` parameter has been added to cover the case where a transition is being built to cover a simultaneous change to permanent and temporary attributes: `hybrid`. This too has been …
> More say transition changes

- renpy/display/layout.py
- renpy/display/render.pyx
This is fix #1875 
Also added an additional condition to the `invalidate` that doesn't cause excessive redraw, in the case of sizing outside render.
> Fix adjustment bug

- launcher/game/mobilebuild.rpy
I've eventually tracked down this annoying bug that silently paused the Ren'Py process whenever I started an Android build, if Ren'Py was running in the background (e.g. `./renpy.sh &`).
I couldn't find a way to make gradle behave, so I implemented the equivalent of `< /dev/null`.
> rapt: prevent gradle from stopping Ren'Py when run in the background

- renpy/display/core.py
- renpy/gl/gldraw.pyx
When Ren'Py "caches" the fullscreen status, this lead to issues in RenPyWeb, as exiting fullscreen can be triggered directly by the user pressing "Esc." (handled by the browser, rather than requested by Ren'Py/SDL2). This makes Ren'Py keep requesting fullscreen right after the user exits it.
Getting the low-level fullscreen status is a bit convoluted but I could do it without modifying the API.
> web: detect when fullscreen status changed externally

- gui/game/screens.rpy
- renpy/main.py
- sphinx/source/screens.rst
- the_question/game/screens.rpy
- tutorial/game/screens.rpy
This proposal detects additional variants by querying the browser.
This allows the same web game to e.g. plays with a mobile UI on mobile, and with a full-blown UI on desktop/"pc". This can be tested with real hardware as well as "Responsive Design Mode" in browsers.
I'm not entirely sure about setting "android" and "ios", maybe some games use it to target OS-specific features not available through the browser.
(tested on 7.3.2.320, master is broken with the on-going GL work AFAICS)
> web: set variants according to what the browser runs on

- sphinx/source/python.rst
Additional stores are available as local variables in the default 'store' under their name already, consequently 'import store.mystore as mystore' is a no-op
> doc: python: clarify other stores usage

- sphinx/source/build.rst
I spent a lot of time finding where this was set. It would be useful putting what file it is located.
> Added that the default setting are in options.rpy

- renpy/common/00action_data.rpy
A field (especially a global Variable) might not exists at the beginning of the interaction. This causes the application to crash e.g. if the variable is set on the 'action' of a button.
The solution is that the get_selected returns False if the given field does not exists at the moment.
> prevent crash when get_selected is called on a non-existent field

- renpy/gl/glenviron_shader.pyx
> gles: handle GPUs that do not support highp

- renpy/display/viewport.py
Fixed bug where viewport stops edgescrolling for a fraction of a second after every mousemotion event when mouse in the edgescroll area. It's caused by the event function setting edge_last_st = st when it calls check_edge_redraw. 
Fixed by adding a boolean parameter to check_edge_redraw that keeps the method exactly as before by default, but allows it to skip resetting edge_last_st when called from the event function.
> Fixed bug with edgescroll in viewport

- sphinx/source/config.rst
AFAICS the only place where it's set to True is in a `version <= (6, 99, 14)` compatibility block.
I only read and test it to False otherwise.
> config.cache_surfaces is False by default

- renpy/display/viewport.py
Fixed a bug I caused in #2002, where the viewport would jump to a different position when mouse re-enters the viewport.
> Clear edgescroll timer when mouse moved out of bounds

- launcher/game/package_formats.rpy
- launcher/game/pefile.py
- renpy/common/00updater.rpy
- renpy/display/image.py
- renpy/display/swdraw.py
- renpy/loadsave.py
Continuing the work from #1098, #2003 and related PRs.
1. Remove the L suffix from integers.
2. Fix integer division in Python 3.
3. Use the new octal syntax to prevent breakage in Python 3.
> [Py3] Make Python 3 integer related changes

- distribute.py
- renpy/bootstrap.py
- renpy/editor.py
- renpy/loader.py
- renpy/main.py
- renpy/python.py
- renpy/sl2/slast.py
1. Detect if reload is built-in (Py2.7 only) and import it from importlib if not (Py3 only).
2. Replace exec built-in with exec function call.
3. Replace execfile built-in with file read + compile + exec calls.
> [Py3] Replace exec, execfile, reload with Py3 compatible versions

- launcher/game/webserver.py
- module/uguu/xml_to_pyx.py
- renpy/display/pgrender.py
- renpy/gl2/gl2shadercache.py
- scripts/future_print.py
- scripts/rt.py
- scripts/zip_size_by_directory.py
- scripts/zip_size_by_file.py
Some files had print calls added without the import. It appears some of them are already meant to run under python 3, but I added the import to all files that had print without the import for safety.
I also removed an instance of tuple unpacking which is no longer supported in Py3.
> [Py3] Import print_function, remove tuple unpacking

- README.rst
Updated URL in readme to use HTTPS instead of HTTP to avoid redirect to HTTPS version.
> Updated URL to avoid redirect to HTTPS version

- renpy/display/presplash.py
- renpy/main.py
- renpy/script.py
Since pygame_sdl cannot handle events by threads, we pump the presplash window after each file loading. Also checks that the user asked to close the game without waiting end of loading.
> Rework presplash processing

- renpy/python.py
1. Fixed bug when `RevertableList[::1]` returns Python list.
2. Fixed bug when `RevertableList[:] = []` did not participate in the rollback.
3. Since slice methods are not available in Python 3 list, their use is wrapped in six.
4. Added useful `clear` and `copy` methods of Python 3 list.
> [Py3] Updated behavior of RevertableList

- sphinx/source/dialogue.rst
- sphinx/source/displaying_images.rst
- sphinx/source/label.rst
Changes in this PR:
* Update typos in dialogues and displaying images.
* Propose a more explicit example when using `expression` in label
> Improve documentation

- renpy/display/layout.py
It took me forever to spot that there are 2 functions with the same name, and the first one in the documentation (which we find through Ctrl+F) did not mention that.
> doc: reference im.AlphaMask in AlphaMask

- renpy/exports.py
It's mostly a "code typo" fix. I don't have a specific case where it fixes a bug, since the restore didn't seem to matter in my project, but it should now have the intended behavior.
> Fix menu_kwargs restore assignment from old value

- renpy/common/000statements.rpy
Added missing `continue` in parse_queue_music for `channel` parameter parsing
Continues a series of fixes/refactoring done on music statement parsing in https://github.com/renpy/renpy/pull/2159
> Fix parse error on `queue music [expr] channel [expr]`

- renpy/__init__.py
- renpy/compat/__init__.py
- renpy/config.py
- renpy/loadsave.py
- sphinx/source/save_load_rollback.rst
Also document that it has no effect under Python 3
Resolves #2175 
*Note*: it doesn't touch code that has never made the distinction between `pickle`  and `cPickle`, which means in effect it restores the behaviour prior to c2206245e in those parts.
Tested manually under Python 2.7 with the following script:
```renpy
init python:
renpy.config.use_cpickle = False
class PickleSurprise(object):
pass
def __init__(self):
self.surprise = None
label start:
$ surprise = PickleSurprise()
python hide:
def foo():
def bar():
return 42
return bar
surprise.surprise = foo()
label breakme:
"Try saving now for a pickle surprise"
```
> Make config.use_cpickle work again in Python 2.x

- renpy/sl2/slast.py
It fixes the bug with the SL2 cache which can be simply reproduced by
```
init:
if renpy.loadable("test.txt"):
screen test():
add "#ff0"
else:
screen test():
add "#0ff"
label start:
show screen test
pause
return
```
If the value of the condition changes without changing the code, the screen that was in the cache last time will be used ignoring the real value of `Screen.ast`. 
Rationale:
In our project, we have added code that will be distributed as a DLC that also changes some screens. I tried to do something like:
```
screen DLC_SCREEN():
...
screen main_menu():
if renpy.has_screen("DLC_SCREEN"):
use DLC_SCREEN
else:
...
```
But in this case, the game is not compiled in the absence of DLC due to lookup screen error during the `prepare_screen`. So I'm using something like:
```
init:
if …
```
> Also use the location of screen as key of screen in SL2 cache

- renpy/audio/audio.py
- renpy/audio/music.py
- renpy/audio/sound.py
- renpy/common/000statements.rpy
This change enables users to specify `volume` in `play` and `queue` statements as well as via the Python API `renpy.music.play`, `renpy.sound.play` and the `queue` variants respectively.  
Specifically it adds a tertiary volume which in turn affects the secondary volume such that it still works fine with mixer controls and with minimal changes to the codebase.
It is highly likely that a lot of users utilize music from multiple sources, which is almost never loudness-normalized. Few users do this themselves.  
Thus it can be the case that some music or sound effects are louder or more quiet than others, which can be a hassle to deal with as a player, because one would have to constantly change the mixer controls around depending on what's playing.
While this change does not resolve the …
> Allow specification of per-play/per-queue volume

- renpy/main.py
According to [here](https://github.com/renpy/renpy/commit/118d39d83b40620f15033a707680b51c04ba19ce#diff-3deaadb5853b1b2467152b00910bbfe9L240-L246) and [here](https://www.renpy.org/doc/html/screens.html#screen-variants), iOS builds should define the "mobile" screen variant.
> add "mobile" screen variant to iOS builds

- sphinx/source/license.rst
Bug: https://github.com/renpy/renpyweb/issues/4
> Add renpyweb to license repositories

- renpy/ast.py
- renpy/pyanalysis.py
If this function is applied to a function in a module, it will be marked correctly.
> Improved renpy.pure function.

- renpy/atl.py
- renpy/display/accelerator.pyx
- renpy/display/transform.py
I added the `minsize` transform property.
It's useful when trying to fit a displayable to the background without changing its proportions, for example.
If maxsize is specified, minsize is ignored (better to have an underfull box than to have it overflow).
To paraphrase the words of the [doc](https://www.renpy.org/doc/html/atl.html#transform-property-maxsize) :
If not None, causes the displayable to be scaled so that it fills a box of this size, while preserving aspect ratio (Note that this means that one of the dimensions may be greater than the size of this box.). Maxsize takes priority over minsize.
> add minsize transform property

- launcher/game/tl/korean/error.rpy
Ignores the exception, allowing you to continue.
> Add missing Korean translation for launcher.

- renpy/gl2/gl2draw.pyx
Fixes `AttributeError` while trying to use `renpy.gl2.gl2draw.GL2DrawingContext.draw` with a Surface.
> Fix typo (draw -> gl2draw)

- renpy/log.py
Without it, the raw line is written to the file as `LINE\r\r\n` and some text editors treat it as Mac line endings.
> Remove `\n` replacement in log files, because `io.open` is dealing with it

- renpy/gl/gldraw.pxd
- renpy/gl/gldraw.pyx
- renpy/gl/glenviron_shader.pyx
This work-around was specific to Emterpreter, which is obsoleted by ASYNCIFY.
This reverts commit dce59141a7f940da9f5b2820ee4b61016b9113b3.
> Revert "web: Avoid the use of float arguments."

- the_question/progressive_download.txt
- tutorial/progressive_download.txt
Provide web configuration for the_question and tutorial.
The default configuration doesn't make the music files downloadable, because they are at the top-level directory and the default targets 'music/' only (to avoid targetting non-music sounds) -- and this prevents showcasing music download :)
> web: add progressive download configuration for demos

- renpy/display/layout.py
- renpy/display/viewport.py
- renpy/sl2/slproperties.py
- sphinx/source/style_properties.rst
Allows `margin` family of properties to be used to specify additional space around grids. While this was previously possible for vanilla grids by nesting them within a `Window` layout, it was not possible to do this with vpgrids such that the additional space appeared inside the embedded viewport, which is the primary motivation for this addition.
<details><summary>Diagram showing exactly how this applies</summary>
</details>
> Add support for margin to grids

- renpy/display/core.py
This change allows to get the correct value of `start_interact` (via renpy.is_start_interact) in `config.start_interact_callbacks`.
It allows to use the same function in also `config.interact_callbacks` and reduce code duplication.
> Set start_interact before call start_interact_callbacks

- renpy/display/behavior.py
- renpy/display/core.py
Currently players on mobile web are stuck whenever the game asks text input (typically "what's your name").
As usual web support is tricky, and there's no API for the mobile browser virtual keyboard. My leads are:
(1) Map a HTML text input with SDL2 (character-based): cf. https://github.com/emscripten-ports/SDL2/issues/80 -- APIs/events don't match, security policies are in the way, little external interest, probably not feasible
(2) Implement a virtual keyboard within Ren'Py: sounds OK; it won't support many characters or input methods but integration would be best
(3) Map a HTML text input with Ren'Py (line-based): sounds OK; supports the characters / input methods that the browser supports, integration is a bit rough (translucent text input at the top) but works
(4) Give up and tell …
> web: mobile: browser virtual keyboard support

- renpy/lint.py
Using codecs.open here to do implicit conversion of any str to unicode while writing to the lint output file. If a filename is not provided as an argument to the lint command, then output is sent to sys.stdout for which the str to unicode conversion is already in place (using future.utils.text_type) in https://github.com/renpy/renpy/blob/master/renpy/log.py#L228-L229
> Fixes #2292: Use utf-8 encoding when writing to lint file output

- renpy/exports.py
This function is already documented as `renpy.translate_string` and it is strange that it is not part of the API.
1. It doesn't mark strings as translatable.
2. It (as opposed to `__`) has a documented `language` argument. 
And also `__(var, None)` looks ugly.
> Add alias for `__` in Ren'Py exports as renpy.translate_string

- sphinx/source/transitions.rst
pushup and pushdown were called pushtop and pushbottom.
> Fix incorrect docs for pushup/down transitions

- renpy/common/00keymap.rpy
When `config.allow_skipping` or `store._skipping` are set to False, turning skip on is disabled. However, toggling skip is not. ie: ctrl stops skipping, but tab doesn't.
> Don't allow toggle skip when skip is disabled

- renpy/common/00touchwebkeyboard.rpy
- renpy/display/core.py
This adds a basic, translucent on-screen keyboard programmed in screen language.
It should work in landscape and portrait mode.
It synthesizes SDL keyboard events. I believe I dodged possible conflicts (like sending K_ENTER which triggers the current (enter) button again), targeted the right layer, and restarted interaction appropriately. New screen elements are prefixed with '_'.
It doesn't depend on browser-specific feature as it's 100% Ren'Py, so we can expect browser compatibility.
It's not perfect but it does the job: prevent players from getting stuck when playing with Android/iOS browsers when e.g. the game asks the MC name ;)
Gamedevs may want to customize it, so maybe this needs to be reorganized at a point.
> web: mobile: add built-in simple virtual keyboard

- renpy/common/00keymap.rpy
- renpy/common/_errorhandling.rpym
- sphinx/source/keymap.rst
For "director" and "developer" keysyms are replaced so that CapsLock does not swap them.
For "input_copy" and "input_paste" added noshift modifiers.
In all other cases K_keys are added, so it doesn't break backward compatibility.
Also updated the table in the documentation.
> Add K_key keysyms to default Ren'Py keymap

- renpy/easy.py
With this change `image test = "[var]"` will not ask OS about (almost always) unexisting files. 
On the other hand, `image test = "[var].png"` will quickly be recognized as a non-existent image.
> Improve dynamic image

- renpy/audio/audio.py
- renpy/common/000statements.rpy
- renpy/common/00voice.rpy
- renpy/display/im.py
- renpy/loader.py
- renpy/webloader.py
I have made a few adjustments to project code to allow for compiling and running with Python 3.
- Replaced all instances of `except <type>, <var>` with `except <type> as <var>` in Python and RenPy code. The ladder format is valid in both Python 3.X and 2.7.
- Replaced all instances of `<dict>.has_key(<key>)` with `<key> in <dict>` in Python and RenPy code. The ladder format is also valid in both Python 3.X and 2.7.
- Do the bare minimum to let RenPy use Python 3.X.
- To be a stepping stone in getting RenPy completely Python 3.X compliant.
- Change how RenPy projects are packaged or provide configuration options to change the Python runtime's version.
- Refactor code that uses deprecated methods / functions. (Except of those deprecated methods / functions that have been *removed*.)
Before, …
> Python3 Readiness

- renpy/log.py
This change adds enables flushing of the main log file `log.txt` after each write.
It results in the desirable behavior of writing output to the log file while the game is running, instead of writing it all at once when the game closes.
This makes it easier and quicker to debug things while the game is starting up as output is already able to be viewed while at the same time also capturing `stdio` output for easier debugging of things which are currently active.
This behavior existed in 7.3.5 already, so I assume it would be desirable to keep it consistent for 7.4+
I wasn't able to tell why this worked as it did in 7.3.5 though, given that the `flush` keyword was `False` by default there as well and thus shouldn't have flushed, while in reality it did.
> Flush log after write

- renpy/loader.py
Some environments (especially macOS on HFS+ filesystem) will automatically normalize filenames to a customized version of NFD (see also https://gist.github.com/JamesChevalier/8448512 ).
This will allow those files to be found, even if the filesystem is normalization sensitive.
> Normalize unicode to NFC

- module/include/freetype.pxd
- renpy/text/ftfont.pyx
This partially fixes #2272, specifically the heart case where the variation selector character is ignored and rendered as a placeholder instead of getting respected properly.
> Handle variation sequences (VS1-256 and FVS1-3)

- sphinx/source/index.rst
- sphinx/source/label.rst
- sphinx/source/splashscreen_presplash.rst
I reused the documentation found [here](https://www.renpy.org/wiki/renpy/doc/cookbook/Adding_a_Splashscreen) and [here](https://www.renpy.org/wiki/renpy/doc/cookbook/Preloader_Image) (with some minor tweaks) since they seem to still be valid.
**Disclaimer**: I had some issues setting up the environment to build the documentation so I couldn't test it.
> Add splashscreen and presplash documentation

- renpy/lint.py
Given the assumption that define/default statements shouldn't be duplicated, eg:
```
define pineapple = "pineapple"
default has_banana = False
default has_orange = False
define pineapple = "banana"
```
This PR adds a lint rule to inform the user when it happens:
```
game/script.rpy:9 define pineapple already defined at game/script.rpy:5
```
However, ren'py itself breaks this rule:
```
game/screens.rpy:567 define gui.about already defined at game/options.rpy:32
```
@renpytom If you like this rule but want to whitelist certain statements, we can do that. Or should gui.about not be duplicated?
> Add linting for redefined define/default statements

- renpy/script.py
This will print picking error for case:
```py
python early hide:
class Test():
pass
def parse_test(l):
rv= Test()
rv.a = 3
return rv
def execute_test(rv):
print(rv.a)
renpy.register_statement(
"test",
parse=parse_test,
execute=execute_test,
)
```
> Print exception which caused on write_rpyc

- renpy/main.py
Instead of calling `.endswith` for each extension, use `os.path.splitext` then use `in` operator with the extension on the list.
> Optimization for checking archive extension

- .gitignore
This PR adds several system files to this project's `.gitignore` to avoid them showing up in the Git workflow while working.
This chiefly includes auto-generated system files regarding `Thumbs.db` on Windows and `.DS_Store` on macOS.
Excluding these files ensures that the output of things like `git status` and `git diff` is less polluted.
> GitIgnore: Ignore several undesirable system files on macOS and Windows

- renpy/common/00action_menu.rpy
Draft to implement #2194 (Add transition variable to ShowMenu action), please review.
Please also do note that this is technically a breaking change, since the `transition` kwarg was previously consumed by `**kwargs` and passed to the screen. `transition` could be renamed, but any new kwarg to `ShowMenu` has this issue.
Resolves #2194 
~~this isn't hacktober spam I promise~~
> Option to specify transition in ShowMenu (for #2194)

- renpy/common/00nvl_mode.rpy
When retrieving the `kind` argument from a `_history_list` entry, characters whose kind is declared as `nvl` now return the string `"nvl"` instead of `"adv"`.
> History entries properly identify kind as nvl

- renpy/audio/audio.py
Fixes #2383 and stems from a discussion with @Andykl 
When calling `set_tertiary_volume` the secondary volume would be reset due to a magic number remaining in the code.
This patch fixes this by introducing a storage field for the raw value of the secondary volume, which it subsequently uses when setting the tertiary volume, thus keeping the propagation intact and correct.
> Fix a bug that would cause the secondary volume to reset in some cases

- launcher/game/itch.rpy
Adds User-Agent header info the web request which resolves #2394, at least on my machine.
The ssl unverified context was removed as it caused some issues with the Request
> Resolves #2394 Itch.io butler download 403 failure

- sphinx/source/style_properties.rst
The documentation for `order_reverse` was mistakenly located under the `Fixed Style Properties` header, rather than `Box Style Properties`, where it belongs. No changes were made to wording, just relocating it to the correct header.
> Relocate order_reverse property to Box Style Properties

- after_checkout.sh
This is a minor change for running the nightly build in Linux. The documentation mentioned being able to run `renpy.sh` after running `after_checkout.sh`. Issue is that `renpy.sh` is never linked in the script. This change adds that link in.
> added linking to the nighly build renpy.sh in after_checkout.sh 

- README.rst
Some systems don't have libjpeg-turbo8-dev, and need libjpeg62-turbo-dev instead. Use the libjpeg-dev metapackage like https://github.com/renpy/pygame_sdl2/blob/master/README.rst does, which seems to work everywhere. Also, use `$(uname -m)` instead of hardcoding `x86_64` so the same instructions work on ARM systems too.
> Make the module-building instructions more portable

- launcher/game/choose_directory.rpy
- launcher/game/tkaskdir.py
This PR hopes to make RenPy's project directory chooser more robust by supporting multiple backends. In theory Tkinter should be readily-available on Linux distributions, but in practice I find it surprisingly difficult to set up when trying to build and run RenPy when python3-tkinter is an optional package that doesn't come preinstalled on many distributions.
Neither the [Freedesktop SDK](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/master/NEWS) nor the [Gnome SDK](https://gitlab.gnome.org/GNOME/gnome-build-meta/-/tree/gnome-3-38/elements/sdk) include Tkinter, even excluding it from their Python builds, and even more problematic that there doesn't appear to be a complete tkinter package available on PyPi. Gtk on the other hand is much better supported and is straightforward …
> Add Gtk support for project directory chooser

- renpy/config.py
- renpy/display/layout.py
- sphinx/source/config.rst
This update adds a config variable, `allow_underfull`, which is `False` by default. If set to `True`, Ren'Py will display grids which are not full.
> Allow grids to be underfull

- launcher/game/tl/spanish/screens.rpy
- the_question/game/tl/spanish/screens.rpy
- tutorial/game/tl/spanish/screens.rpy
> Typos in Spanish translation

- renpy/display/im.py
- sphinx/source/displayables.rst
As discussed in #2427.
I didn't include `im.Data` because I don't think the same can be done without it (I have no idea how to do it, and it's a kinda obsolete functionality anyway).
I didn't include `im.AlphaMask` either because `Alphamask` is already linked in `im.AlphaMask`'s docline. Furthermore, using `Alphamask` to do `im.AlphaMask`'s work would require passing the control displayable through a Matrix to replace its alpha layer with its red layer (and even then it wouldn't override the base displayable's alpha channel, it would multiply it), resulting in a more complex workaround than the other examples I gave.
> Adding im and im.MatrixColor workarounds in documentation

- renpy/common/00layeredimage.rpy
fix for #2456 
After being wrapped into each Transform given by the at statement(s), the layeredimage is then wrapped in another Transform, taking all the given properties that can't be taken by the Fixed.
> fix layeredimages to take any transform property

- renpy/display/accelerator.pyx
If `fit` is set but not `xsize` nor `ysize`, the available size is fed to the fit algorithm instead.
The `width` and `height` parameters given to the `render()` method are interpreted as the available size.
Also since the `fit` property replaces the `maxsize` property, and this is a case when the `fit` property is supplied, the `maxsize` property is ignored.
An example of its use : it allows for backgrounds to be given only `fit='cover'` for them to cover the whole screen (if shown directly), so that the code using it doesn't have to be modified following the size of the screen.
**This code remains to be tested**, because as modifying or even deleting the `accelerator.pyx` file doesn't keep Ren'py from executing the function it contains (meaning it has to be compiled somehow, I guess), I …
> Enable the fit mechanism whenever the fit property is set

- tutorial/game/screens.rpy
- tutorial/game/tl/schinese/01example.rpy
- tutorial/game/tl/schinese/common.rpy
- tutorial/game/tl/schinese/indepth_character.rpy
- tutorial/game/tl/schinese/indepth_displayables.rpy
- tutorial/game/tl/schinese/indepth_minigame.rpy
- tutorial/game/tl/schinese/indepth_style.rpy
- tutorial/game/tl/schinese/indepth_text.rpy
- tutorial/game/tl/schinese/indepth_transitions.rpy
- tutorial/game/tl/schinese/indepth_translations.rpy
- tutorial/game/tl/schinese/options.rpy
- tutorial/game/tl/schinese/screens.rpy
- tutorial/game/tl/schinese/script.rpy
- tutorial/game/tl/schinese/style.rpy
- tutorial/game/tl/schinese/tutorial_atl.rpy
- tutorial/game/tl/schinese/tutorial_director.rpy
- tutorial/game/tl/schinese/tutorial_distribute.rpy
- tutorial/game/tl/schinese/tutorial_nvlmode.rpy
- tutorial/game/tl/schinese/tutorial_playing.rpy
- tutorial/game/tl/schinese/tutorial_quickstart.rpy
- tutorial/game/tl/schinese/tutorial_screen_displayables.rpy
- tutorial/game/tl/schinese/tutorial_screens.rpy
- tutorial/game/tl/schinese/tutorial_video.rpy
Though [Chinese documentation](https://renpy.cn/doc/) of Ren'py has already been complete, I think the tutorial game is more intuitive. Starters can see how it works in action. So I spent some time translating it into Chinese.
I name the translation as "schinese". And I add an appropriate option in Language preference screen. I also try to keep technical terms in the tutorial consistent with the Chinese documentation while translating. I hope these would be helpful.
---
By the way, have you thought about changing the font for Chinese, Japanese and Korean? In my view, SourceHanSansLite.tff is too limited, and sometimes not beautiful in Chinese. I suggest [Noto Sans CJK](http://www.google.com/get/noto/help/cjk/) from Google, covering Simplified Chinese, Traditional Chinese, Japanese, and …
> Translate tutorial game into simplified Chinese

- launcher/game/project.rpy
Fixes paths on Windows being returned with mixed separators.
Resolves relative paths in filename before joining to base directory.
Example of first issue which this fixes:
```py
project.current.unelide_filename("game/script.rpy")
u'C:\\Users\\mwillcock\\Documents\\testgame\\game/script.rpy'
```
...this was potentially passed to external programs if using custom editor configurations.
I'm presuming that it would be by design for project files to always be within the project folder, I cannot find any obvious usage contrary to that and monitoring calls to the unelide function doesn't seem to show any part of the program using it that way.
> Normalize project filename for unelide

- renpy/display/image.py
Now when several matches are found (given they all have every required argument), only the ones with the largest amount of optional arguments are kept. If there are still several, the exception is raised as it would have been, otherwise the one having the max amount of optionals is returned.
> Fix for choose_image ambiguity

- sphinx/source/displayables.rst
- sphinx/source/im.rst
- sphinx/source/matrixcolor.rst
- sphinx/source/save_load_rollback.rst
Some typos, and the fact that strings not referring already-defined images work fine even if the extension is missing.
> Doc minor fixes

- renpy/parser.py
Fixes paths on Windows being returned with mixed separators.
Resolves relative paths in filename before joining to base directory.
This matches the behaviour change from #2527, but for opening files from a running game.
> Normalize game filename for unelide

- renpy/common/00achievement.rpy
In addition to the setter already in place (the `achievement.progress` function), there's now a getter to display to the user inside ren'py, giving a use to the non-steam achievement progress tracking.
I directly used the persistent's implementation, since the steam's implementation of the `progress` function uses it directly, but if in the future several ways to store progress emerge, a `get_progress` method could be added to all subclasses of Backend, and the function could be a foreach loop like the others.
> Add a getter for the achievement progress

- renpy/exports.py
Right now, passing a keyword argument to the renpy.input() will throw:
TypeError: input() got an unexpected keyword argument '{}'
With this, renpy.input() takes keyword arguments and passes them to the screen shown with the function.
> Pass kwargs of input() to the shown screen

- gui/game/screens.rpy
`screen main_menu()` is probably the most customized of all built-in screens.
Currently styles in `screen main_menu` are applied to one `frame` and one `vbox` from `style_prefix`. This way, any time a developer adds a `frame` or a `vbox` to customize their `main_menu` they will inherit some unexpected properties (like `xsize`, `yfill`, `xalign`, `yalign`, a very specific `background`...).
Actually: `style_prefix` is useful to reuse the same properties in different children of the same type. But current properties defined in `style main_menu_frame` and `style main_menu_vbox` will hardly be reused.
My proposal is not to use `style_prefix` in the main menu, but apply directly those two styles to the two unique children that will use them.
This way, if developers add more `vbox` or `frame` to …
> Make screen main_menu() easier to customize

- renpy/text/ftfont.pyx
- renpy/text/textsupport.pxd
- renpy/text/textsupport.pyx
Specifically:
- Explicitly cast the Unicode characters to FT_ULong before doing bit ops.
- Add the decoded value by 0x10000 to get the actual Unicode value.
- Change the rest of Py_UNICODE castings to FT_ULong so the Unicode values don't get casted back to 16-bit when rendering.
- Make the decode routine easier to read.
---
This is a followup to #2653, which properly closes #2642.
> Fix issues that prevented #2653 from working.

- renpy/character.py
This fixes issue #2682 .
Adds the ability for the string type conversion to also "call" a callable "who". Currently, only __call__ will attempt a callable who conversion.
> Character class callable for string type

- renpy/display/behavior.py
I am of the opinion that when a player is using the keyboard to navigate the interface the location of the mouse should be ignored to avoid potentially confusing the player, but the mouse area displayable doesn't follow this principle. Ideally a mouse area would be able to tell if the keyboard-focused displayable overlaps with it and remain hovered then and only then, so it can be used to style/animate menus of buttons with built in keyboard support, but I have made the mouse area always unhovered when using the keyboard to navigate the interface as a simple solution in the meantime.
> Make mouse area stay unhovered when keyboard focus being used

- renpy/display/core.py
Fixed issue introduced by 3ee3794 where tts reads the children of containers in the wrong order.
> Fix order tts reads children in

- sphinx/source/movie.rst
Hi. I got contacted by a dev who wondered about poor video performances and blamed Ren'Py usage of a defunc library (libav.org).
I answered that there was probably confusion between the libav* libraries provided by FFmpeg and the old libav fork.
Nonetheless, the current documentation has an ambiguous usage of "libav" and I figured we could clarify.
> doc: clarify video library used

- gui/game/gui.rpy
- gui/game/screens.rpy
I have made two small tweaks to the default GUI so that it'll work more nicely on small-screen devices right out of the box.
One is adding a small variant for the text size of choice button texts, since unlike other text with specified text sizes choice button text didn't already have that and thus didn't change size on small-screen devices.
The other is changing two of the small variant styles, slider_pref_vbox and slider_pref_slider, to slider_vbox and slider_slider, since slider_pref_vbox and slider_pref_slider are unused styles.
> Improve small gui

- renpy/gl2/live2d.py
- renpy/gl2/live2dmotion.py
1. Combined get and wait methods of Motion class, as they called only from the Live2D.update function and do almost the same.
2. Fixed the issue that "hold on last frame" feature caused redrawing with 0 seconds instead of stop redrawing.
3. Fixed the issue when if curves total duration less than motion duration this used the default value of the parameter instead of the value from the last curve.
> Fixes for Live2D

- renpy/audio/audio.py
- sphinx/source/audio.rst
Ensures that we can sync the audio clip time of new music layer to a channel we specify. This will allow the music layers to remain in sync after save/load (\<from X\> doesn't sync after save/load, since X is at a different point after loading).
Usage:
Audio clip filename to play = "<sync [channel_name]>[audiofilename.ogg]"
> Can now sync to channel when playing audio

- launcher/game/tl/spanish/common.rpy
- launcher/game/tl/spanish/error.rpy
- launcher/game/tl/spanish/launcher.rpy
- the_question/game/tl/spanish/common.rpy
- tutorial/game/tl/spanish/common.rpy
Some missing strings (about JDK and errors).
And a funny typo (the non-existent word "Potapapeles" could be translated as "Barfpapers". "Portapapeles" is the correct one for "Clipboard".)
> Update Spanish translation

- renpy/display/transition.py
Allowed any displayable to take the role of the image controlling the transition.
Formerly only proper images were allowed, due to the use of the im. matrixes.
> Porting ImageDissolve to the new matrixcolor system

- renpy/common/00layeredimage.rpy
With renpy 7.4.3, when using attribute_function in layeredimage, `unknown attributes` warning are show in two cases:  
- `attribute_function`  returns `-attribute`, even if attribute is define in the layerimage defintion
- `attribute_function` returns a `variant` attribute
> Avoid unknown attributes warning in layeredimage

- renpy/exports.py
In projects where 'dismiss_unfocused' has been provided keys, these keys will also dismiss unfocused hard pauses. Generally this is undesirable, so this commit makes it so hard pauses use an empty list for the dismiss_unfocused parameter of the say behavior.
> make hard pause undismissable

- renpy/display/im.py
- renpy/loadsave.py
- renpy/savelocation.py
Old camelCase names still exists in Python 3, but now all the names in the code follow the snake_case scheme.
> Make threading function names consistent to snake_case

- tutorial/game/tl/korean/indepth_character.rpy
- tutorial/game/tl/korean/indepth_displayables.rpy
- tutorial/game/tl/korean/indepth_minigame.rpy
- tutorial/game/tl/korean/indepth_style.rpy
- tutorial/game/tl/korean/indepth_text.rpy
- tutorial/game/tl/korean/indepth_transitions.rpy
- tutorial/game/tl/korean/indepth_translations.rpy
- tutorial/game/tl/korean/script.rpy
- tutorial/game/tl/korean/tutorial_director.rpy
- tutorial/game/tl/korean/tutorial_distribute.rpy
- tutorial/game/tl/korean/tutorial_playing.rpy
- tutorial/game/tl/korean/tutorial_screen_displayables.rpy
Fixed some awkward Korean Translations
ex) game/tl/언어 -> game/tl/languages (directory names should not be translated...)
시각 소설 -> 비주얼 노벨 ('비주얼 노벨' is much more common form than '시각 소설')
and some translationese... like 그것은, 우리는, ...
> Fixed awkward Korean Translations

- renpy/display/layout.py
As previously described in #2782.
Using xfit or yfit in cunjunction with fit_first is not common, especially with string values for fit_first, but this may mess up some displays based upon the glitchy version.
Adding a config property could solve that problem, not sure it's worth it though.
> Keep xfit and yfit from overriding non-boolean fit_first values

- renpy/display/layout.py
When no terminal value is given to a ConditionSwitch, it shows Null().
Avoids triggering a "could not choose a displayable" exception.
Could be linked to a compatibility config variable.
> Add a fallback value for ConditionSwitches

- renpy/character.py
Document that `define eright = Character(kind=e, namebox.xalign=1.0)` is vallid Ren'py.
Another phrasing not mentioning the NotSet sentinel may be better.
> Document Character() not requiring a name

- renpy/common/00achievement.rpy
The code to clear a single achievement was treating dicts as sets.
Additionally, only clearing if the achievement was granted means that the progress is not cleared for half-progress achievements.
Closes #2870
> Fix single achievement progress clear

- renpy/config.py
- renpy/exports.py
- sphinx/source/config.rst
Almost all places where Ren'Py autosaves have a configuration variable that can be set to False to prevent Ren'Py from autosaving at that time. The exception is the input function. This commit creates a new config variable autosave_on_input which can be set to False to disable autosaving when players input text.
> autosave on input config variable

- renpy/exports.py
It adds them for the three corresponding `seen_*` functions:
- `seen_label`
- `seen_audio`
- `seen_image`
> Add mark_*_seen and mark_*_unseen functions

- renpy/common/00gui.rpy
Now when SetPreference is defined with rebuild=False the rebuild function won't be called, as said in the documentation.
> Fixed SetPreference rebuild attribute

- renpy/display/focus.py
If buttons with keyboard_focus True are shown but the first focusable element has keyboard_focus False, the focus_nearest function would focus on that first element when not focused on anything. This commit fixes that.
> Fix focus_nearest bug that ignored keyboard_focus

- renpy/common/00compat.rpy
- renpy/config.py
- renpy/display/behavior.py
- sphinx/source/config.rst
- sphinx/source/screens.rst
- sphinx/source/style_properties.rst
From @mal's idea and code.
Makes the default input caret blinking, and stops it from offsetting characters by 1px when activating/deactivating like it did before (that's the `xsize=0` part, no I don't understand it either but it works).
The blinking effect has 3 opt-outs :
1. you can set `config.input_caret_blink` to a False value for the whole game
2. you can override it for a specific input by setting its new `caret_blink` property
3. you can override all of this by replacing the default caret using the already existing `caret` style property
An addition to `renpy/common/00compat.rpy` can easily be done to disable it for previous versions, although I don't think it's worth it.
Adding `caret_blink` as a keyword in `renpy/screenlang.py` and `renpy/sl2/sldisplayables.py` didn't seem …
> Upgrade input's caret

- renpy/common/000atl.rpy
- sphinx/source/atl.rst
- sphinx/source/transitions.rst
Using the transition classes' time_warp arguments is much more easy when access is given to the already-defined functions.
The keys to the dict are already documented.
> Document access to the warper functions

- renpy/common/00layeredimage.rpy
It's dangerous as it becomes trivial to accidentally pollute what is expected to be a clean dictionary. The default `group_properties` as it stands never leaves this function, and is never written to, and so the current code is safe in that regard, however leaving it in the codebase becomes a landmine just waiting to be stepped on in future.
```py
>>> def foo(bar={}):
...     return bar
... 
>>> foo()
{}
>>> foo()['qux'] = 'leaky'
>>> foo()
{'qux': 'leaky'}
>>>
```
> Avoid using a dict as a default argument value

- sphinx/source/atl.rst
Obsolete since config.gl2 is now enabled by default.
A message like "This requires model-based rendering, which is enabled by default." could be put in its place, but I don't feel it's really relevent.
> Remove obsolete gl2 references in the doc

- renpy/lint.py
Applies the function when checking a recognised image, and stashes the original name so that the error report will match the line in the script being referenced (rather than reporting the adjusted version).
I believe this is the correct ordering, as it means it's the "real" tag that makes it's way into `image_prefixes`, but I'm not 100% sure.
Seeks to address https://github.com/renpy/renpy/issues/2978.
> Make lint config.adjust_attributes aware

- gui/game/options.rpy
`config.has_sound`, `config.has_music` and `config.has_voice` have other side-effects than toggling the appropriate mixers in the preferences screen. Such are hard to debug if not documented.
I believe this is the proper file to be copied in the new game as the default template.
The translations will need to be updated.
> Document config.has_channel side-effects

- sphinx/source/screens.rst
adresses #2139 
The fade transition has been replaced with pixellate, because it's clearer to see what's happening in the example.
> Document screens' _with_none kwarg and the call screen's with behavior

- launcher/game/preferences.rpy
So that theme options remain separated from the rest
> Reorder launcher preferences

- renpy/common/00layeredimage.rpy
Attempt at fixing #3011 solely within the confines of LayeredImage.
- Keeps any duplicates present in `attributes`. This is necessary to pass the match checking code in `image.py`.
- Extends them with any de-duplicated optional attributes.
- Checks all the attributes it's about to return are valid.
> Prevent duplicate attributes breaking LIs

- sphinx/source/displaying_images.rst
- sphinx/source/layeredimage.rst
- sphinx/source/transforms.rst
In layeredimages, when a group is `multiple` it's as if there was no group for the purpose of automatic name generating.
It's now documented.
> Edit and fix documentation

- renpy/display/model.py
Renames `properties` setter (now `property`) in line with siblings (`shader`, `texture`, etc) to avoid conflict with instance property of the same name. Non-breaking as any attempt to call this method previously would have found the instance property and resulted in:
```
TypeError: 'dict' object is not callable
```
Found while poking around #3024, but is tangential and does not address that issue itself.
> Exception when setting GL props on Model displayable

- launcher/game/tl/spanish/launcher.rpy
Personalizas is not correct on the context of the tl
Corrected at: Personalizado
Another Corrected form: Personalizar
> Fixed Spanish TL: Personalizas

- renpy/ui.py
```
label start:
$value = ui.ChoiceReturn("rock", "Rock", location="label_start", block_all=True)
pause
return
```
Before such change, this code will leak the reference to `persistent._chosen` to saves. This dict may be big and saving it is redundant.
> Make ChoiceActionBase.chosen a property

- renpy/common/00musicroom.rpy
If music is currently playing it will pause, otherwise it will resume from where it stopped.
In case a music has already finished, the queue will play the music again from the beginning the next time it is called.
If the music is playing the button will receive the selected status and when paused it will be removed.
Note:
`__MusicRoomTogglePause` is based on `__MusicRoomStop`, because in some tests in my project, if `__MusicRoomTogglePause` was the same as `__MusicRoomTogglePlay` it caused some data about the music being played added using `add(action=[SetVariable("jb_title", title)])` not to be displayed.
Inspired by the report I did before #3054
> Added TogglePause on MusicRoom

- renpy/persistent.py
- renpy/savelocation.py
Without this the code
```
label start:
$persistent.var = True
$renpy.save_persistent()
"Text"
```
will cause reading and unpickle of just saved persistent data by `persistent.update()` in idle frame, which is (I think) redundant.
> Do not unpickle persistent just after the save

- renpy/display/screen.py
the `try`/`finally` block in screen.py still had exception possibilities, and when raised due to an unsafe dict key removal in the `finally`  block, the original exception was completely lost, leaving what was shown as something somewhat unrelated and very misleading.
This PR adds the `except` block and prints its exception info to the log file, making it easier to see what went wrong and where, additionally I have changed the `del` statement to be safer, using `dict.pop` with a default value of `None` as to not raise a further exception.
Examples from traceback:
Where `_scope` isn't used at all in our game's code.
Rest of the trace leads back here.
> Fix scope deletion in screen.py

- renpy/common/00nvl_mode.rpy
`config.nvl_page_ctc` overrides Character's (actually ADVCharacter's) `ctc` argument.
In the constructor, the argument is converted using `renpy.easy.displayable_or_none`, so passing a string replaces it with a displayable, internally. Which means the code accessing it relies on it being a displayable.
That conversion is not done in the case of `config.nvl_page_ctc`. Which means the `display_say` function finds itself with a string and calls `_duplicatable` on it.
I patched the only place in the code where the config variable is read, by wrapping it in the displayable_or_none function.
> Patch config.nvl_page_ctc not being a displayable, fix #3116

- renpy/common/00matrixcolor.rpy
Messy diff, ([hiding whitespace helps](/renpy/renpy/pull/3111/files?w=1)) but the tl;dr is:
- `ContrastMatrix` was using `-.5` in `step3` rather than `.5` leading to poor results.
- The doc block was in the method instead of the class, and so not being generated for the website.
- Turns out Contrast is a scaled and inverted InvertMatrix, which allows us to avoid the triple Matrix combination.
The first two points are hopefully pretty unobjectionable, but if you feel the third hurts maintainability I can remove that commit, it's definitely not as straight-forward to grok.
> Fix and expose ContrastMatrix

- launcher/game/updater.rpy
Otherwise the button stays red after an update, until a full day passes.
Now the button will start grey after the restart, and will stay grey after the check.
> Force refresh update state after updating

- launcher/game/tl/german/common.rpy
I noticed many of the "German" translations were left in English. I tried to fix as many as I could, but a few I was still unsure about. ("Clipboard voicing", in particular.)
As a general note, these older translation files seem to be missing strings from the renderer (shift+G) screen.
> Update German translation in common.rpy

- renpy/display/layout.py
- renpy/display/pgrender.py
- renpy/display/render.pxd
- renpy/display/render.pyx
- renpy/display/swdraw.py
- renpy/display/transition.py
- renpy/gl/gldraw.pyx
- renpy/gl2/gl2draw.pyx
This removes `Render.opaque`, `Render.visible_children`, `Render.is_opaque` and `Surface.is_opaque` and all its uses.
If I understand correctly, it was only useful in SWDraw, and since it's not used to render creator things now, it can be removed. Also, it has not been used since 2018 and no one seems to be hurt about it.
This fixes #3089
> Some clean up of Render

- renpy/character.py
- renpy/common/_developer/inspector.rpym
- renpy/display/core.py
- renpy/display/dragdrop.py
- renpy/display/im.py
- renpy/display/image.py
- renpy/display/layout.py
- renpy/display/screen.py
- renpy/display/transform.py
- renpy/parser.py
- renpy/text/text.py
As per #3069.
The template I used in Displayable subclasses is slightly different from @Andykl's.
Andy's : `<MyModule.MySubclass object at 0x00000000 optional_repr_info>`
Mine : `<MyModule.MySubclass object (optional_repr_info) at 0x00000000>`
The parentheses were chosen to separate the aditional info from the class name and other text such as the "at" and "object" words.
I didn't choose brackets or square-brackets to avoid substitution issues (although they're unlikely to happen).
The placement, between the "object" and the "at", should prevent people from interpreting it as constructor arguments, and also placing it after the address seemed weird.
If you prefer Andy's style, it's available in my code, just commented out.
As it were, MultiBox's repr is a special case which overrides the …
> Fix repr for Displayable subclasses

- renpy/translation/__init__.py
This change is backwards compatible as it only adds an alternative identifier to Translates that did not have one.
> Provide alternate identifier to translates with id clause

- renpy/translation/__init__.py
Such code will be executed correctly on default language, but chained translations will have corrupted return point.
```
label start:
"Line 1" id start_00000000
"Line 1" id start_00000000
return
```
> Report translate nodes with duplicate id clause

- renpy/savelocation.py
After we added the use of save rename function, we have started to get errors referring to WindowsError: [Error 183] Cannot create a file when that file already exists. I don't know why it happens only for some of them, but this should fix the problem.
> Delete temporary renaming file if it exists

- module/fribidi-src/lib/common.h
Cherry-picked from https://github.com/fribidi/fribidi/commit/f20b6480b9cd46dae8d82a6f95d9c53558fcfd20
> fribidi: use error preprocessor directive correctly

- renpy/gl2/gl2shadercache.py
Fix the last issue in #3217, the gl2/shader part.
This is a hotfix : all gl2 type issues haven't been solved. You can still see this in the log.txt file :
```
Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1080)
swap interval: 1 frames
Windowed mode.
Vendor: "b'NVIDIA Corporation'"
Renderer: b'Quadro P1000/PCIe/SSE2'
Version: b'4.6.0 NVIDIA 472.39'
Display Info: None
Screen sizes: virtual=(1280, 720) physical=(1280, 720) drawable=(1280, 720)
Maximum texture size: 4096x4096
```
Notice the b before the strings, indicating use of bytestrings instead of actual strings.
The culprit code is in renpy/gl2/gl2draw.pyx, line 392. Using type `char *` means a use of bytes strings, as opposed to `wchar *` for unicode (I think).
Concern should also be raised about the wide use of …
> Type hotfix for gl2 model management

- renpy/__init__.py
- renpy/compat/pickle.py
- renpy/loadsave.py
The first issue was a discrepancy in pickle.HIGHEST_PROTOCOL between py2 and py3. This has been adressed by setting a (new) preferred protocol, 2 being the highest of the protocols supported by both.
Now, renpy8 saves can be loaded from renpy7 🥳.
The second issue tries to address a [known incompatibility](https://bugs.python.org/issue6784) between pickle from py2 and py3.
Using the keyword-arguments break pickle loading in renpy7 (don't try it at home kids, it erases the launcher preferences), but until the py3 pickle problem is definitively fixed (which it is not) I wanted to keep the main way of doing things as the first thing py3 would try.
*This* fix enables the renpy8 launcher to read the preferences set in the renpy7 launcher, which is the case between two renpy7 installs' …
> py3 pickle fixes

- launcher/game/EasyDialogsWin.py
While choosing project directory where new projects are saved by default renpy crashes and gave a traceback saying bytes or integer address expected not str. I convert those strings to bytes. It's just a small fix
> Fixing str for bytes error, thrown while choosing project directory.

- renpy/compat/pickle.py
This fixes an error occuring when reloading a py3 game defining datetime objects.
Why it works, with the partial objects being class attributes and not instance attributes defined in `__init__`, is anyone's guess.
> Fix datetime pickle hack

- renpy/loadsave.py
Normally, the persistent data file is saved when the game exits. However, on renpyweb/emscripten, this does not happen. It seems @Beuc tried to work on that issue but gave up eventually. My guess is that the `beforeunload` event that is fired when the page is closing does not allow to write new files to the virtual FS.
This PR is a workaround, so that the persistent data file is updated each time a new save is created. Thus, even if the persistent data file is not saved when the page is unloaded, a version that matches the latest save will exist (could be the periodic autosave, but here again, no autosave is written when page is unloaded).
> Update persistent file while saving on emscripten

- renpy/display/transform.py
This allows
```rpy
define centr = Transform(align=(0.5, 1.0))
image test = centr("#fff")
```
following the example of
```rpy
transform centr:
align (0.5, 1.0)
image test = centr("#fff")
```
> Allow Transform-defined transforms to take strings

- renpy/common/00achievement.rpy
I believe this is a typo. `config.default_tag_layer` should be the right variable that `config.tag_layer` defaults to.
> Replace "config.default_tag_name" with "config.default_tag_layer" in the docs

- renpy/config.py
- renpy/display/image.py
- sphinx/source/config.rst
This is to support images having a "weak" set of default attributes
applied to them when they are first shown, allowing for more complex use
cases with a minimum of boilerplate in scripts.
While similar in nature to the existing `config.adjust_attributes`, this
feature only applies to images when they are first shown, and is "weak"
in the sense that it may not countermand attributes from the script.
> Add config.default_attributes callback dictionary

- renpy/character.py
- renpy/display/image.py
The `wanted` and `remove` kwargs on `Character.resolve_say_attributes` and
`images.apply_attributes` were previously used to support the speaking
attribute feature, however that has since moved over to using the
temporary attribute functionality and these parameters are never passed
as anything beside empty lists, so we can clean them up.
> Clean up disused kwargs on attribute functions

- renpy/common/_developer/developer.rpym
This import fails in renpy8 when doing Shift+D then "Variable Viewer". The new import seems to display things just the same.
> Patch module not found in py3

- renpy/display/transform.py
Trying to coerce the `child` arg to `Transform.__call__` into a displayable
adds an avoidable call and could lead to redundant duplication (in the
case where the coercion yields a duplicatable displayable).
Instead, use `getattr` in the duplicatable check to prevent raising and
allow `__init__` (which already does arg coercion) to handle it as normal.
Related to #2102, and #3228. /cc @Gouvernathor
> Improve duplicatable check to consolidate coercion

- renpy/common/_developer/developer.rpym
Since `file` doesn't exist in py3, I replaced it with `open` instead. During my testing the menu worked again.
> Fix a crash in dev menu

- renpy/display/core.py
This PR allows Python statements to be executed in Ren'Py process from Javascript. Currently, the interface between JS and Ren'Py is pretty limited and adding new functionalities to it requires to recompile the emscripten application, as there is no feature in emscripten/SDL to allow generic communications between JS and the application. Being able to execute Python statements in Ren'Py process directly allows more powerful controls from JS without having to recompile anything.
The changes make Ren'Py look for a specific MEMFS file during idle frames, and execute its content as a Python script. Using a file in MEMFS makes sure the lookup will be fast and no FS sync is required. The file creation and execution errors are handled by JS (see the related PR in renpyweb).
I don't know Ren'Py …
> Allow Python statements to be run from JS (emscripten)

- launcher/game/tl/schinese/common.rpy
Change 免费软件 (means "free-of-charge software") -> 自由软件 (which is closer in meaning to "libre software")
> Simplified Chinese translation: Correct term

- renpy/script.py
Had a crash like this
```
File ".../renpy/renpy/script.py", line 276, in load_script
script_files.sort()
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```
Since script directory can be `None` (if the script file is in an archive), during sorting we might compare `str` to `None`. For example, when there's 2 scripts with the same name, but one is in an archive. This is a very rare case, but I thought we could still fix it.
Apparently it's fine in Python 2 (somehow?), but in Python 3, it will crash.
Building doesn't seem to be affected, before files w/o dir would come first, now they are treated as `""` which should put them ahead of the other files just like before.
> Prevent possible crash in `Script.load_script`

- renpy/python.py
- renpy/rollback.py
Games that make liberal use of stores end up with (a small amount of) redundant work being done during rollback, saving, and loading; proportional to the number of stores used and length of rollback, even if the majority are infrequently changed. This PR seeks to improve that without detriment to the more typical case involving no more stores than Ren'Py creates itself (14 including the default).
---
Currently keys for every store are added to a `Rollback` object's `stores`
and `delta_ebc` dicts, even if they contain no data. When rolling back
these dicts are iterated over, and the empty stores amount to no-ops.
These empty data structures are also serialised/de-serialised by the
save system (albeit efficiently) but yield no benefit.
This change is to skip recording entries for stores …
> Skip recording deltas for stores that don't change in rollback

- renpy/common/00action_data.rpy
Document that Set/ToggleScreenVariable will affect the top-level screen when used withing a used screen.
> Document ScreenVariable's top-level screen meaning

- renpy/execution.py
I've noticed that when creating dynamic variables for sub StoreModule, this doesn't work correctly.
I left a case with an example below.
Also with comments on how dynamic stack behaves.
```renpy 
default current_label = None
default previous_label = None
default test.current_label = None
default test.previous_label = None
init -999 python:
def reach_label(label, action):
if label.startswith("_"):
return
renpy.dynamic("current_label", "previous_label")
renpy.dynamic("test.current_label", "test.previous_label")
store.test.previous_label = store.test.current_label
store.test.current_label = label
store.previous_label, store.current_label = store.current_label, label
config.label_callback = reach_label
label pre_start():
"[current_label] == [test.current_label]"  # pre_start == pre_start …
```
> Correct work of dynamic stack for sub StoreModule.

- renpy/character.py
I'm currently working on a game where dialogue can be repeated by revisiting the same label.  Using an equality check, I can use a callback to prevent the history from showing the same line multiple times in a row.
> Add equality comparison to HistoryEntry

- sphinx/source/movie.rst
I add the below sentence doc.
It depends on the ffmpeg native decoders whether movies with alpha channel work
correctly. We recommend using mask or side_mask for that purpose.
> add doc about movie with alpha channel

- launcher/game/editor.rpy
- launcher/game/options.rpy
Pretty self-explainatory. The RENPY_ATOM environment variable allows for a non-renpy-issued version of Atom to be used, so having to download the Atom dlc for this bypass to work is somehow paradoxical.
This is a duct-tape fix, as it involves the existence of the "atom" subfolder even when Atom is not actually installed.
However, the existence of Atom.edit.py was not (and is still not) sufficient for renpy to consider Atom installed, so this shouldn't cause any unintended change in renpy's behavior.
Solving this properly would probably need a comprehensive understanding of how the other editors are handled, and of how things work in other platforms than windows, which I don't have.
> Do not download Atom when environ RENPY_ATOM is set

- sphinx/source/persistent.rst
Adresses #2166 and #3354. The use of default is recommended, and the use of define is not mentioned.
Maybe it could be the place to say that `persistent.substore.x = val` doesn't work, even though it doesn't currently raise an exception ? (that is, until #3177 is merged)
> Better document how persistent works with default

- renpy/display/layout.py
fix #2795
Having the line number for the *grid* is "simple" (don't quote me on this), having the line number for the *element* making it overfull is not.
I guess that by writing the SL parser differently, it could report the line of the extraneous element by itself, but I wouldn't recommand going that way just for more accurate error reports.
> Move overfull check in the Grid's add method

- renpy/parser.py
This fixes the issue when SDK is by path inside projects directory, lint `if common(node)` behaved wrong.
This change is backwards compatible, because at the end (built game) renpy_base and basedir are the same path.
> Distinguish renpy_base correctly even if it is inside gamedir

- tutorial/game/01example.rpy
Now the translation of the example isn't ignored when copying it.
Fixes #2388
> Fix code copy button doesn't copy the translated example

- renpy/ast.py
- renpy/common/000namespaces.rpy
For now special namespace sub-stores isn't possible or supported, so
there's no need for the machinery to support it. At such time we have
a clean way to implement it this method can be updated to support it.
Talked it over with @Gouvernathor and they're happy with this and will
re-introduce delegation machinery if/when there's a clean solution to
add sub-stores to the persistent namespace.
Considered defining `STORE_DOT = len('store.')` to avoid the magic `6`,
but ultimately decided that a comment should be sufficient.
> Prevent special namespace sub-store creation

- sphinx/source/screens.rst
This seeks to explain the consequences of having or not having parentheses and parameters in a screen. It also links parts of the doc referring to common subjects, which I think should happen more frequently.
> More documentation about paren-less screens

- renpy/atl.py
This fixes the issue with such code
```
label main_menu:
return
define config.default_transform = None
image base:
Text("image 1")
pause 1.0
Text("image 2")
pause 1.0
repeat
transform centr:
align (0.5, 0.5)
image test = centr("base")
label start:
pause
show test
pause
hide test
pause
show test
pause
return
```
Where if `test` was hidden in state of `Text("image 2")` it does not starts from the beggining on second show, which is inconsistent with  `define centr = Transform(align=(0.5, 0.5))`.
Fixes 2nd point in #2102.
> Duplicate child during ATLTranform `__call__`

- renpy/lint.py
Resolves #1287 and resolves #3182.
Opted to call `_start_store` rather than loop over `config.start_callbacks` so if something else is added to `_start_store` later this won't need to be revisited.
> Execute default statements prior to linting

- renpy/display/matrix.pyx
fixes #3184
Having `matrix[k] != matrix.m[k]` is weird, granted. But changing the really faulty thing here, the `fields` list, would break compatibility with the existing matrices having been constructed and accessed via the .?d? accessors.
A quick look in the current code shows no use of the [ ] operator on Matrix instances, and it is undocumented, so this one should be broken rather than the three-letter accessors.
An argument could be made to remove the getitem and setitem methods altogether, since 1) it's undocumented, 2) it's about to change behavior, 3) it accesses the elements of the matrix in one-dimension when the matrix has two dimensions.
There could also be a renpy.object.Object-like \_\_version__, getstate and setstate but since current Matrix instances have no …
> Fix Matrix's getitem, setitem and repr

- renpy/atl.py
Addresses two issues with ATL related to fast-forwarding:
- The first commit resolves an issue where, when fast-forwarding, ATL would block on a function call that returned None.
- The second tackles an issue where, when fast-forwarding through ATL, one frame from every interpolation is shown in rapid succession due to the first_frame flag. To avoid this, we only set the flag if the `st` rests within the duration of the interpolation. This ensures that the flag is correctly set, but only for the single interpolation that will be active when `st` is reached.
> Fast-forward focused ATL tweaks

- renpy/display/video.py
fix #3394 
Contrary to #3395, this PR handles the following situation:
```rpy
define good_ending = Movie(...)
define bad_ending = Movie(...)
default ending = bad_ending
label start:
...
show expression ending
```
If a game is saved on a device where the underlying movie file exists, then loaded on a device where it does not, the Movie object will now be unpickled with a None \_play attribute.
If a game is saved on a device where the file does not exist then loaded on a device where it does, the Movie object will be unpickled with the correct filename as a \_play attribute, because it will have been saved as \_base_play.
> Fix Movie._play being invalid

- renpy/common/_layout/classic_load_save.rpym
Prevents an error being raised when comparing against `mtime` in the `for` loop just below due to comparing an int to None.
> Avoid incomparable None error in classic save menu

- renpy/__init__.py
In py3 modules get `mappingproxy`s for their `__dict__`, which are essentially immutable dicts. As such they have no `clear` method and trying to use it raises exactly as you'd expect. Some modules do end up with real dicts for various reasons, so in theory we could typecheck this, but as we're deleting the module anyway, I believe that should suffice to see it garbage collected, and the removal from `sys.modules` should ensure it's re-imported/executed.
> Avoid trying to clear the mappingproxy type

- sphinx/source/live2d.rst
Adapted from [this advice](https://github.com/renpy/renpy/issues/3093#issuecomment-945160706) from #3093.
Watch out, the code I added only works in python 3. A py2-compatible way is `return kwargs.pop("fallback", None) or Placeholder(text="no live2d")`.
> Add workaround advice for live2d being missing or disabled

- renpy/common/00build.rpy
Given it's placement in the list, my guess is that the current `pyd` exclusion is a typo, with the intent being to exclude Cython `pxd` files. However since the `pyd` extension is used to denote a Windows-specific Python DLL, this isn't a certainty only likely.
Also noticed and fixed `build.remove` which was non-functional.
> Fix potential typo in build exclusions and fix build.remove

- renpy/exports.py
Fixes 3df81cd81: `get_at_list` can return both `None` and `list`, doing `list(None)` raises a `TypeError`.
Could probably do `get(tag, [])`, but to keep things compatible we can None-check.
> Fix regression

- renpy/text/text.py
- renpy/text/textsupport.pyx
- sphinx/source/style_properties.rst
I add Language style property "anywhere" which allow linebreaking at anywhere without ruby.
This is intended to be used when keeping a layout is preferred.
> add Language style property "anywhere" which allow linebreaking at anywhere

- renpy/revertable.py
Looking at the [python docs](https://docs.python.org/3/library/stdtypes.html#set), "Binary operations that mix set instances with frozenset return the type of the first operand. For example: `frozenset('ab') | set('bc')` returns an instance of frozenset."
Therefore, the functions being wrapped here should never actually return a frozenset.
And even if it somehow did, it would convert a frozenset to be mutable, and I would consider that an even greater mistake.
> Remove frozenset from the revertableset methods

- renpy/atl.py
Seeks to address #1650, without triggering regressions in #1254, #2834, #3041, or #3305.
Takes the original intent from 6a3aad948ffb6837b8ca85a2e8dfb3d9d84c4671 - to allow `pause 0` to ensure that at least one frame is shown before progressing, even when technically there isn't time to do so.
Where the previous approach applied this behaviour unilaterally, carving out various exceptions, this approach opts to instead actively target the special case and deal with it in isolation, which limits the impact of the forced frame on catch up in various scenarios that have appeared over the years - see referenced issues.
> Revisit the original intention of ATL first frame

- renpy/common/00placeholder.rpy
- sphinx/game/doc.py
- sphinx/game/script.rpy
- sphinx/game/shaderdoc.py
This fixes sphinx in-game project I/O issues related to relative paths when renpy.py is launched from its base directory instead of from within the sphinx subdirectory.  Older file I/O patterns (open/close) have been updated to their newer forms (with open() as)
> Sphinx-directory-traversal

- sphinx/source/cds.rst
This PR makes the following changes to the CDS docs:
- Move the example section to the top of the page. This established a hierarchy for the information from broad to increasing in specific detail.
- Adds return values to the Lexer class docs.
- Change Lexer method docs from a passive voice ("Returns the apple") to an active voice ("Return the apple")
> Rewrite docs for Creator-Defined Statements

- renpy/common/00preferences.rpy
- renpy/display/core.py
- renpy/preferences.py
- sphinx/source/preferences.rst
Attempted implementation of #2645. Governed by a preference; should pause all audio tracks when the game window is minimized and resume them when it is maximized by default.
> Pause audio when window is minimized

- renpy/curry.py
The underlying functools.partial doesn't have an \_\_init\_\_ method, so the
super call bounces up to object which doesn't take arguments. This is
fine in normal use but presented issues in some pickling scenarios.
Since we can be slightly more efficient without it, and it avoids the
edge cases with pickle, nuke it.
> Remove __init__ from new Partial class

- sphinx/source/dialogue.rst
- sphinx/source/displaying_images.rst
fix #3443
I also expanded the doc about the show statement to include how the minus sign behaves.
> Expand doc on @ and minus for image attributes

- renpy/config.py
- renpy/preferences.py
- sphinx/source/config.rst
Currently, volume bars show that value as 0 when it is mute and changing the bar disables mute.
I added config.show_volume_in_mute.
If False, the default, the behavior isn't changed. Otherwise, volumes are shown and adjustable while keeping mute when it is mute.
> add config.show_volume_in_mute

- sphinx/source/audio.rst
It was documented in renpy.music.play but it's also valid with the play statement.
> Document if_changed for the play statement

- tutorial/game/tutorial_atl.rpy
Just noticed this while going through the tutorial. I'm not sure if the second "to" is actually needed, but I am fairly sure the first one is supposed to be "do."
> fix (tutorial): Correct typo in dialogue

- renpy/substitutions.py
Previously nested interpolations would lose scope due to it not being
pushed down into the recursive call. Unfortunately the fix is slightly
non-trivial.
The string.Formatter class does not naturally expose the provided scope
to the convert_field method which is where we need it for nested
interpolations. In order to get it there we use the expectation
(documented, see ref) that the value provided to convert_field is the
obj returned by get_field which is supplied with the scope.
Additionally we handle nested interpolation via a call to self.vformat,
rather than round tripping through renpy.substitute since we're actively
not translating or changing the scope.
Fixes https://github.com/renpy/renpy/issues/3492
> Fix scoped nested string interpolation

- renpy/atl.py
Restores the "has state" exception that was mistakenly removed in b0dc9df96c3a95ceb2fdfc15b0f5fab0891dfe49.
> Fix regression in ATL pause 0

- sphinx/source/changelog.rst
- put the part when things are supported outside of Python before the part where thins are only supported inside Python, to make it clearer what we mean by "in Python" in that context
- make it clearer that f-strings are only supported in pure-python areas, and that they aren't recognized by the parser in most other areas
- move a misleading dot, to make it clear that in that context 1 is an integer
- unless I'm mistaken the optimizer flags disable the assert statement, not the yield statement
> Tweak changelog formulations

- launcher/game/front_page.rpy
- launcher/game/preferences.rpy
- launcher/game/tl/french/launcher.rpy
I added *some* fancy things : clicking on a language chooses it, and displays its name at the end of the second sentence (in its own language). But the sentences ("Hello" and "Start using renpy") display in the language being hovered by the user (or, if none is hovered, in the chosen language).
The choice isn't enacted using the Language action until the return textbutton is clicked, that is to avoid unnecessary computations.
> Launcher language prompt

- renpy/common/000statements.rpy
- sphinx/source/screens.rst
I've seen quite a few people asking how to call/show a screen using an expression, they often try to do it using the syntax close to `call expression` for labels. I also had to use `renpy.call_screen` when I only had a variable with the screen name.
While there's a way to do it directly using Python, I think having a way to do it from RenPy which is intuitive (since the syntax is very similar to `call expression`) will be beneficial.
At first I only wanted `call screen expression` and `show screen expression`, but I think having `hide screen expression` won't do harm.
> Implement show/call/hide screen expression

- renpy/common/000statements.rpy
1. Do not evaluate screen in `audio` namespace.
2. Don't suppress the real exception that occurred in screen evaluation.
3. Return early in screen prediction if screen evaluation failed.
> Fixes for show/call/hide screen expression

- renpy/display/layout.py
- sphinx/source/screens.rst
This fixes 2 problems, documents another, and there's potentially one more, but I'm not sure about it.
The first issue is `self.offsets = [ None ]` causes a crash, that's because it's being unpacked as a tuple in the event method. Since it's `None`, it can't be unpacked. I set it to `[(0, 0)]`, but maybe it should be set to an empty list?
The second issue is `if self.focus`, `focus` is a method of the parent class (`Displayable`), that `if` check will always be evaluated to `True`. I think it was intended to be `if self.focus_rect`.
The third issue is using `focus` in the `NearRect` constructor. The `Displayable` class it inherits has a parameter named `focus`, but it seems to be doing something else. In the parent class `focus` sets `focus_name`, in `NearRect` it sets `focus_rect`. Right …
> NearRect fixes

- renpy/common/00build.rpy
- sphinx/source/build.rst
Sets the distinction between archive names and file_list names, how to expand these lists of names, and when each is valid or not.
I.e this says that archives should not be included in other archives, or be given as file lists to the build.package function.
fixes #3548
> Clarify the build/distribute functions

- renpy/common/00action_control.rpy
Does the Action documenting part, last mentioned in #3577.
> Document renpy.show_screen's kwargs in screen-related actions

- gui/game/screens.rpy
- the_question/game/screens.rpy
- tutorial/game/screens.rpy
The previous change made to the comment 'as it is above' useless
> delete unnecessary comment

- renpy/atl.py
This makes any expression used in ATL cached in bytecode.rpyb
> atl: `Context.eval` now uses `renpy.python.py_eval` instead of Python `eval`

- renpy/atl.py
- renpy/common/00compat.rpy
- renpy/config.py
- sphinx/source/changelog.rst
- sphinx/source/incompatible.rst
Fixes https://github.com/renpy/renpy/issues/3636, and adds documentation and compat for the original change.
> Restore blocking to functions that delay

- renpy/ast.py
- renpy/config.py
Parameter order of `renpy.with_statement` changed [11 years ago](https://github.com/renpy/renpy/commit/23240e634ae93039093719643b3cb73fbf44323e#diff-6add03b804c4c72050f3509ad4c97251fbc5a63c153ac4be12051121259c1af0R839) (I suspect by accident - it was a docs commit) which resulted in the value intended for the `paired` parameter being passed to `always` instead. This in turn meant that the `paired` parameter for `with_callback` was always `None`.
https://github.com/renpy/renpy/blob/f50dd2f02de94fb9b657173b107b99f7ca806315/renpy/exports.py#L1606
I believe the only time that `paired` (and thus `always`) would be truthy without this fix would be when `trans is None`, since the only paired transition is the implicit `with None` added prior to inline `with` statements, and since the purpose of …
> Fix paired parameter of with_callback

- renpy/loader.py
Addresses `AttributeError: 'SubFile' object has no attribute 'readable'` and series of follow up issues when using a `SubFile` object with `io.TextIOWrapper`.
Triggered by calling `renpy.open_file(path, encoding='utf8')` where `path` is inside an RPA.
> Fix opening a file with encoding from an archive

- launcher/game/options.rpy
- renpy/common/00build.rpy
Move existing exclusion from the game level to the SDK level.
> Avoid distributing python interface files

- renpy/display/core.py
These calls appear to be the suggested way to notify an Android system that your app is ending. While `finish` will leave the app in the "recent activities" screen, `finishAndRemoveTask` will remove it.
I've only had the chance to test these calls via the console, but the behaviour they exhibit matches my expectations based on the Android docs, and what seems to make sense for backgrounding behaviour and the `quit_on_mobile_background` config flag.
https://developer.android.com/reference/android/app/Activity#finish()
https://developer.android.com/reference/android/app/Activity#finishAndRemoveTask()
> android: Notify system that we're finishing

- sphinx/source/trans_trans_python.rst
The doc initially says that the fields of Transform corresponding to transform properties "may not be modified outside of the constructor", so after object creation.
This is contradicted by two things. First, the `function` argument, whose purpose is to mutate these attributes.
Second, the `update` method, which "should be called when a transform property field is updated outside of the callback method". Although the "callback method" wording is dubious (and I included a correction), it clearly implies the fields are modified outside of the constructor.
So I added a clarification listing these three cases as times when tprop fields can be set.
> Clarify Transform's fields' allowed use

- renpy/common/00gallery.rpy
The parametrisation of the `gallery_navigation` screen in 95dc99f972ac8aeb139e411a01cbda23a3ba671c rendered it unable to access the `gallery` object, the fix is to explicitly pass it as a parameter.
This is the fix that was suggested by the original reporter (lsf user RFB).
ref: https://lemmasoft.renai.us/forums/viewtopic.php?p=552591#p552591
> Pass gallery object to gallery navigation screen

- renpy/exports.py
- sphinx/source/build.rst
- sphinx/source/conditional.rst
- sphinx/source/dialogue.rst
- sphinx/source/displaying_images.rst
- sphinx/source/label.rst
- sphinx/source/quickstart.rst
- sphinx/source/statement_equivalents.rst
This adds another wiki thing to the doc : the "Main article" references at the beginning of a section. I'm not too sure about the term "article", as it was taken from wikipedia but may be less relevant here.
This also moves the renpy.pause function from the "others" page to the statement equivalents page.
> More internal references within the documentation

- renpy/exports.py
- sphinx/source/config.rst
Proposed solution to #3690, a regression introduced by #3650.
The code being removed was unreachable prior to 7.5/8.0 due to a bug meaning that the `paired` parameter was never passed. This meant it could never be a `dict`, and that this code was unreachable.
An alternative solution could be to gate this behind a compat flag, however as has been noted in the issue, it appears that no one has missed this for over a decade, and while the information in the callback is useful (hence the fix that lead us here), it's possible that the added flexibility of paired `dict`-transforms is not.
> with: Remove previously unreachable code

- sphinx/source/3dstage.rst
In document, default perspective is False, but actually None.
> fix doc perspective defaut to None

- renpy/execution.py
the field is required for it to compile in python 3.8+
> Add missing field to Module node

- launcher/game/mobilebuild.rpy
Fixes https://github.com/renpy/renpy/issues/3711
In py3 the print_exc function prints a str, which files opened in binary
mode do not like. Conversely py2 doesn't seem to mind whether the file
is in binary mode or not.
This matches the approach taken in the rest of the file, where various
logs and outputs are also not opened in binary mode any longer.
Error recreated and change tested with this code on Linux using python2 binary from 7.4.11, and python3 binary from 8.0.0:
_This represents the fix, see comments for bug recreation._
```py
import subprocess
import traceback
for bin in ('sh', 'nonexistant'):
with open('tmp.txt', 'a') as f: # change to 'ab' to recreate bug report
f.write("\n\n\n")           # change to b"\n\n\n" when recreating bug report
try:
subprocess.Popen([bin, '-c', …
```
> py3: Update mobilebuild exception logging

- sphinx/source/translation.rst
```py
label start:
e "This used to have a typo." id start_61b861a2
```
> [DOC] improved translation ID example

- renpy/display/transition.py
The reason behind this is interesting : for the crop and the position of the cropped layer (here, the one being appeared), the value for the beginning and the value for the end, both between 0 and 1, are interpolated relative to when we are within the transition, then that is multiplied by the with and heigth to render to. This obviously returns a float, which will very likely not have an integer value. In the case of this transition (as for many others), the float of the position and the float of the crop size add up to the total size (width or height).
These floats (those of the crop and those of the pos) are then clamped *down* to integers, using `int`. And that's where the bug happens. Say we have a width of 1920, and the x pos is 10.6, the x crop is then 1909.4, since they add up to …
> Fix CropMove transitions

- renpy/common/_audio.js
It often happens in Renpy that a same audio file is queued twice in a same audio channel, in particular to implement the audio loop feature. In this case, the current audio code decodes the audio file each time it is queued, while the audio data is already available from the currently playing audio file. This means Renpy uses more memory and CPU than it needs, especially when the audio file is big.
This PR checks if the currently playing audio file and the next one are the same, and if so, it re-use the decoded audio data from the currently playing one. It only does that between audio files of a same channel, but it might be possible to check between the files of the different channels (but I doubt it will make a difference).
For the records, I experienced OOM crashes with a Renpy Web …
> Re-use audio data to reduce memory and CPU usage (Web)

- sphinx/source/self_voicing.rst
I tried to find an example where we would want to include in the alt a) something non textually visible (the color) and b) something already visible but which would need to be phrased differently to be properly spoken.
Improvement in the second part of the example, to make more clear what it tries to show, is welcome.
The end of the file is a bit weird : the `sv` variable is mentioned but there's no information about what it does or how it should be used.
> Improve Self-voicing documentation

- renpy/common/00definitions.rpy
The values of alpha and zoom properties are int In default & reset transform.
But these type should be float in the document.
https://www.renpy.org/doc/html/atl.html#transform-property-alpha
> mofify alpha, zoom type in default and reset transform

- sphinx/source/atl.rst
Even though the `@renpy.atl_warper` decorator allows users to define their own warpers, this syntax can be useful when for example using curryfied versions of generalized warping functions, such as `lambda x, p : x**p`.
> doc: better document user-defined warpers

- renpy/exports.py
This simply allow to use --warp command in console.
This would not be useful on its own, but it would be useful if this is able to be called by the editor in some way.
That allows Ren'Py to jump to the current editor line like engines that are integrated with the development environment like Light.vn or other.
> add renpy.warp_to_line func

- renpy/display/behavior.py
- renpy/display/core.py
Renpy games were being allowed to advance in the following two scenarios even when a modal screen was being shown: when using auto-forward, and when using the renpy.pause function. With these changes a modal screen will properly block progression in those scenarios.
> Fix modal behavior

- renpy/text/extras.py
The text may contain displayable tokens.
This will cause an error when converting to string.
> Fix: `filter_text_tags` for `tts`.

- renpy/display/behavior.py
Mouseareas are supposed to not hover if the keyboard is being used for focusing, but this was broken by an if/else statement that changed the is_hovered value again without regard to if it had already been set to false because of keyboard focusing. Changing it to elif/else ensures the value of is_hovered is only changed if it hasn't already been set to false because of keyboard focusing.
> Fixed mouse area hovering

- renpy/display/layout.py
At the time of import `renpy.import_all` the `pygame` module may not be present.
> fix: Unavailable `pygame` in `renpy.display.layout`

- sphinx/game/script.rpy
Using replace is probably simpler than using split then join.
Also, the markup using a leading whitespace is the quote markup in sphinx, which is a bit ugly. A bullet list renders better, I think.
> Improve the generation and inclusion of the console commands list

- renpy/exports.py
def scry():
"""
:doc: other
Returns the scry object for the current statement.
The scry object tells Ren'Py about things that must be true in the
future of the current statement. Right now, the scry object has followed
field:
``nvl_clear``
Is true if an ``nvl clear`` statement will execute before the
next interaction.
``say``
Is true if an ``say`` statement will execute before the
next interaction.
``menu_with_caption``
Is true if an ``menu-with-caption`` statement will execute
before the next interaction.
``who``
Is the next character object if an ``say`` or ``menu-with-caption``
statement will execute before the next interaction.
"""
> add doc about scry

- renpy/display/dragdrop.py
This commit expands the functionality of the `drag_offscreen` property of Drags to allow for more diverse use cases. Notably, it allows you to constrain the offscreen dragging to one direction (horizontally or vertically), to provide a border around the screen which the drag cannot go past, to provide a (width, height) tuple of the displayable that should always remain within the screen bounds, or to provide a callable which can return a position for the drag.
Feel free to let me know if there's anything I can improve upon for the feature and/or the documentation.
> Expand functionality of drag_offscreen

- renpy/common/_developer/developer.rpym
In py3 it resulted in a bunch of `b'somepath'` being written to the file and in the console, now it's good, back to `somepath`.
I also changed things internally to simplify it.
> Fix and simplify the "List filenames" dev action

- renpy/display/im.py
Three reasons :
1) the im.Data displayable also returns a filename as _repr_info, but doesn't shorten it,
2) if printed in the console, the console repr shortener is clever enough to trigger by itself (although it limit is lengthier), and
3) with the artificially shortened repr there's no way to access the original filename from the console only, typing `long` won't help, you have to know about the private `.filename` attribute. That's not handy when debugging.
> Don't shorten Image's repr

- renpy/display/matrix.pyx
Uses the standard equality and inequality methods (ne was added for py2 support).
Got rid of the mistaken `Matrix other` in the signature which was enforced.
Added type comparison inside.
> Use eq and ne for Matrix comparisons

- renpy/lint.py
I didn't phrase it like "the init *statement's* priority" because it also applies to statements like `define 1000 bluh = "oh"`, which aren't understood by your common creator as init statements.
> Lint out-of-range init priorities

- launcher/game/distribute.rpy
- launcher/game/web.rpy
When packaging a Web build, all the files are put in a game.zip file first before being selectively removed based on whether they should be downloaded progressively or not. This is a waste of time and disk space (the ZIP file content is duplicated), especially for novels with lots of images.
This PR adds a generic file filtering feature to the Distributor class so that builder scripts can filter out the files to package based on their specific needs. The Web builder script uses that to prevent the files to be downloaded progressively from being put in the ZIP archive at all, and copy them to the destination folder on the fly. The original progressive download filtering logic is preserved, but it happens sooner.
With these changes, empty folders are put in the ZIP archive though, but it …
> Optimizations for building Web packages

- renpy/python.py
This marks any and all names used as a parameter in a lambda within the comprehension expression, as not being a variable coming from outside the comprehension expression.
> Fix the ast magic applied on comprehensions when containing lambdas

- renpy/display/image.py
This includes an off-site link to a python official tutorial, as well as a lignt fix - as far as I understand it, the function doesn't return tags.
> Expand get_ordered_image_attributes doc

- renpy/lint.py
The advice to setting it to False is a bit outdated, but if the creator sees the message it means config.developer was True, which itself is a bit outdated.
> Advise setting config.developer to "auto" in lint

- renpy/text/text.py
- sphinx/source/text.rst
Sometimes, your tag doesn't know what size it will be, but `+`/`-` is not enough, and turned out that in some circumstances I actually need a multiplier, rather than an addition, never mind that it's an int in the end.
Could this be added?
```
"{size=*2}This is double size{/size} and this is {size=*0.5}half size{/size}"
```
> Allow multipliers in {size=<value>}

- renpy/lint.py
Applies config.adjust_attributes to say attributes when linting, so lint won't report errors for say statements which work in-game.
> Improve lint for say attributes

- renpy/exports.py
Before AST nodes would run in the order they were in the script. Now we're sorting them before running them.
> Fix `renpy.load_module` not respecting init order

- launcher/game/updater.rpy
Not meant to get documented.
When the previous update failed or is doubted of, its possible to set the `allow_repair_updates` variable to true in the console, which enables upgrading to the same version we're (supposed to be) in.
We could add this for the general public as a smol "(repair)" button alongside the disabled button of the current version.
> Allows the launcher to perform repair updates

- renpy/display/viewport.py
Forget the initial drag position if the visible dragging was not started and the player unpressed LMB.
Fixes https://github.com/renpy/renpy/issues/3940
> Fix sticky draggable viewport

- sphinx/source/displaying_images.rst
- sphinx/source/layeredimage.rst
The "If an attribute is not inside a group..." is removed because as far as I could test, it's not true. Attributes outside of groups have a .group attribute of None, not one equal to the attribute name.
I also think the explanation about the filename-finding procedure is a double with the one in the Group section, so they should probably be merged, probably by making this one just a link to the Group one. If this is wanted, I'll add it to this PR.
> More layeredimage documentation

- renpy/display/behavior.py
- renpy/exports.py
- renpy/game.py
- sphinx/source/keymap.rst
- sphinx/source/label.rst
- sphinx/source/other.rst
Aside from reassigning specific functions to specific include places, this creates a Contexts section in the "Labels and control flow" page, which receives 1) the functions which were listed in the now removed Contexts section of the "Others" page 2) a function from the general Others list 3) three functions previously listed in the label-related functions.
Some explanations about what a context actually is is outside of the scope of this PR, but would be a good addition to that section.
> Move some functions from the "Others" page to more specific places in the doc

- renpy/common/00console.rpy
This is proof-of-concept of #3783. Right now to make it work you need to copy Python's `sysconfig` into `lib/python3.9`.
> Add help <expr> into console commands.

- renpy/common/00layeredimage.rpy
- renpy/display/behavior.py
- renpy/easy.py
- renpy/exports.py
replaces #3944 
I chose to test for str and not basestring, so that the behavior is exactly the same on py2 and py3, but that's arguable (now it only applies to unicode, to be clear).
The default value of `copy` is also arguable.
Another or_none parameter could be added, to avoid returning [None] in some cases.
> Use easy.to_list and easy.to_tuple

- sphinx/source/label.rst
- sphinx/source/lifecycle.rst
- sphinx/source/python.rst
- sphinx/source/screens.rst
- sphinx/source/splashscreen_presplash.rst
A section where to include functions and classes would be cool, including at least `renpy.is_init_phase`.
I think we could add more flesh to it, but this could also be merged as it is.
> Lifecycle doc page

- renpy/common/00console.rpy
The help <expr> changes done by #3890 was giving errors when used with the normal commands e.g. help save. That seemed unintuitive so I added an extra code snippet which returns the command's help text rather than an error.
> Added help <expr> for existing commands

- renpy/script.py
This fixes behavior of renpy.load_module if it exists both in game and tl directory.
For example, if there are `game/module.rpym` and `game/tl/russian/module.rpym` loading the game the second time with russian language selected `init python: renpy.load_module("module")` will try to load `game/tl/russian/module.rpymc`.
> Fix wrong .rpymc loading.

- sphinx/source/drag_drop.rst
the `say` screen was missing the `who` and `what` parameters
> fix drag drop screen example

- README.rst
The correct triplets for various arches are:
- `x86_64-linux-gnu`
- `arm-linux-gnueabihf`
- `powerpc64-linux-gnu`
- `powerpc64le-linux-gnu`
The `uname`-based instructions produced the following:
- `x86_64-linux-gnu` (correct)
- `armv7l-linux-gnu` (wrong)
- `ppc64-linux-gnu` (wrong)
- `ppc64le-linux-gnu` (wrong)
`gcc` produces the correct results for all four.  I suspect this will also fix non-GNU triplets such as musl, but didn't test those.
> Fix RENPY_DEPS_INSTALL docs for armhf, ppc64, and ppc64le

- sphinx/source/android.rst
- sphinx/source/splashscreen_presplash.rst
The Ios one is missing, but I don't have much infos about it.
> Document platform-specific presplash images

- renpy/__init__.py
- renpy/display/core.py
- renpy/main.py
- renpy/persistent.py
This poolrequest includes a workaround of the error when trying to save, and some changes and additions inside `renpy.persistent`, namely they deal with the interaction with objects of the `_MultiPersistent` class.
> fix & changes: bypassing exception on `MP.save`, some functions, docs for `MP`

- renpy/common/00steam.rpy
Without these changes imposed by Python3.9, calling get_session_ticket() raises two exceptions.
Testing Done: Yes
First Exception: ticket is not defined
Second Exception: Cannot slice non-integer
Steps to reproduce: Call get_session_ticket().
> Fix bugs on steam.get_session_ticket

- renpy/exports.py
> Pylint - Avoid shadowing the function parameter

- renpy/display/core.py
- renpy/display/layout.py
- renpy/exports.py
- renpy/loader.py
- renpy/main.py
- renpy/text/font.py
From #3994
Generates simpler executable code, I think (it's recommended anyway)
> Pylint - Use literals instead of builtin types constructors

- renpy/ast.py
From #3994
Wastes memory and may break in a future version of python, see point 6 of this : https://docs.python.org/3/reference/datamodel.html#notes-on-using-slots
> Pylint - Remove overriden slot name

- renpy/translation/__init__.py
The alternate variable wasn't used where it should.
Instead there are two indentical `self.language_translates.get((identifier, language), None)` lines.
> Fix: alternate translation

- renpy/common/00gltest.rpy
something i noticed is that this bit of code:
```
image black = Solid("#000")
image white = Solid("#fff")
define config.gl_test_image = "white"
define config.tag_zorder["black"] = 5
```
will cause the gl_test_image to not show up due to its zorder being lower than black's.
this is annoying when a `splashscreen` that uses a white solid is used:
```
label splashscreen:
show white
pause 1.0
return
```
the game will "flicker" from black to white, when only white is supposed to be showing
> use `zorder 0` for the gl test

- renpy/main.py
I know ren'py extensions are considered unused, but I have a few use-cases for Ren'Py augmentations/core changes/non-intrusive features and not being able to re-use code without copy-pasting because I can't rely on the extensions' load order is a pain. Could this be merged to make them more reliable ?
> Make extension load order reliable

- renpy/main.py
`sys.path` grows without limit at each reload, which quickly makes it unwieldy when working on a game with several extensions.
Also sets the __file__ global to make loading extension files that are not python modules more idiomatic (at the moment, the only way is to use sys.path[0], which relies on the way ren'py internally handles extension-loading to work, being able to do `os.path.dirname(__file__)` from a packaged extension seems more clear).
> Add path cleanup when reloading extensions and extension __file__ context

- renpy/python.py
`from module import *`
In python 2, when `b"__name__"` is found in the module's inner dict, it is not imported. _**However**_, if `u"__name__"` is found, it _is_ imported and replaces the local `__name__`.
Given the `from __future__ import unicode_literals`, `d["__name__"] = pyname` stored the name in the unicode key on both py2 and py3, whereas the key needed to be `pystr("__name__")` - unicode in py3, bytes in py2, just like the pyname variable itself.
Using the update method does the same thing as using pystr on the keys : it interprets the keys as unicode in py3 and as bytes in py2.
> Fix star-import of substores

- renpy/webloader.py
When checking for outdated media in the to_unlink variable, if you click through images fast enough, sometimes it throws an error `RuntimeError: dictionary changed size during iteration` because of new items being pushed to the dictionary. Iterating through the copy of to_unlink prevents this error.
> fix to_unlink changes size during iteration error

- launcher/game/distribute_gui.rpy
I thought it would be a good idea to differentiate the type of package being built from the rest. This adds (DLC) if it is enabled in `build.package`
Example:
> Differentiate DLC from other types of packages (Build)

- sphinx/source/index.rst
- sphinx/source/thequestion.txt
- sphinx/source/thequestion_nvl.rst
The toctrees now take the :caption: instead of a heading, so that the caption appears in the left side list.
The last toctree was dismantled and changed to a simple bullet list so that it disappears from the left column list.
> Upgrade toctrees for the new doc theme

- renpy/exports.py
fixes #4125 more properly
There could be an argument for not dwelling too much on statement equivalents, but I think making the already available information clearer doesn't hurt.
> Add doc examples for renpy.show

- sphinx/game/doc.py
Every python class, function or method which currently gets documented from its docstring is incorrectly tagged as a function.
This reads fine-ish visually - although the class lack the `class` keyword - but there's a problem with autolinks : the A.b() method will be considered as the b function, and therefore will collide with the C.b() method.
Now, every class is declared as a class, and the functions found inside classes are declared as methods.
I explained it better in the linked issue.
> Tag the callables properly when generating sphinx from docstrings

- sphinx/source/gui.rst
This is an alternative to creating a single-use anonymous version of the `var` thing. I think this is simpler.
> Avoid re-defining two config variables

- launcher/game/web.rpy
Support of Progressive Web Application (PWA) in RenPy requires the generation of a bunch of icons for a variety of devices.
This code needs a single icon image (in png format) of 512x512 or bigger. It looks for a file called `pwa_icon.png` in the project directory. If such an icon does not exist, it will look for the default one from the web folder (ref: https://github.com/renpy/renpyweb), which is also optional because it requires an additional pull request to the renpyweb repository to add this file. Then this file is scaled down progressively to all required sizes and saves everything into the icons subfolder in the build directory, so we can use it later for actually building PWA in the `index.html` file.
To test this code, you can use this image:
> web: Generate PWA icons and prepare files

- launcher/game/tl/japanese/launcher.rpy
In the Japanese UI, the notation `Ren'PY` was used in the description text of `Create Xcode Project` in the iOS build settings section, but `Ren'Py` is believed to be the correct notation.
> fix: upper case letter

- launcher/game/web.rpy
The first step on working on [https://github.com/renpy/renpy-build/issues/53](https://github.com/renpy/renpy-build/issues/53).
This code creates a minified `pwa_catalog.json` file in the destination build that has the following structure:
```
{"files": { "<file_path>": "<hash>", ... }, "version": "your-game-<timestamp>"}
```
`files` contains all paths in the `game` folder, and will allow us to download all files at once, for offline use.
The `version` will let us track if the catalog is updated to the current version of the service worker. If not, we'll create a warning in the console, to let the dev know that it needs to be updated
> web: Generate catalog of all media content for caching in PWA

- renpy/display/layout.py
- renpy/display/viewport.py
Bit of potential optimisation after looking into https://github.com/renpy/renpy/issues/4153.
The main change is that only in the event that the grid is underfull and developer mode is active will it bother to:
- Resolve the `allow_underfull` value,
- Construct of exception instances.
This is very much a same-behaviour refactor, which I appreciate we're not always looking for, so completely understand if it's not desired. :)
> Optimize allow_underfull for non-developer mode

- renpy/lexer.py
This is the lazy version of fixing the issue. The parser calls expect_noblock() so many times (52) it's very hard to grasp how it could be segregated more precisely.
> Add colon warning in the noblock lexer error

- module/generate_styles.py
- renpy/sl2/slproperties.py
- sphinx/source/style_properties.rst
Not tested in any way.
https://github.com/renpy/renpy/blob/xycenter-style/sphinx/source/keywords.py and https://github.com/renpy/renpy/blob/xycenter-style/tutorial/game/keywords.py should probably be updated, but I'm not sure how to do that.
> Add the xycenter proxy style property

- sphinx/source/config.rst
Very rarely, I left empty lists or dicts. This is the case for things like adjust_attributes or callbacks directly meant for creators and that I felt it wouldn't make sense for us to customize in future versions.
I should check if the `:` syntax compiles as properly as `=`.
> Futureproof list and dict config variables, and better nomenclature for callable configs

- sphinx/source/config.rst
The documentation advised using the ui functions, which are now obsolete.
The only internal use calls ui.text and ui.add, which are defunct, but also renpy.show_screen and renpy.hide_screen.
So, if they have actual current use cases, we could also leave them documented but phrase the explanation differently.
> Undocument config.overlay_functions

- renpy/persistent.py
- sphinx/source/language_basics.rst
- sphinx/source/persistent.rst
- The new _hasattr method, and its documentation
- document the __-starting names : warn about them not being affected by _clear, and general limitations over these names in renpy
> Persistent improvements and fixes

- renpy/common/000statements.rpy
- renpy/display/screen.py
Attempt to implement #3577
Allows to do:
```renpy
show screen screen_name as screen_tag
show screen some_overlay onlayer overlay zorder 15
```
and similar.
> New screen clauses

- renpy/parser.py
```rpy
label scn:
scene sand6
"scene sand6"
scene wet onlayer screens
"scene wet onlayer screens"
scene
"scene"
scene onlayer screens
"scene onlayer screens"
jump scn
```
The commented-out lines were previously bogus, as they didn't raise a parsing error but their first onlayer clause was silently ignored.
Now, they raise parsing errors.
Fei, the separate onlayer parsing is required for the last scene statement to function properly.
This PR offers no compat, for the same reasons as in ddc4eab5fd0001b6b9e30e49112885911fb7c3df.
But if one is requested, I have a lead on how to do it differently.
> Remove bogus onlayer parsing on scene statements

- sphinx/source/developer_tools.rst
`config.editor` was apparently never implemented, despite having been documented.
I removed the reference in the doc (missing a declaration, #3600) and described what Shift+E actually does.
I did _**not**_ remove `editor` from config.py, for fear of pickle-like consequences. And because a None-set variable has negligible memory impact.
> Undocument config.editor and document Shift+E

- sphinx/source/config.rst
Per #3600
It was added in "rarely used", because I believe most people use config.developer instead and there's not much use for enabling _only_ the console.
> Add a formal doc entry for config.console

- sphinx/source/config.rst
- sphinx/source/translation.rst
`default_language` is a default
`language` is an override, only topped by an environ variable
`config.language` was documented using language actually describing `config.default_language`, except at the rundown of the language choice in translation.rst which is actually correct. `config.default_language` was referred to there, but missing an entry (per #3600).
Both are now fixed.
> Unmixup config.language and config.default_language

- sphinx/source/android.rst
This concerns the request_permission and check_permission functions, at the bottom of exports.py.
The JSONDB class in 00db_ren.py also has a docstring intending for it to be documented, but never included in the doc. Although in _that_ case, a bigger bunch of documentation remains to be done.
> Include functions intended to be documented

- launcher/game/package_formats.rpy
This is the last use of the six module across the repo - other than `__init__.py` importing it. Maybe we can remove it from the requirements ?
> Use the regular way of testing py's version

- sphinx/source/config.rst
- sphinx/source/file_python.rst
- sphinx/source/save_load_rollback.rst
- sphinx/source/screens.rst
`config.skipping` is undocumented, per #3773 and #1158.
`config.gamedir` is undocumented, and I suggest it stays so for the same reasons as config.skipping : it's not intended to be writeable.
Two examples were using those, now they don't.
Per #3600
> Avoid undocumented config variables in examples

- renpy/exports.py
- sphinx/source/config.rst
There are undocumented keyword arguments (they are at least 7 years old) which would already break existing uses of config.show with a function which would only take the documented arguments. This warns about them, and tell creators to pass them unchanged.
Also, the layer argument is worded as "if not None..." while the displayed default value is "master". I find that putting None in the signature is more clear, because the explanation is clear enough.
> Improve and secure the documented signature of renpy.show

- sphinx/source/language_basics.rst
That, and moves it, it was under Keyword but belongs under Name.
> Document name-munging more visually and add warning for f-strings incompatibility

- sphinx/game/doc.py
Due to #4143 
This reserves all `:doc: *action` as classifying actions, and categorizes those as functions regardless of their true nature.
Overrides like `:doc: somethingaction class` still take precedence over this added behavior.
This works well. Existing `:class:` references still work and link them properly just as before.
This does not cover Bar and Input Values however, which are still classified as classes. And some actions like Replay, EndReplay, gui.SetPreference, gui.TogglePreference and StylePreference are not covered, because their include name does not end with "action".
So either we don't care about them and leave them as classes, or we override them specifically with `:doc: something function`, or we rename their include name to end with "action", or we don't care at all …
> Classify actions as functions

- sphinx/source/3dstage.rst
Currently, the documentation does not specify how to enable 3D stage for specific layers (only mentioning the possibility).
This PR should address the issue.
> [docs] Elaborate on layer specification in camera statement description

- renpy/exports.py
- renpy/game.py
- renpy/main.py
- renpy/script.py
This PR closes #3960 by adding a new function `renpy.include_module`. It allows the developer to control which module will be *included* in the script during init (where `renpy.load_module` loads the module right away, "ignoring" the init order).
This also moves the sort I added in #3959 directly in `Script.load_module` and also adds sort to `Script.load_string`, now they are consistent with `Script.load_script`. Sorry, I missed it the first time.
Since timsort is a stable sorting algorithm (as of Python 2.3), I removed the old code with decorated sort to make it run a bit faster.
I had to add `heapq_merge` which looks ugly and scary, but it's just a port from the Python 3.10 sources that works in Python 2.7. It can be removed down the line when you decide to no longer support py2.
If any …
> Add `renpy.include_module`

- sphinx/source/translation.rst
Removes an unclear and possibly wrong advice, and replace it with the `id` thing.
> Remove wrong example and move things around

- sphinx/game/doc.py
In py3, `class A: pass` then `A.__init__.__doc__` returns the docstring of `object.__init__`, which babbles about help(type(o)).
This part of code I edited looks for the `__init__` docstring to add it to the extracted docstring of the class, but we don't want object's docstrings, we only want ours.
This works by memorizing the forbidden docstring (for efficiency). I removed a previous test which _seemed_ to do a similar test but I'm **not sure what it was about**. It was added in 3b6c9bde63333d28bd9b20caae591a35d45116a3 without much explanation, and seems outdated.
> Ban object's __init__ docstring from our documentation

- renpy/exports.py
- sphinx/source/config.rst
- sphinx/source/custom_text_tags.rst
- sphinx/source/gesture.rst
- sphinx/source/preferences.rst
- sphinx/source/side_image.rst
- sphinx/source/store_variables.rst
Various tweaks, in particular to how callbacks are documented, so that creators always know what parameter they can be passed.
I'm not sure why gesture and side_image appear as entirely replaced, I suppose it's a problem of LF/CRLF and git or vscode replaced all line endings automatically ? That, or they had trailing whitespace on all lines.
If it's a problem I can try to recommit that differently.
> Variables documentation

- renpy/common/00preferences.rpy
In current nightlies activating self-voicing mode doesn't display the screen saying it's active - regression introduced by 9366678fef7e83f4d59ec1aff1c0000965d1e52d.
> Restore self-voicing notification callback

- renpy/common/00webvideo.rpy
Usually if a game starts with a video, the video is just a series of logos without sound. So why not auto mute the video if no user click instead of show a prompt to request user click? This can provide a better experience.
This change have no impact on in-game videos since in-game videos must be played after at least one click interaction so won't be muted. Only splash videos may be muted for autoplay. If user clicked video in muted status, the sound will be enabled again.
(I have already applied this change to my site and works well, u can test this feature at https://zhijiang.qinlili.bid/play ,which is a game starts with a splash video)
> web: auto mute video for autoplay

- renpy/display/movetransition.py
By the way, the `entering` function does nothing with its `sle` parameter and wraps the `new_sle` displayable directly. Shouldn't it work the same way as `leaving`, and wrap its parameter ?
> Apply transforms to displayables the proper way

- renpy/config.py
- renpy/defaultstore.py
- renpy/display/core.py
- renpy/display/layout.py
- sphinx/source/changelog.rst
- sphinx/source/config.rst
- sphinx/source/displayables.rst
The second half of https://github.com/renpy/renpy/issues/4149.
This is intended as a feature for more advanced creators and comes with minimal hand holding. Docs to follow Tom's approval.
**Key points**
- The `Layer` displayable has been added to represent one layer inside another.
- `config.detached_layers` has been added to allow declaration of layers that will not be automatically added to a scene, but rather used via the `Layer` displayable on an as-needed basis.
- `layers` and `sticky_layers` have been created to help manage layer configuration and optimize some of their operations.
---
This feature underwent significant changes during development, with a substantial portion of the original code backed out. The original PR body can be viewed below to contextualise the comment thread, …
> Layer displayable and detached layers

- renpy/character.py
- renpy/config.py
- sphinx/source/config.rst
Attempt to implement https://github.com/renpy/renpy/issues/4018.
Added a configuration variable that allows adding the current dialogue to history screen.
> Allow adding the current dialogue to history screen

- renpy/sl2/slparser.py
I don't think this deserves a compat, because there's no use to the syntax hereby disabled. And if one is found, thiis shouldn't be merged at all.
> Disable empty keywords in screen parsing

- renpy/common/00director.rpy
- tutorial/game/01director_support.rpy
- tutorial/game/tutorial_director.rpym
The tutorial needs to disable the interactive director in a variable manner.
This replaces a variable meant to change over time but placed in a constant store (which lead to bugs), with a query made on a variable in the general store.
I think this is cleaner than #4307.
> Better director toggle variable

- renpy/display/image.py
The recent change adding negated attributes to the director made one line (which i didn't change) look like this `return tuple(i + negative)`.
The issue is that while `negative` was always built as a list, `i` (meaning the elements of `l`) is sometimes a tuple, and sometimes a list - _choose_attributes makes it a list, otherwise it's a tuple. So, adding a tuple and a list ends up in an exception every other time.
The fix here is to make every relevant thing be a tuple.
An `attrs = tuple(attrs)` could be added for more safety but it seems pretty consistent in being always a tuple.
This caused an exception when trying to add a scene statement in the tutorial at the moment when it asks you to.
> Fix recent director regression

- renpy/display/core.py
- renpy/display/layout.py
- renpy/display/movetransition.py
Proposed fix for #4264. I don't pretend to have worked with `MoveTransition` enough to know if this is truly the right approach, it seems sane, but given how often issues in this area have come up before - #2560, #2821, #2995 - it should probably be vetted comprehensively.
---
This alters how the Move transition deals with layers that have been wrapped in a transform by the "show layer" statement.
Previously raw layers were hung on the layers_root widget, so that the Move transition could unwrap them when needed. Unfortunately this meant that it was only possible to do this unwrapping if it was the layers_root widget being transitioned, rather than individual layers.
The change is to instead hang the raw layer on its transformation directly, allowing it to be accessed both in the case of …
> move: Transformed-layer specific Move transition

- renpy/display/im.py
Each committed change was tested on my end.
Among the subclasses of im.ImageBase :
- im.Data, and im.ZipFileImage aren't subject to oversampling, as they aren't "im transforms" - taking an im and returning another
- Composite takes several im parameters, so computing the oversampling of the whole is not trivial. I chose only to support all the images having the same oversampling factor - which is better than nothing, for obsolete functions
- Alphamask already had the constrant of the two images having the same size, they now also must have the same oversampling - seems fair enough to me. If you try it, it will most likely glitch, but that's only if and because #4083 is not merged
- All others have been converted.
> Oversampling for image manipulators

- renpy/sl2/slast.py
- renpy/sl2/slparser.py
SLBreak and SLContinue, apart from their respective execute methods, were shamelessly copied from SLPass. Same with BreakParser and ContinueParser wrt PassParser.
Test code :
```rpy
define colorlist = ["#f00", "#0f0", "#8400ff", "#00f"]
screen break:
hbox:
for color in colorlist:
if len(color) > 5:
pass
add Solid(color, xysize=(100, 100))
```
- Using pass should yield red, green, purple, blue
- Using continue should yield red, green, blue
- Using break should yield red, green
> Add break and continue to the screen language for loop

- renpy/exports.py
Replaces calls to undocumented method Render.is_pixel_opaque.
renpy.render is preferred to Displayable.render because of its caching effects, saving potentially lots of computation time.
> Add renpy.is_pixel_opaque

- renpy/sl2/slast.py
This pull request fixed https://github.com/renpy/renpy/issues/4331.
As there was a missed point in the iteration in this change (https://github.com/renpy/renpy/commit/03d37d24dc912e091490c27d02af75449336ddf6)
> fix: missed iteration arg in `SLIf.keywords`

- renpy/text/text.py
This relaxes the restriction on using slow text in screens while self-voicing is enabled. As say dialogue is handled by Character it is unaffected by this change.
The use-case for slow text while TTS is active is that it can be in some cases an effective visual story-telling aid for first person PoV typing and writing, and so on. Many TTS users still have partial sight, and so are able to appreciate this visual effect despite not being able to read the text for themselves directly.
> Allow slow text to be used in screens while TTS is active

- renpy/display/transition.py
Even though time_warp is mentioned three times in the [transition classes document](https://www.renpy.org/doc/html/transitions.html#transition-classes), it's never shown how to actually use it. Since the idea of using the _warper module is not intuitive, and it's mentioned only once at the beginning of the section, I thought it would be best to at least include it in one of the examples.
> Include an example of a proper usage of time_warp in the docs of ImageDissolve

- sphinx/game/doc.py
- sphinx/game/script.rpy
The only thing changed in doc.py (in fine) is the use of the `inspect` module, using the new methods instead of obsolete ones.
The only thing changed in script.rpy (apart from that linebreak thing) is the `object.__init__ = lambda self:None` line, which applies to the revertable object since it's in a rpy file. That is to fix #4317.
> Modernize the `inspect` module and fix subclasses of RevObject not overriding __init__

- gui/game/screens.rpy
- launcher/game/interface.rpy
- launcher/game/navigation.rpy
- launcher/game/preferences.rpy
- launcher/game/style.rpy
- renpy/common/00console.rpy
- renpy/common/00director.rpy
- renpy/common/00gui.rpy
- renpy/common/00layeredimage.rpy
- renpy/common/00nvl_mode.rpy
- renpy/common/00placeholder.rpy
- renpy/common/00style.rpy
- renpy/common/00sync.rpy
- renpy/common/00themes.rpy
- renpy/common/00touchkeyboard.rpy
- renpy/common/_compat/styles.rpym
- renpy/common/_compat/themes.rpym
- renpy/common/_errorhandling.rpym
- renpy/sl2/slproperties.py
- sphinx/source/oshs/game/screens.rpy
- sphinx/source/screen_special.rst
- sphinx/source/screens.rst
- sphinx/source/style_properties.rst
- testcases/game/screens.rpy
- testcases/game/script.rpy
- the_question/game/screens.rpy
- tutorial/game/01example.rpy
- tutorial/game/indepth_style.rpy
- tutorial/game/screens.rpy
- tutorial/game/tutorial_screens.rpy
The use of `textalign` in style blocks, and as assignments to field-like properties of a Style object, already works.
The different commits do incremental changes.
- be95fa74127261f37b8b0e398e4a3f52049fd21d enables the use of textalign in screen language
- ad2e80f90029783a61f68ecb54e3194ee47220cc updates the documentation
- 6c89fcb29d28a7b48d01679a27aa3d6d4083c771 seeks to address gui.text_properties, first by correcting the reference to the style property changed in the preceding commit, and then by doubling the key of the returned dict (the old key is kept for compatibilty, and the new one is the one documented now). I don't fully understand what the function does so this should be checked.
- a0dba5ca1d81a6493fdf90ffc44f2fba08f11162 updates examples in the doc and in the tutorial game, …
> Textalign renaming

- renpy/common/00compat.rpy
- sphinx/source/changelog6.rst
I believe it was influenced by an even earlier commit:  b6d51b7b0bffb5ab1b08deeadfbea9cad273ceda
> fix: typo in common

- renpy/ast.py
- renpy/common/00start.rpy
The ast.py use is quicker now, the others are probably unchanged but prettier.
> simplify renpy.dynamic calls

- renpy/audio/audio.py
When audio files need to be downloaded and they have not been yet, the current behavior for Web is to queue the download and play a silence audio file instead. This is the root cause for #4113 and it also prevents some audio effects/voices to be played at all if prediction failed.
These changes make queueing the audio files wait for the files to be downloaded to prevent that. I kept [the silence file playback code](https://github.com/renpy/renpy/blob/8668e3c986f4aaf0b35c7a7c404ec6138558eee5/renpy/audio/audio.py#L83) but it is probably a dead code now.
> Wait for audio files to be downloaded before queuing them (web)

- renpy/common/00action_other.rpy
- renpy/display/focus.py
fixes #4381
It's a bit weird to have that and None not being the default value, though.
> Enable ClearFocus and renpy.clear_capture_focus to clear all focuses at once

- renpy/display/transition.py
Tweaks a0c5ef35e199309d254537e4d98664e0728b3805 (everyone's a critic) so that transitions aren't implied to take (any) style properties by parameter. This is documented in the case of displayables, but for Transitions it's not, as far as I know. Short of a comprehensive explanation of what properties are accepted and what they do in the context of a transition, I don't think we should be documenting it that way.
> Document mipmap specifically in transition parameters

- renpy/persistent.py
Removing ineffective code - variables being set for no effect, and an if that could be turned into an elif and save some time.
The first part is a rewrite of b2ba026. I think it was a copypaste of the lines not far above, and it can be simplified safely, but if the continue should be a break for example then it should be fixed.
> Simplify and quicken code in persistent.py

- renpy/display/behavior.py
- renpy/display/viewport.py
This fixes inertial viewport dragging. Namely, it adds an `instantly` parameter to the Adjustment `end_animation` method such that the relevant Adjustment parameters can be reset for the animation to instantly stop where it is. This is used 1) when the user touches down again, so the viewport stops when they press down, and 2) when the drag hits one of the viewport limits (so it can't be dragged any further). You may also consider using it in other circumstances, such as stopping the animation when the viewport scrollbar is grabbed.
> Fix inertial viewport dragging

- renpy/__init__.py
Starting with 67.2.0 setuptools enforces PEP440 compliance.
> renpy: Make version PEP440-compatible

- renpy/common/00layeredimage.rpy
- sphinx/source/layeredimage.rst
- sphinx/source/statement_equivalents.rst
Several main goals:
- Remove the first part of the page, which was presenting a big example which we don't yet know how to make sense of, and then taking it back to replace it with another, very confusing in my opinion
- Clarifying use of the word "attribute", to discern between the thing you pass after an image tag in a show statement, and the parts of a layeredimage
- Clarify what is one group and what is one attribute (when defining "several" with the same name they are actually one and the same)
- Almost never use the term "layer" as the superset of attribute, if and always - confusing with renpy's layers system, not clear as to what it means, not supported by syntax other than in the word "layeredimage", and conflicts with understanding the previous point
- Use the word "sprite" to …
> Rewrite the layeredimage page

- renpy/webloader.py
`voice_count` only increases when `rtype` is 'voice', so behavior should be the same, without having to iterate over the queue again for each queued voice files.
> Remove useless double iteration

- renpy/common/00matrixcolor.rpy
Per the documentation, the alpha shouldn't ever have been impacted.
This change instead treats the alpha in the supplied RGBA value as the tint opacity rather than applying the tint formula to the alpha channel. The result is the ability to use a colour value of `#FF000080` to apply a 50%-red tint to the target.
<details><summary>Control, before, and after screenshots.</summary>
</details>
<details><summary>Reproduction code.</summary>
```rpy
label main_menu:
$ _confirm_quit = False
return
image s = Solid('777', xysize=(320, 240))
label start:
scene
show s at Transform(align=(.5, .5))
'Original'
show s:
matrixcolor TintMatrix('ff000080')
'Test'
```
</details>
I did consider compat for this, but given the current behaviour directly conflicts with the documentation, and also doesn't align …
> Fix TintMatrix to respect alpha

- renpy/loadsave.py
- Adds handling for the case where the output of `__reduce_ex__` is a string representing a singleton.
- Makes sure "BAD REDUCTION" warnings make it into output.
- Grabs the protocol to use from `renpy.pickle.compat.PROTOCOL`.
- Adds support for functions, which can be pickled but don't support the `__reduce__`/`__reduce_ex__` APIs.
Recommend [viewing changes without whitespace](https://github.com/renpy/renpy/pull/4444/files?w=1) as a chunk of code had to be indented but was otherwise untouched. Each commit corresponds to an entry in the list above.
> Improve savedump

- renpy/common/00layeredimage.rpy
I added `:doc: li` in Always as part of the global rewrite, but it didn't work because Always is not exported to the general store at the bottom of the file (unlike the others, Attribute, Condition, ConditionGroup and Layeredimage).
Since a displayable passed to LayeredImage gets converted to an Always in `Layeredimage.add()`, i think it's not necessary to add Always to the general store (where it may shadow things), and I included general displayables as being taken by Layeredimage too.
The additional properties taken by the always statement are not being given an equivalent (if_any, if_all and such) are not being given an equivalent, but people can always use Condition and the "True" condition.
> Python equivalent of layeredimage's Always layer

- README.rst
sphinx_rtd_theme and sphinx_rtd_dark_mode were required to build sphinx.
> add README sphinx_rtd_theme sphinx_rtd_dark_mode

- renpy/display/behavior.py
Either choosing to cancel the long press detection when focus is lost was a bad decision, or something is broken in the focus logic for touch devices. Checking for a mouse up event to cancel the long press detection as this PR does is a more obvious way to do it.
I've kept the detection logic based on focus just in case it makes sense for other platforms.
Fix #4482.
> Cancel long press wait when user stops touching the screen

- renpy/gl2/gl2shadercache.py
Just like in any code, C-style (or GLSL-style) single-line comments, starting with //, are allowed.
This applies to the `variables` parameter of renpy.register_shader.
> Allow comments in shader variables lists

- renpy/display/transform.py
In ef6173de4f93d3b45c2ea2d393f3d3f9a16f9e7c we added the facility for alt text to be passed through `Transform` to allow its use in SL2. A side effect of this was to always pass alt text, meaning that the underlying `Displayable`'s `properties` could never be empty (they'd contain `alt=None`). This has been preventing `Transform` benefiting from the optimised code path in `Displayable` that avoids creating a new anonymous style.
In order to address this, we now filter out arguments passed to `Transform` that ought to be propagated up to the parent class, sending them only when defined, thus re-enabling the optimisation for the vast majority of `Transform` instances.
> Let Transforms benefit from style optimisation

- renpy/common/00compat.rpy
Fixes `Exception: config.timer_blocks_pause is not a known configuration variable.`
7d4610d13d6dc27440e9b5e235ab9992c55cb28d introduces `modal_blocks_timer` which is probably what was meant to be used here.
> Fix compat using unknown config option.

- renpy/common/00action_other.rpy
The existing behavior is weird, because if the lockedness is auto-computed and determined to be false, the behavior will not be the same as if the value `False` was passed.
If the existing behavior is deemed good, `git merge 5c400fdbc9481ca325355105a21a7ad2856628eb` will make the doc entry accurate as to what it does.
> Replay action's lockedness

- renpy/exports.py
The returned dicts are mutable, but otherwise compare equal with equal inputs.
I'm using that in a dollar-line in a screen, seems like an optimization could be done there.
> Mark renpy.split_properties as pure

- renpy/audio/audio.py
Using `exception.relpath` instead of `fn` makes sure the search prefixes are applied to the final path (when `config.search_prefixes` is used for instance).
> Apply path prefixes when loading movies for web

- sphinx/source/changelog.rst
This fixes the changelog example for _ren.py code sections.
>A Ren'Py section is introduced with """renpy on a line by itself, and is terminated with """ on a line by itself.
> Fix _ren.py format changelog example

- renpy/common/00sync.rpy
`download_content()` only takes 1 argument, I guess the `hashed` argument is from obsolete code.
> Fix sync download for web

- launcher/game/tl/portuguese/ios.rpy
- launcher/game/tl/portuguese/preferences.rpy
ios - Fixed a broken string which was in Spanish and changed a duplicate string.
preferences - Fixed a typo which said "Open launcher" instead of "Open launcher project".
> Update Portuguese Translations

- renpy/revertable.py
Follow-up to #4598 using PEP 584's recommendations and [datamodel](https://docs.python.org/3/reference/datamodel.html#emulating-numeric-types) support.
> Update revertable types according to Python's datamodel

- sphinx/source/atl.rst
This seems it should have gone away when references to `config.gl2` did - or even sooner.
> Remove warning about software rendererers

- renpy/common/00layeredimage.rpy
Linking the Displayable CDD class was't a great idea. The exposed `renpy.Displayable` is a revertable _subclass_ of the actual displayable class, so `isinstance(some real image, renpy.Displayable)` would only return True in the case of CDDs.
Also, `add` (and the constructor) take anything that can be converted into a displayable, so the latter is more accurate.
> Document LayeredImage.add

- renpy/common/00sync.rpy
PY3 zipfile accepts bytes and unicode, and encodes unicode using utf-8 (as the doc says), but py2 zipfile only accepts bytes.
On PY2, bytes still have the .encode method, so whatever the type of save_directory, my `if` shouldn't fail.
> Encode the save directory as bytes on py2

- sphinx/source/atl.rst
Corrects the indentation so that the code is valid.
One of the affected lines had a typo ('thje' instead of 'the'), which is now corrected.
> Fix interpolation example block

- launcher/game/tl/schinese/options.rpy
fix
```
I'm sorry, but errors were detected in your script. Please correct the
errors listed below, and try again.
File "launcher/game/tl/schinese/options.rpy", line 193: previous string is missing a translation
old "## A Google Play license key is required to perform in-app purchases. It can be found in the Google Play developer console, under \"Monetize\" > \"Monetization Setup\" > \"Licensing\"."
^
```
Remove `old "## A Google Play license key is required to perform in-app purchases. It can be found on the \"Services & APIs\" page of the Google Play developer console."` because it is an obsolete string.
> fix: fix launcher\game\tl\schinese\options.rpy

- renpy/lint.py
Fixes an issue where fonts located in the fonts/ directory and referenced in .rpy files with just their filename and not the fonts/ prefix would be falsely claimed to be unloadable by the linter despite working just fine in-game. Also fixes the converse issue, where fonts located in images/ directory and referenced without the images/ prefix weren't caught by the linter despite the game crashing when actually attempting to load them.
> fix fonts linting

- renpy/display/core.py
Multiple advantages over the wrapper-class implementation : lighter in memory, don't wrap methods that don't need too, don't spend time converting their parameters, avoid a two-version pickling and unpickling mechanism (with slots), shorter code with less warning silencing.
I'm not certain how pickled instances of the wrapper-class implementation will work, but if this is merged shortly it won't be a problem - saves made on a nightly have limited support.
> Make absolute a float again

- renpy/common/00preferences.rpy
- renpy/display/core.py
- sphinx/source/changelog.rst
- sphinx/source/preferences.rst
May require a compat, though I think it's probably not worth it due to the nature of the preference here.
Mentioning Andy as he authored the preference in the first place.
Code by @the66f95 (can't co-commit it since I don't know the no-reply email).
> Extend the system cursor preference to config.mouse_displayable

- sphinx/source/changelog.rst
I can't see that this is documented anywhere else, but I'm pretty sure that the wrong file type was described and `rpy python 3` is meant to be in the source file rather than the compiled file.
Also, the sentence was incomplete, so I've described `rpy python 3` as a new "statement".
> Fix changelog entry for 'rpy python'

- renpy/display/transition.py
It's rare, but sometimes it's desirable to dissolve between two differently sized widgets - most typically when the size of one or other is not known or easily computable by the creator (dynamic input text and user-chosen displayables are good example of these).
Currently the dissolved area is the smallest possible, rather than one that will be able to encompass both old and new widgets. This change ensures enough space is rendered to be able to dissolve cleanly between the two widgets.
There's a trade off that we'll dissolve more pixels in these cases, but A) they are probably fairly rare, and B) the current visual behaviour is unlikely to be desirable in any scenario.
<details><summary>Testcase</summary>
```rpy
image r = Solid('f773', xysize=(160, 240))
image b = Solid('7ff3', …
```
> Avoid cropping widgets during a dissolve

- renpy/common/00console.rpy
- renpy/compat/__init__.py
- renpy/display/behavior.py
Fix #4718.
On a side note, there are "bad mtime" warnings from Python when importing most of the PYO files on 7.6 Web, which forces Python to recompile the files and increases the load time. I'm not sure if this is specific to 7.6 and/or Web though.
> Fix for 7.6 web

- renpy/display/movetransition.py
- sphinx/source/transitions.rst
Linkify, fix a dubious link, keep the best phrasing in the two locations, and simplify the code a bit.
> Tweak 1a62894

- sphinx/source/gui.rst
"gui.choice_text_hover_color" doesn't point to choice_button, so changing it won't do anything.
> Correct var in GUI Customization Guide

- renpy/common/00preferences.rpy
This PR makes the display preference behavior be coherent with the available display modes on Web.
This PR and renpy/renpy-build#77 should fix the issues in https://github.com/renpy/renpy/issues/4760.
> Fix fullscreen Web

- renpy/display/dragdrop.py
Encountered in rare rollback scenarios where `self.st` would correctly reflect the drag was complete, but the render `st` was zero, resulting in `self.st` and `self.target_st` being equal resulting in the divide by zero.
> Prevent rare divide by zero in drag/drop

- launcher/game/itch.rpy
- renpy/common/00build.rpy
- renpy/common/00compat.rpy
- sphinx/source/incompatible.rst
The compat works as follows :
- The games already distributed and doing list operations on it (from creators who disregarded the doc) will still work when launched from a more recent launcher, the build.itch_channels will still support list operations.
- Distributing a game after this update will need the code to be updated, otherwise it will fail, but I think that's acceptable. The required change to code is very light, the feature is very recent and it is probably not widely used.
I chose to target master because with the caveats above, it's an incompatible change (albeit a fix in purpose).
> Convert build.itch_channels to a true dict

- sphinx/source/renpydoc.py
- sphinx/source/screens.rst
(the new one is on the left)
The internal issue with this is the massive amount of duplicate screen (element/displayable) properties : "action", "unhovered", "keysym", "modal" and others which are shared between several displayables.
For comparison, style properties only have two pairs of duplicates : "mouse" and "spacing".
To mitigate that we could only linkify the first 8 properties, those applying directly to the screens and not the screen displayables, from "modal" to "roll_forward". Possibly add to those the 12 properties shared by all screen elements, from "at" to "properties".
The reason I didn't just reuse the style property directive is that they would end up in the style property index, and that some may imply they can be put in style definition blocks - and I think that doesn't …
> Add the screen property directive

- renpy/exports.py
Fixes #4807.
Despite correctly recording control exceptions in the rollback log, the `pause` statement wasn't permitting them to be used (it was clearing any roll-forward info that wasn't `True` or `False`. The fix is to allow `roll_forward` to be of type `bool` or one of the expected control exceptions (`CallException` and `JumpException`).
> Allow control exceptions as pause roll forward

- renpy/lexer.py
[Source](https://docs.python.org/3/reference/lexical_analysis.html#operators)
Yes, these two operators can't be used in PY2, but the first operator in the list, <>, can't be used at all either and it didn't cause any issue, so it doesn't appear that a conditional is needed.
> Update the list of operators in the lexer

- renpy/common/00layeredimage.rpy
It was always documented as None (I checked), which means deferring to config.predict_all (which itself is False by default), but its actual default value is False, which means not predicting even if config.predict_all says we should.
I don't think this deserves a compat, but that's arguable, maybe the safer solution would be to change the doc.
> Update layeredimage.predict_all to None

- renpy/display/core.py
My rewrite of the change propagated the error into the fix branch, when it was originally contained in master.
I tested a save-load cycle on an instance of absolute before and after this very fix, it passed without problem. But if someone added arbitrary attributes on an absolute instance, that will now fail.
> Fix absolute.slots to __slots__

- renpy/common/00action_other.rpy
- renpy/common/00splines.rpy
- renpy/display/accelerator.pyx
- renpy/display/core.py
- renpy/display/displayable.py
- renpy/display/dragdrop.py
- renpy/display/layout.py
- renpy/display/motion.py
- renpy/display/render.pyx
- renpy/display/transform.py
- renpy/gl2/live2d.py
Second part of segmenting #3214 into subtasks.
This time, adds the `absolute.compute_raw` function and the `absolute.compute` counterpart, which assembles all these similar computations in one place, which avoids the need for future #4709s in the future should we ever add position types or change their behavior (wink wink).
> Absolute compute

- renpy/common/_developer/developer.rpym
Inspired by #4865.
Adds a screen (toggled via the developer menu) which displays the current translation identifier and, on click, copies the value to the clipboard.
> Tool to view and copy translation identifiers

- renpy/display/layout.py
I don't believe the current behaviour of swallowing return values here is intentional, so hopefully this falls into the "obvious fix" category. 🤞
> Restore return values from time-adjusted widgets

- renpy/common/00musicroom.rpy
This change ensures that a MusicRoom queues up from the first track if the currently playing track is not part of the playlist. Enables the interjection of the MusicRoom into more complex scenarios (such as hotswapping MusicRooms to effect dynamic playlist changes).
> MusicRoom: have queue_if_playing consider whether the currently playing track is in the playlist

- renpy/parser.py
- renpy statement names are authorized in python blocks, in function and method signatures, so they should be authorized in the calls parsed by renpy which end up calling a python thing (more about that nuance later)
- `r"stringu"` still cannot be mistaken for a keyword in this context : `r` will be recognized as a word, but since there is no `=` afterwards it will be discarded afterwards
- python statement names are still allowed as keywords, as they currently are. It makes little sense per se, but barring them is not necessary in order to fix #4874 and I fear unnecessary incompatibilities - for example a `label a(def)` and `call a(def="abc")`.
This change is necessary for when parsing the arguments to a say statement, where the call is forwarded to a Python callable, first to the …
> Parse argument keywords as words instead of names

- renpy/lint.py
In the event that a user is using the say_menu_text_filter to clean up some of their text, lint should take this into account so it doesn't report errors that the filter fixes.
> Use the say_menu_text_filter when linting

- renpy/common/00action_control.rpy
- renpy/common/00action_menu.rpy
- renpy/common/00layeredimage.rpy
- renpy/defaultstore.py
- renpy/display/anim.py
- renpy/display/focus.py
- renpy/exports.py
- renpy/sl2/slast.py
The `(kw=val, *args)` syntax _**in calls**_ (not in signatures) is the python equivalent of a default in the middle of a label : it's misleading, and if you think it changes anything then you're wrong about how things actually works.
That syntax was only kept in python (in and after [PEP 448](https://peps.python.org/pep-0448/)) due to backwards-compatibility concerns, but the interpreter internally does the exact same tweak I'm making here (an element of [proof](https://docs.python.org/3/library/ast.html#ast.Call)), and its peculiarity leads Python core devs to push to deprecate it.
I checked, this fix works in PY2.
Sources :
https://mail.python.org/archives/list/python-dev@python.org/thread/I6AUYV6DVEMP7XVYVDWC62N6PK6FHX3H/ https://discuss.python.org/t/rationale-for-supporting-foo-kw-1-ar …
> Fix occurrences of *args following a kwarg in calls

- renpy.py
Edgecase issue:
When lunching a renpy project from a OneDrive Vault `os.path.dirname(os.path.realpath(sys.argv[0]))` returns the Name of the virtualized file system Volume, but not the actual path. 
Changed it to `os.path.dirname(os.path.abspath(__file__))`, which in my limited test seems to work.
> Edgecase with OneDrive vault

- renpy/display/accelerator.pyx
The order of the camera point_to/orientation/x,y,zrotate and x,yplacement,zpos matrix was reversed at 7c082f0fb5ed6516b776c93209e97d7cec90e283.
Currently, above rotations don't rotate around the camera when x, y, zpos aren't 0.
> revert the applyment order of poi,orientation,xyzrotate and zpos

- renpy/common/00action_other.rpy
- sphinx/source/screen_actions.rst
Documents how and when action lists are sensitive and selected.
Also changes the **documented** signature (not the actual one) of SensitiveIf and SelectedIf actions, because "expression" is a misleading name when we want people to only pass actions.
> Sensitiveness and selectedness of action lists

- renpy/audio/audio.py
- renpy/audio/music.py
Fixes #4872 by restoring the `loop_only` parameter of `enqueue()` in audio.py.
After commit `b0b096b`, calling `play` on a music track with the `if_changed` parameter would *always* add it to the queue, even if the same track was already currently playing on loop. This newly queued 'loop' would always begin at the very start of the track, **ignoring any user-defined `loop` point parameters** that were added by the user to allow the track to seamlessly loop. This caused the looping track to abruptly 'restart' the next time it would normally loop whenever a player visited a label that wanted that track to play if it wasn't already looping (for example, the 'market' example in Ren'Py's audio documentation page for `if_changed`).
This change restores the `loop_only` parameter and …
> Revert removal of `loop_only` to fix `if_changed` loop seam issue

- renpy/loadsave.py
respect the renpy.store._autosave value when calling renpy.loadsave.force_autosave() directly. could be annoying if you have a choice menu in a splashscreen for instance.
> respect "renpy.store._autosave"

- renpy/exports.py
- renpy/game.py
- sphinx/source/label.rst
Fixes #3992 using help from [this article](https://patreon.renpy.org/dev-2019-12.html#extra-what-s-a-context), which is now in the free domain.
> Document what a context is

- renpy/loader.py
When trying to call method `get_data` of class `RenpyImporter` (for example through `pkgutil.get_data`) on Windows OS there can be situations when path with mixed delimiters is passed to function.
I consider it necessary, before checking and passing the path to the loader, to bring the delimiters into a single format (with straight slashes), to avoid errors. 
For example, such a path was passed to a method in the game I was running:
`D:\Novels\MyGame\game/python-packages/my_module\some_file.txt`
After that I got an error:
```
Exception: Backslash in filename ...
```
Also the path `renpy.config.gamedir` on Windows contains backslashes. And if, before passing to `RenpyImporter.get_data` method, the path will be normalized, then deletion of `renpy.config.gamedir` will not happen.
> RenpyImporter.get_data fix

- launcher/game/new_project.rpy
Not disabled, because it still makes sense for test purposes or to update default files of an older game (that last part can be done in renpy 8 but it's not obvious that it works and having to update to 8, generate the files and downgrade after is not obvious either).
This can be reworded (I'll add translation when it's fixed), and has been made fix-compatible.
Obviously it's meant for the transition period before the end of renpy7.
> Add a warning when creating new projects in renpy 7

- renpy/common/00console.rpy
When starting a line with @, you're using a decorator so the line can't work just by itself, and it would if you let the user write a def or a class underneath.
Same when ending a line with `\` : it's expecting the python line to continue on the next text line.
A colon should start a block, even if it's followed by a comment (less likely to be an issue in practice).
> Better detect when the console should expect a new line before executing the block

- renpy/main.py
Since iOS 13, Safari uses the desktop mode by default on iPad which removes the "iPad" string from the User-Agent header. The new detection looks for an Apple product with touch enabled (there is no MacOS product with touch screens AFAIK).
Fix https://github.com/renpy/renpy/issues/5022
> New detection for iPad

- renpy/display/im.py
- sphinx/source/im.rst
7.4.0 was (apparently) the first release to include 06004f1b575984d996120370bd37d9d084af3da5 and 76e03b3c36a025f5df05d851a0cf2a12cec45766 which led image manipulators towards the path of deprecation.
> Add warnings and deprecated sections for image manipulators

- renpy/python.py
Prevents this at the highest level.
Blocking it at the define/default level would be not as good because a lot of things create stores : python blocks, define, default, and now transforms.
> Prevent creation of a "store" substore

- renpy/common/00layeredimage.rpy
Remake of #4812, related to #4810
This time I commented-out the pass satement in if/elif/else blocks, for the reasons given in comments : these blocks cannot be empty as of now, they require a displayable to be provided, so adding a pass statement is useless.
It can be considered good for consistency however.
> Re-add the pass keyword to the layeredimage language

- renpy/common/00barvalues.rpy
_not sure why this wasn't a thing before_
the sphinx doc isn't written since _i do not know what the widenekoflap `inc/value` is_
> add the `LocalVariableValue` action

- renpy/common/00barvalues.rpy
- factorize the most common BarValue subclasses, using the same recipe (but in a much simpler way) as in #4473, which considerably shortens the code and avoids code duplication
- fix the `kind` parameter of `FieldValue` and `VariableValue` - it was saved but never passed to \_get_field and \_set_field
- fix some subclasses doc entries that weren't appropriately worded, some which set variables mentioned "fields"
- implement LocalVariableValue, supersede and fix #5055, and allow it to have adequately-worded exceptions
The doc has been tested.
> Factorize and improve some Barvalue subclasses

- launcher/game/front_page.rpy
- launcher/game/preferences.rpy
- renpy/lint.py
This adds the option to toggle certain Lint checks, so as to have some useful features implemented, but not bloating the report (or the report time) by default.
I guess the choice of which check is optional and which is enabled by default is up to some debate.
It should be noted that I include no mechanism to deprecate some of these options and remove them from people's persistent - but it's relatively easy to do it in an init python.
Also, #5001 is there, but only for the None language (which seems to fulfill the provided use-case).
And #3878 is here too, disabled by default.
> Add lint toggles

- renpy/sl2/slparser.py
_i'll take what i did for a project as a use case_
i created a custom vpgrid that does some alpha operation depending on how much a displayable is showing (if 60% of its surface is showing, set its alpha to 0.6).
then i created a custom screen displayable with `renpy.register_sl_displayable`:
```rpy
renpy.register_sl_displayable("gradient_alpha_vpgrid", GradientAlphaVPGrid, "vpgrid", "many", replaces=True) \
.add_property("rows") \
.add_property("cols") \
.add_property("allow_underfull") \
.add_property("child_size") \
.add_property("mousewheel") \
.add_property("arrowkeys") \
.add_property("pagekeys") \
.add_property("draggable") \
.add_property("edgescroll") \
.add_property("xadjustment") \
.add_property("yadjustment") \
.add_property("initial") \
.add_property("yinitial") \ …
```
> `copy_properties` method for custom screen statements

- launcher/game/preferences.rpy
Fix incorrect parameter for unclosed text tags in preferences.rpy.
```
usage: renpy.py [--savedir DIRECTORY] [--trace LEVEL] [--version] [--compile] [--keep-orphan-rpyc]
[--errors-in-editor] [--safe-mode] [--json-dump FILE] [--json-dump-private]
[--json-dump-common] [-h] [--error-code] [--orphan-tl] [--builtins-parameters]
[--words-char-count] [--check-unclosed-tags]
[basedir] [command] [filename]
renpy.py: error: unrecognized arguments: --unclosed-text-tags
```
> Fix incorrect parameter for unclosed text tags

- renpy/compat/pickle.py
- renpy/persistent.py
This checks whether the type of the object being pickled into persistent is of a supported type (defined `early` enough), or the object itself if the object is a type.
This probably adds some amount of execution time at loading, and possibly at saving, but I don't know how the check could really be done more quickly than this.
For some reason I did not fully investigate, `renpy.config.developer` is not set to True when init() executes, so the creation of `safe_types` cannot be done on that condition. It would save some time in distributed games, if it could. The computation cannot be made any later, since the only call to persistent.init() happens right at the time when it's too late to define new persistable types.
If the check was done in `safe_deepcopy` as the issue suggests, the …
> Add a type check on data saved in persistent

- renpy/revertable.py
Simplification and separation from #4604. This is arguably more risky than the dict stuff which is new, so it can wait for 8.1.1 or something.
> Bring list operator dunders in accordance with the datamodel

- renpy/compat/pickle.py
- renpy/persistent.py
Follow up to #4545 to group all the associated logic in one place and reduce impact outside of developer mode.
Notes: Uses `__qualname__` but this is a py3-only code path, so it's okay to use.
> Centralise safety features for persistent data

- renpy/display/layout.py
- renpy/sl2/sldisplayables.py
This PR adds the ability for nearrect to take a more general `preferred_side`, which is one of "left", "top", "right", "bottom", instead of just `prefer_top True`. This allows tooltips and other information to appear to the left or right of the hovered area as well as the top and bottom.
It also includes a `invert_offsets` property which will invert the offsets if the preferred side is unable to be used (False by default to maintain the current behaviour).
> NearRect Updates

- renpy/ast.py
- renpy/common/000window.rpy
Use "menu-nvl" instead of "menu" for `config.window_auto_hide` when showing a nvl menu, as this kind of menus don't need to hide the dialogue window by default (contrary to adv menu).
Fix #5089.
> Differentiate between adv and nvl menus for window auto hide

- renpy/arguments.py
On macOS a file with the quarantine flag will cause an error on game start:
```
error: unrecognized arguments: -psn_0_some_number_here
```
Unfortunately the end user has no control over how the renpy engine is packaged and/or embedded. Thus let's ignore this argument.
I did not want to ressurect #1326 and opted to provide a fix instead.
> fix(arguments): ignore -psn_0 argument on macOS

- launcher/game/ios.rpy
This is relevant when running `ios_create` from the command-line: in such a case, `project.current` is not the desired project and this results in an xcode project that does not use the right project names/information
> Ensure ios_create uses the target project's information

- renpy/color.py
The complete version raises an exception when it didn't use to, when passing an invalid `color` parameter with another valid parameter (for example `Color(3, rgb=(1, 1., .3))`), which I think doesn't make sense to allow.
The first commit can be taken alone to avoid that new error and stay strictly compatible.
> Allow any iterable to build a color, not just a tuple

- renpy/exports.py
Inspired by #5076 but the feature was already there.
I also think context_dynamic deserves its **kwargs but that needs to go to master so it will wait for a separate PR.
> Document that renpy.dynamic supports variables in stores

- renpy/common/000atl.rpy
- renpy/common/000statements.rpy
- renpy/common/00achievement.rpy
- renpy/common/00build.rpy
- renpy/common/00director.rpy
- renpy/common/00gamepad.rpy
- renpy/common/00iap.rpy
- renpy/common/00layeredimage.rpy
- renpy/common/00library.rpy
- renpy/common/00steam.rpy
- renpy/common/00updater.rpy
- renpy/common/_errorhandling.rpym
No functional change, purely code organisation. Makes it more obvious when reading the file that defines a store whether that store is expected to be constant. Follows the pattern established in `00sync.rpy` and applies it where appropriate.
> Move constant definitions into individual stores

- renpy/lint.py
Old projects _should_ put that config to True, and new projects which for some reason would empty the default gui screen and start anew should even more.
In the report, I placed it above the statistics and not with the config.developer check because it's more serious than both : there are valid reasons to put a boolean expression as config.developer and not rely on the "auto" behavior, but the only reason we didn't set that config to True by default is because it would trigger on vanilla projects generated from the beginning of renpy 7 I believe, which is a huge lot (maybe a majority).
Now, a problem is that this config is not listed in the config doc page, so a decision should be made on whether we document it, but I'm against because if you should never set it to False, we shouldn't …
> Lint check_conflicting_properties

- renpy/rollback.py
This is necessary so they can be counted out as the log is truncated, keeping `rollback_limit` accurate. This results in correct reporting from `renpy.can_rollback()` in the scenario where `config.rollback_length` has been exceeded.
**[Original issue](https://github.com/renpy/renpy/issues/5014) (steps to repro on 8.1.3)**
Presents as `renpy.can_rollback` returning `True` despite rollback not being possible.
Repro:
- Start game
- Skip to 099 (careful not to overshoot)
- Rollback as much as possible (usually lands just below 010 but before 001).
Observations:
- `renpy.can_rollback` reports inaccurately
- Warnings in console
- Log runs out before rollback_limit hits 0
**New issue (following https://github.com/renpy/renpy/commit/2a62b88aeb83f538cce64b55ea9aad13b0d3fa4d)**
Presents as rollback …
> Track hard checkpoints that have been blocked

- renpy/exports.py
warp_to_line() now has the problem Ren'Py doesn't return to main_menu when the game ends after warp by warp_to_line().
This fixes it.
> fix warp_to_line behavior

- renpy/loader.py
Loading the file from the archive inside `config.searchpath` on Android will be ignored, as the file is most likely also contained in `apk`.
A better solution would be to target `os.stat`, but I guess that's not currently available.
> fix: loading sequence

- renpy/common/00definitions.rpy
- renpy/display/movetransition.py
- renpy/display/transition.py
- sphinx/source/atl.rst
Systematically link to Warpers when mentioning time-warping functions, at least in Transitions (it should be done everywhere).
Replace None with `_warper.linear` in a signature - which is a white lie, as it's how it behaves and gives a wink towards how to pass warpers. Maybe it should be generalized ?
Add examples and more explanations in MoveTransition.
Add an example with the simplest transition in the Warpers section, for those who don't intuitively understand what a "read-only module" is, also fix the math formulas and make them more readable.
> Various improvements around warpers

- sphinx/source/changelog.rst
- sphinx/source/incompatible.rst
Adds a reference to the config in both changelog and incompat, since the config is now included in lint messages. The link won't work (since the config is not listed in config.rst) but it's intended, as a good practice.
Follows #3821 and #5150.
> Better document conflicting properties

- renpy/common/00compat.rpy
- renpy/config.py
- renpy/substitutions.py
- sphinx/source/changelog.rst
- sphinx/source/incompatible.rst
- sphinx/source/text.rst
Supercedes #5023 based on feedback. Going commit-by-commit and hiding whitespace changes is recommended.
---
This allows Python expressions to be used with text interpolation, i.e. `"I have [apples * 4] apple slices."`. This comes with a compatibility variable `config.interpolate_exprs` to revert to the old behaviour.
A single parser is compatible with, and used for, both old and new modes of operation. Code in `common` is expected to use interpolations able to be interpreted correctly in both mode of operation. Aside from not being able to use expressions, the main potential "gotcha" is the difference in how item access is interpreted (i.e. `foo[bar]`). This is documented on the incompatible changes page, along with how to retain the current mode of operation.
A side effect of the single …
> Treat string interpolations as Python expressions

- renpy/ast.py
Based on `The Question` & `Tutorial`.
`self.next` field always contains sub type of `ast.Node`
> fix: `TranslateSay.predict`

- renpy/atl.py
- renpy/display/transform.py
DualAngle.from_any is already dualangle_or_float, and anchorangles (if not None) cannot be a tuple of None, it can only be a tuple of float (from older versions of renpy, maybe from user code passing it in but I doubt it) or a DualAngle
ALIASES's values were never read, because the only read values of PROPERTIES are those also present in diff2_properties or diff4_properties, both of which are only populated by add_property
> Simplify renpy.transform.ALIASES and nuke dualangle_or_float_or_none

- renpy/common/_shaders.rpym
- renpy/display/layout.py
A second pass at this concept based upon the work done by @Elckarow in #4887.
The key differences are:
- Using the default BLIT operation rather than DISSOLVE.
- Discarding the mask's RGB via colour mask to (depending on which shader articles you read) possibly save some texture space.
- Simpler shader leveraging constants/uniforms and avoiding calculations and functions that can't be optimised by some hardware.
> Implement AlphaMask using shader

- renpy/config.py
- renpy/exports.py
There is a config.nvl_layer for the nvl dialogue and a config.choice but no config for the nvl choice, that's unfair. Also, passing _layer to the menu as a menu parameter is now allowed, the display_menu function politely gives way and uses the config(s) as a default.
The _layer parameter is documented for show_screen, so I think it's acceptable to document it for [menu arguments](https://www.renpy.org/doc/html/menus.html#menu-arguments) too. I didn't do the documentation pass, I think it should be documented as "Menu arguments passed to the menu itself become arguments to the renpy.show_screen function which passes them to the screen" and the rest of the sentence unchanged.
I'll document when the purpose is accepted.
This has been requested by a creator.
> Enable the _layer parameter for the menu statement and add config.nvl_choice_layer

- renpy/lint.py
Fixes https://github.com/renpy/renpy/issues/5272.
> lint: Allow emoji_font to be None

- renpy/atl.py
- renpy/display/transform.py
Fixes https://github.com/renpy/renpy/issues/5274.
- Brings back transform `ALIASES` type-mapping since they're needed for interpolation.
- Looks up and passes the type to interpolate_splines.
- Only attempts to convert to `position` when the config flag is true, and the passed type is position.
Tested with:
```rpy
transform example:
align (0, 0) offset (0, 0)
linear 2.0 offset (50, 100) knot (0, 33) knot (50, 66)
align (0, 0) offset (0, 0)
linear 2.0 align (.5, 1.) knot (0, .33) knot (.5, .66)
align (0, 0) offset (0, 0)
linear 2.0 pos (50, 100) knot (0.2, 33) knot (500, 66)
```
> Retain correct types during spline interpolation

- renpy/common/00compat.rpy
- renpy/config.py
- renpy/display/layout.py
- sphinx/source/incompatible.rst
Possible solution to #5268. Inspired by comment on the original issue and included below.
---
> It might make sense to change that going forwards, just for hover and idle, but this is going to be an 8.2 thing.
_Originally posted by @renpytom in https://github.com/renpy/renpy/issues/4578#issuecomment-1528933364_
> Filter events propagated through containers

- renpy/exports.py
It was unclear whether the pause ends when the time is expired AND the prediction is done, or if it ends when the time is expired OR the prediction is done.
From the issue the feature was proposed in, it's pretty clear that's an AND, and the passed time is a minimum rather than a maximum.
Now, what happens when the player clicks/skips, and what happens with timeless pauses ? I don't know, and I think it should be documented.
Also moves the hard parameter last, as it's not advised to use it.
> doc: Clarify renpy.pause's parameters

- renpy/rollback.py
Fixes #5289.
As we pop from the end of the log we decrement the limit until it is exhausted, before continuing to decrement the block count as further entries are popped in an effort to find a place to end rollback.
Verified using the test case provided in the linked issue.
> Prevent negative rollback counters

- renpy/ast.py
Addresses two issues:
- When `lookup` returned `self` both `predict` and `scry` could set up a loop returning references to `self` over and over.
This PR adds an explicit check for `node is self` as was already being done in `execute`.
- When scrying, and no translation was active, the scry data would not contain `Say` specific information that is expected.
This PR has `scry` defer to `Say.scry` when the result of `lookup()` is `None` or `self`.
> Fix TranslateSay scrying

- sphinx/source/config.rst
`config.periodic_callback` is older and having a list of functions is better than having one single function
> doc `periodic_callbacks` rather than `periodic_callback`

- renpy/rollback.py
Fixes https://github.com/renpy/renpy/issues/5311 in which the problem description can be found along with a test case.
Once the `hard_rollback_limit` is exceeded, hard checkpoints are added to the number of blocked checkpoints, ensuring that when totalled limit and block counts total the number of hard checkpoints currently in the log.
Now that the entire log is counted, it makes it safe to count hard checkpoints out of the log, first from the blocked count, and then from the limit count, never dropping below zero.
> Ensure that all checkpoints are tracked

- renpy/substitutions.py
`dicts` was never empty so the `else` was never entered.
I took advantage of this to replace inserts with appends which I think are faster.
> Fix optimization of string substitution

- renpy/display/dragdrop.py
Seeks to address a rare issue where a drag will be treated as mid snap animation, despite snap never having been called. I'm not sure this is the best solution, but it does appear to be _a_ solution, as I've not managed to recreate it with this change made locally.
I've been unable to come up with an easily reproducible test case for this, but have seen it multiple times during development.
My best guess is that it's to do with the drag widget being replaced and having it's x/y values updated at the same time, such that the time values trick it into thinking it's mid snap, despite `snap` never having been called.
> Avoid trying to snap when not snapping

- sphinx/source/changelog.rst
- sphinx/source/template_projects.rst
`changelog.rst`: Fix link to the vertical property and remove unncessary ` after renpy.fetch
`template_projects.rst`: config.build_name doesn't exist. Replaced it with build.name
> Update changelog.rst and template_projects.rst

- renpy/revertable.py
Remove unnecessary imports (which pose no pickle issue as modules themselves are not pickled) and use the documented way to access `__future__` contents - as python.py and script.py do.
> Cleanup some warnings in the revertable module

- renpy/exports.py
On android platform renpy.request_permission produce an exception: 
`AttributeError: 'NoneType' object has no attribute 'SDL_AndroidRequestPermission'`
See: #5510
It happens because `renpy.exports.get_sdl_dll()` function return None on android platform. Function tries to find a native `librenpython.so` in `os.path.dirname(sys.executable) + "/"`, but this path on Android is point to `/data/user/0/{package.name}/files`, which does not contain this file. 
So I added just `librenpython.so` in libs list, just like in the old versions where there is no this problem and function started to return what it had to.
> Fix permission requesting on Android platform

- renpy/text/hbfont.pyx
Variable fonts are usually divided into regular fonts and italic fonts, and italic fonts do not contain `bold` instance but `bold italic` instance usually.
Currently, renpy only uses `bold` instance for bold text, that causes when setting `config.font_replacement_map["sample-vf-font.ttf", True, True] = ("sample-vf-font-italic.ttf", True, False)` and use bold italic text, it will not use `bold italic` instance for "sample-vf-font-italic.ttf", but manually setting bold for it instead.
```shell
$ renpy.variable_font_info('NotoSans-full-vf.ttf')
Maximum texture size: 4096x4096
Named Instance: 'extralight'
Named Instance: 'light'
Named Instance: 'regular'
Named Instance: 'medium'
Named Instance: 'semibold'
Named Instance: 'bold'
Named Instance: 'extrabold'
Named Instance: 'black'
Axis: …
```
> Allow use italic/bold italic instance for variable font by default

- sphinx/source/python.rst
Fix an unpaired quotation mark in example code in python.rst.
It causes wrong code highlight in document page https://www.renpy.org/doc/html/python.html.
> Fix unpaired quotation mark in python.rst

- renpy/substitutions.py
Small optimisation for the fix in 10c02a4caf9a92e97b9c0bd108ab0084bdf1b79a.
We already bail early when inside parens (see code snip below), and taking the same approach with brackets allows us to short-circuit some unnecessary character checks.
https://github.com/renpy/renpy/blob/6a613314c5accfe231a3a063acc33f74aa9051b8/renpy/substitutions.py#L183-L184
> Skip unnecessary conditionals during interpolation

- renpy/gl2/live2d.py
On behalf of @auxiliaryout from Discord. His use case looked pretty legitimate.
Targeting fix branch as this should be completly backward compatiable.
> Allow to have the same model with 2 different default_fade

- launcher/game/tl/italian/common.rpy
- launcher/game/tl/italian/developer.rpy
- launcher/game/tl/italian/error.rpy
- launcher/game/tl/italian/gui.rpy
- launcher/game/tl/italian/launcher.rpy
- launcher/game/tl/italian/options.rpy
- launcher/game/tl/italian/screens.rpy
- launcher/game/tl/italian/script.rpym
Hello again everyone, this time I decided I would contribute something to Ren'Py!
My initial idea was to work on translating both of the example novels included with the SDK, since I was surprised to see that they aren't available in my native language, Italian. However, after starting to work on them, I noticed how many strings from the engine were not properly translated: a few were missing here and there, some had a few inconsistencies or slightly bad word forms, and quite a big chunk were of really low quality due to being machine-translated. So, here I got to work:
* ~[ ] Translating example and tutorial novels to Italian~ (will be moved to distinct PRs)
~* [ ] The Question~
~* [ ] Tutorial (this will probably take a while, but I think it's a good chance to study Ren'Py better)~
You …
> Update existing Italian translations and add missing ones

- renpy/common/00textshader_ren.py
```py
renpy.gl2.gl2shader.ShaderError: ERROR: 0:15: '/' : wrong operand types - no operation '/' exists that takes a left-hand operand of type 'highp 2-component vector of float' and a right operand of type 'const int' (or there is no acceptable conversion)
renpy.gl2.gl2shader.ShaderError: ERROR: 0:17: '*' : wrong operand types - no operation '*' exists that takes a left-hand operand of type 'const int' and a right operand of type 'const float' (or there is no acceptable conversion)
ERROR: 0:17: '*' : wrong operand types - no operation '*' exists that takes a left-hand operand of type 'const int' and a right operand of type 'highp float' (or there is no acceptable conversion)
ERROR: 0:17: 'cos' : no matching overloaded function found
```
> textshader: convert static int to float

- renpy/exports.py
This makes no change to the API.
Fixes the bug aspect of #5509 regarding kwargs.
About the change of parameter default, look at line 1276 and the commit comments. The goal is to avoid mutable parameter defaults, which are a bad practice.
> Tweak display_menu

- sphinx/source/incompatible.rst
The Incompatible Changes page has the variable written as `config.fill_shrinks_frames`, but `config.fill_shrinks_frame` is the correct variable
> Correct config.fill_shrinks_frames to config.fill_shrinks_frame

- renpy/lint.py
Prevent Lint from erroneously reporting a font file is not loadable when the font name is an alias in `config.font_name_map` for a file that *is* loadable.
Before:
```
Ren'Py 8.3.0.24061402+nightly lint report, generated at: Sat Jun 15 16:50:22 2024
Style style.default uses file 'Varela Round', which is not loadable.
Style style.say_label uses file 'Varela Round', which is not loadable.
Style style.button_text uses file 'Varela Round', which is not loadable.
Style style.gui_text uses file 'Varela Round', which is not loadable.
Style style.choice_button_text uses file 'Varela Round', which is not loadable.
```
After:
```
Ren'Py 8.3.0.24061402+nightly lint report, generated at: Sat Jun 15 16:48:53 2024
```
Where:
```renpy
define config.font_name_map = {
"Varela Round": …
```
> Add lint check for font aliases in font_name_map

- renpy/config.py
- renpy/exports.py
Related to https://github.com/renpy/renpy/issues/5267
> Clear config.log file during game startup

- renpy/display/behavior.py
- renpy/preferences.py
- sphinx/source/keymap.rst
Adds a fix for the `map_event` function so it can handle a list of gamepad bindings as well as a singular binding. Also updates the documentation to reflect the default pad_bindings as of 8.2 (notably the update to button_alternate).
> Gamepad event fix

- renpy/display/im.py
Currently, the '@' character in image names must be placed at the end, followed by a float value. It will raise an exception otherwise.
I'd like to be able to do the following:
- Name a directory `xyz@2` and have all the images inside it be oversampled
- ~~Name an asset or directory of assets after the handle of an artist who created them without throwing an error~~
Notes:
- The most specific specifier should win, so `assets@2/image@2.5.png` should have an oversample of 2.5.
- ~~I realize naming an asset after an artist's handle is a niche request, so I understand if you'd rather not have this to prevent confusion.~~
***
Examples of old behavior, which work the same / are unchanged:
```
images/assets/image.png -> no oversampling
images/assets/image@2.png -> oversampling of 2, and so on …
```
> Be more lenient with '@' in image names

- gui/game/screens.rpy
- renpy/common/00keymap.rpy
- the_question/game/screens.rpy
- tutorial/game/screens.rpy
Allow use of mousewheel to navigate between pages in the default save/load screen.
Not sure if there is a deliberate reason for omitting it, but as a player it has always bothered me that I couldn't scroll through my savegames using the mousewheel.
> Allow mousewheel to paginate save/load screen

- renpy/common/_audio.js
When `config.web_video_base` is set with an absolute URL to another origin, modern browsers won't load the video with an error:
> The HTMLMediaElement passed to createMediaElementSource has a cross-origin resource, the node will output silence.
For CORS to work:
1. The server serving the resources should have a `access-control-allow-origin: *` header.
2. The `video` element should have `crossorigin="anonymous"` [attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin).
This PR adds such an attribute to the `video`.
> Fix video playing if config.web_video_base URL is cross-origin

- sphinx/source/bubble.rst
- sphinx/source/cdd.rst
- sphinx/source/screens.rst
- sphinx/source/text.rst
- sphinx/source/thequestion.txt
- sphinx/source/translation.rst
- sphinx/source/updater.rst
Hi guys, 👋
this is just a single-commit fixing some typos I've found when reading Ren'Py docs.
> Fixes some typos found in docs.

- launcher/game/android.rpy
Allow to define a build.package for android.
`build.package("android_premium", "directory", "android all premium", "Android Core files and Premium", hidden=True, update=False, dlc=True)`
The package can be build from CLI:
`./renpy.sh launcher android_build the_question --package android_premium`
> Add package argument when building android from CLI

- renpy/common/00compat.rpy
- renpy/config.py
- renpy/display/accelerator.pyx
- sphinx/source/incompatible.rst
- sphinx/source/transform_properties.rst
Using crop to expand a displayable's area makes a lot of sense, though in an abstract way.
It's a partially incompatible change, sure, but that has to happen in any case because of my mistake.
Crop in general sets the new size of the child and from what coordinates (relative to the child) it starts.
Sure, that's a bit more abstract than cropping, but the same can be said of negative values for xzoom and yzoom : it makes sense when you get your mind around it, and there is a real use for it : flipping images.
There's a use in this case too, for adding padding around an image and setting a final size for the image, irrespective of its actual start size. I'm not sure of an way to do that differently.
> Unrestrain crop

- sphinx/source/textshaders.rst
Add the below Note to the textshader document
**Note** A text block should either use text shaders or not - mixing is not supported. For example, you should set :var:`config.default_textshader` or :propref:`textshader` style property if you use the text tag like above.
> add the textshaders doc note

- renpy/atl.py
- renpy/common/00compat.rpy
- renpy/config.py
- renpy/parameter.py
This fixes (sort-of) the #5237 in that it doesn't correctly reflect and reproduce the buggy previous behavior. As such, it should be shipped in 8.3, along with that already-merged update (which it compats). The only difference would be when an old game defines a pos-only parameter in a transform and then passes it a parameter by keyword - but that's a weirdly nonsense thing to to.
This issue does not re-authorize pos-only parameters, which are still forbidden at the parser except in compat mode), as that is the responsibility of #5592, which can be merged after 8.3.
> Patch compat ATL pos-only behavior

- renpy/common/00action_file.rpy
- renpy/loadsave.py
- renpy/savelocation.py
With Ren'Py default config, multiple `MultiLocation` functions call a related function on 2 different instances of `FileLocation` (one for "savedir" and one for "sync"). Some of these `FileLocation`'s functions call `synfc()`, so the warning message "2 FS.syncfs operations in flight at once, probably just doing extra work" shows up. This commit prevents that.
My main goal was to fix the problem for `MultiLocation.save_persistent()`, but since it appears for other functions, it probably does not harm to fix these as well (using a context for concision).
On a side note, emscripten 3.1.61 (05/31/24) introduces [an auto mode to persist the FS data](https://github.com/emscripten-core/emscripten/pull/21938) so that it is not needed anymore to call `syncfs()`.
> [Web] Only call syncfs once from MultiLocation functions

- sphinx/source/dialogue.rst
Fixed the example dialogue that causes an error by doubling the percentage sign `%`:
> doc: Fix example in dialogue.rst

- launcher/game/project.rpy
This change makes it easier for humans to read the `project.json` file.
Before this change, `project.json` looks like this:
```
{"build_update": false, "packages": ["linux"], "add_from": true, "force_recompile": true, "android_build": "Release", "tutorial": false, "renamed_all": true, "renamed_steam": true}
```
After this change, `project.json` looks like this:
```
{
"build_update": false,
"packages": [
"linux"
],
"add_from": true,
"force_recompile": true,
"android_build": "Release",
"tutorial": false,
"renamed_all": true,
"renamed_steam": true
}
```
> make project.json easier for humans to read

- renpy/text/text.py
This removes the second `push()` when handling the size tag, which was preventing the outermost tag from properly closing. Examples of the behavior this should fix:
```rpy
label start:
"{b}Bold, {size=*2}large and bold,{/size}{/b} still bold."
"{i}{u}{b}Styled, {size=*2}large and styled{/size}{/b}{/u}{/i}, still italic."
"{size=*1.5}1.5x large, {size=*2}3x large,{/size}{/size} still 1.5x large."
```
> Fix size tag preventing outer tags from closing

- sphinx/source/text.rst
jitter text shader does not have a speed uniform
> doc: Fix example of shader text tag

- launcher/game/front_page.rpy
- launcher/game/project.rpy
Addresses issue https://github.com/renpy/renpy/issues/2467
A Visual Novel developer wanted to customize their renpy launch screen because they do not use the default locations for their file structure. This PR allows a Visual Novel developer to customize their renpy launch screen via editing their project.json file. The defaults values are:
```
{
"renpy_launcher":
{
"open_directory":
{
"game": "game",
"base": ".",
"images": "game/images",
"audio": "game/audio",
"gui": "game/gui"
},
"edit_file":
{
"script.rpy": "game/script.rpy",
"options.rpy": "game/options.rpy",
"gui.rpy": "game/gui.rpy",
"screens.rpy": "game/screens.rpy"
}
}
}
```
> allow 'Open Directory' and 'Edit File' customization on renpy launch screen #2467

- launcher/game/package_formats.rpy
When experimenting with parallelizing all game builds performed via the GUI, every build took +1 second longer than the previous one, until RenPy was restarted. This change fixes that bug.
> fix bug that adds 1 second to each successive parallel build

- sphinx/source/cds.rst
When linting the code block from [Creator-Defined Statements ](https://www.renpy.org/doc/html/cds.html):
```sh
renpy game lint
```
I received the error:
```
While running game code:
File "examples/_creator_defined_statements.rpy", line 21, in lint_random
renpy.error(renpy.check_text_tags(i.what))
AttributeError: 'SubParse' object has no attribute 'what'
```
> doc: Fix code block in cds.rst

- module/ffmedia.c
This PR makes Ren'Py compatible with newer FFmpeg versions. A lot of deprecated APIs were removed in FFmpeg 7, leading to compile errors.
Old API compatibility is kept by means of compile-time version checks.
Fixes: #5681
> Replace deprecated APIs when compiling against newer FFmpeg

- README.rst
I have quite new ubuntu 24.04 in wsl2 and I tried to install it following the readme and found few issues which I'm fixing here:
- The setuptools were missing, so it's worth adding them when other stuff gets installed
- Cython 3 is out for quite some time and it's not compatible with `pygame_sdl2` at all. 
This is the log of my attempt
<details>
```bash
(renpy) (base) racinsky@PRGA-010501:/mnt/c/Projects/others/renpy/pygame_sdl2$ python setup.py install
pygame_sdl2.error is out of date.
pygame_sdl2.color is out of date.
pygame_sdl2.controller is out of date.
pygame_sdl2.rect is out of date.
pygame_sdl2.rwobject is out of date.
Error compiling Cython file:
------------------------------------------------------------
...
sf.base = base
sf.length = length
sf.tell = 0
rv = SDL_AllocRW() …
```
> docs: restrict the cython version and add setuptools

- renpy/audio/audio.py
- renpy/config.py
- renpy/execution.py
- renpy/exports/__init__.py
- renpy/exports/displayexports.py
- renpy/exports/persistentexports.py
i don't think labels, images and audio files should be marked as seen in replays. basically all other variables are local to that context.
for instance developer would be able now to temporarily unlock content of a replay gallery for higher tier patrons without actually changing the seen status of a label. to preserve the old behavior one can set the new config var to True.
> no seen labels, images, audio in replays

- renpy/common/00build.rpy
Some games make use of .rpe files to extend Ren'Py's capabilities and/or embed game-specific python libraries. This makes it possible to keep this kind of game working while still removing rpe files by default.
I have at least two such cases:
* A game that uses a custom archive format and augments Ren'Py with support for it
* Games that use my Epic Games integration for Ren'Py ( https://github.com/Ayowel/renpy-epicgames-eos )
> Only ignore .rpe files if they are not explicitly tracked

- renpy/common/_audio.js
Fixes `Uncaught ReferenceError: p is not defined`
> Fix an obvious undefined variable error

- README.rst
Pip outputs a parameter format error when using the `pip install` command as documented. This fixes it so that it works as expected.
> doc: fix python dependencies list for copy/paste

- renpy/common/00steam.rpy
The definition of GetAuthSessionTicket expects an identity parameter:
https://github.com/renpy/renpy-build/blob/0681b1bdb8836f4ded742491158234beb90d9059/steamapi/steamapi.py#L5083
This simple fix seems to work as expected.
> steam: fix get_session_ticket

- renpy/common/_errorhandling.rpym
`renpy.launch_editor()` is not supported on mobile (or Web) so clicking on the button does nothing.
> Do not offer to open "traceback.txt" on mobile

- sphinx/source/android.rst
Seems the original URL refering to "stable" doesn't exist anymore, this updates it to direct to "latest" instead.
> fix link to pyjnius docs

- tutorial/game/tutorial_atl.rpy
In the "Tutorial" > "Transforms and Animation", there is a section that demonstrated that `repeat` can take an integer argument.
However, the `alt_image1` example code is shown twice on lines 543 and 548 for two different examples.
Line 548, should be changed to show the `alt_image2` example code which removed the `repeat 2` line from the previous example, showing that the animation will only happen once.
> Fix the ATL part of the tutorial to show the correct example code

- sphinx/source/label.rst
Most internal labels start with an underscore and can be easily told apart from regular labels. 
There are couple labels that don't. All are defined under common/_layout/ and thus Ren'Py throws a "defined twice" exception should someone try to define their own with the same name, but I figured it would be nice to have them briefly mentioned in the docs nonetheless.
> Mention screen calling labels in Special Labels

- renpy/gl2/live2d.py
looks like you forgot to put this code here?
i've been using `live2d.blend_parameter` in my `update_function`, but `live2d.blend_opacity` threw an error saying it didn't exist until i added this code. now it exists and works fine
> Live2D.blend_opacity wasn't usable

- sphinx/source/persistent.rst
9df57291d68fa259033a51a5b8b502eece6dd985 (via #5000) changes the behavior of `persistent._clear` to re-apply default values, which makes the existing documentation wrong. Re-applying to default values and "resets the persistent data" already makes it clear enough that the data in memory is being "deleted" (which could instead also be interpreted as immediately deleting the persistent file on disk).
> docs: Update persistent._clear with current behavior

- renpy/display/presplash.py
Checks for foreground+background first, before falling back to the single presplash image, instead of the other way around, to match [behavior in the documentation](https://www.renpy.org/doc/html/splashscreen_presplash.html#adding-a-progress-bar).
> Fix order of attempting to load presplash images

- renpy/substitutions.py
Fixes #5981
When scopes are stacked in [`substitute`](https://github.com/renpy/renpy/blob/9d4fd5aef1f0c49918d394759fd6ceb1ac0b9dfd/renpy/substitutions.py#L371) the resulting `MultipleDict` instance would fail to meet the expectation from Python proper that missing keys raise a `KeyError` (rather than a `NameError`). During `eval` this would unintentionally prevent access to `builtins`.
Switching to the `collections` module's `ChainMap` would have been ideal here, as it serves the same purpose, and being Python managed it's more likely to retain compatibility with `eval` in future. Unfortunately however it's not available in Python 2. A separate PR to make that change in readiness for 8.4 will be submitted shortly.
The problem and difference is illustrated in the REPL reproduction below. …
> Prevent MultipleDict masking builtins during interpolation

- renpy/substitutions.py
Originally intended as a fix for #5981, but postponed due to Python 2 compatibility requirements.
In the original issue, when scopes were stacked in [`substitute`](https://github.com/renpy/renpy/blob/9d4fd5aef1f0c49918d394759fd6ceb1ac0b9dfd/renpy/substitutions.py#L371) the resulting `MultipleDict` instance would fail to meet the expectation from Python proper that `KeyError`s be raised for missing keys (it was previously raising `NameError`s). During `eval` this was unintentionally preventing access to `builtins`.
Switching to the `collections` module's `ChainMap` serves the same purpose, but as it's Python managed it's more likely to retain compatibility with `eval` in future, and less code for us to worry about.
The compatible behaviour with `MultipleDict` is illustrated in the REPL …
> Switch from MultipleDict to collections.ChainMap

- renpy/display/behavior.py
- renpy/sl2/sldisplayables.py
- sphinx/source/screens.rst
- sphinx/source/style_properties.rst
This PR does the following:
1) Updates `thumb_offset` to optionally take a tuple instead of an integer. If provided a tuple, the first number is used to offset the left/top of the bar, and the second number is used for the right/bottom. This is helpful for bars whose thumb is asymmetrical, such as a half-circle. In particular, it avoids issues with semi-transparent image overlap (in general or when using ATL or transitions). It is backwards-compatible with the regular integer value.
https://github.com/user-attachments/assets/293e33dc-9331-47b3-916c-a96264cff8d0
https://github.com/user-attachments/assets/94614917-c43f-4d2c-af47-dba9d229f613
2) Adds a `thumb_align` property to bars. This solves an incredibly common issue which occurs when the bar's thumb is larger than the bar images. Most …
> Bar property update & addition

- renpy/common/00action_menu.rpy
- renpy/common/00barvalues.rpy
- renpy/common/00definitions.rpy
- renpy/common/00gui.rpy
- renpy/common/00inputvalues.rpy
Running lint on "The Question" in nightlies surfaces these Python warnings which are due to unescaped backslashes in docstrings of various common files.
```
Python Warnings:
renpy/common/00action_menu.rpy:123: SyntaxWarning: invalid escape sequence '\d'
screen = self.screen or store._game_menu_screen
renpy/common/00barvalues.rpy:254: SyntaxWarning: invalid escape sequence '\ '
class VariableValue(FieldValue):
renpy/common/00barvalues.rpy:296: SyntaxWarning: invalid escape sequence '\ '
self.variable = variable
renpy/common/00definitions.rpy:11: SyntaxWarning: invalid escape sequence '\ '
renpy/common/00gui.rpy:237: SyntaxWarning: invalid escape sequence '\_'
prefs[self.name] = self.b
renpy/common/00inputvalues.rpy:112: SyntaxWarning: invalid escape sequence '\ '
return None …
```
> Use raw strings for docstrings that contain unescaped slashes

- renpy/common/00matrixtransform.rpy
In `python3.12`, the `function` method is `bound` rather than `built-in` after init.
Related to raising `Cython` - https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#compiler-directives
```
binding (True / False), default=True
Controls whether free functions behave more like Python’s CFunctions
(e.g. [len()](https://docs.python.org/3/library/functions.html#len)) or, when set to True,
more like Python’s functions. When enabled, functions will bind to an instance when looked up as a class attribute (hence the name)
and will emulate the attributes of Python functions, including introspections like argument names and annotations.
Changed in version 3.0.0: Default changed from False to True
```
```python
OffsetMatrix(0, 0, 0)(None, 1)
```
```
Traceback …
```
> fix: function property of `TransformMatrix`

- renpy/display/focus.py
This fixes an issue wherein the user wants to set the focus on a screen, but the request is overridden by Ren'Py's default_focus system forcing the largest default_focus to be focused instead.
> Don't overrule focus override for max focus

- renpy/ast.py
- renpy/exports/scriptexports.py
- renpy/lint.py
- renpy/main.py
- renpy/script.py
- renpy/statements.py
- renpy/translation/__init__.py
In this PR I add following changes in `renpy.ast`:
1. Add type hints and documentation for some fields and functions of the module.
2. Make `Node.get_init` and `Node.early_execute` to always exist. They do not appear in flame graph, so such calls take less time than `cProfile` clock resolution.
3. Change `Node.get_init` to return integer priority to call of `self.execute_init` when init code executes, instead of tuple of `priority, Node or Callable`. This simplifies meaning of initcode of script and most importantly, allow to perform `config.profile_init` check on `UserStatement` nodes, which if implemented badly may take more time than developer intended.
4. Remove `after` and `block` slots from `TranslateSay` and implement them as `self.next` and `[]` properties. (Probably need to add …
> Make `renpy.ast` more polymorphic.

- renpy/display/transform.py
When not passed a `child` argument, `ATLTransform.__call__` will presume to use `self.child` which is not desired during `_in_current_store`.
To avoid this, rather than building the transform and then injecting the child, we instead pass the child explicitly. Additionally, we call `_unique` on the child prior to passing it into the transform in order to forestall any `_duplicate` attempts during the build process. This best matches existing behaviour where we would call `_unique` on the transform (and thus its child) immediately after injection.
> Fix to _in_current_store behaviour for ATLTransform

- renpy/lint.py
Lint still uses a function removed when the [bytecode cache was improved](https://github.com/renpy/renpy/commit/fe02e12192d74f448f3b49b1193ef4a9ea676623).
> Update lint to use py_compile function

- experimental/cslots/cslots.pyx
- experimental/cslots/test_cslots.py
- renpy/cslots.pyx
I'll preface this by noting that my Cython and C knowledge is pretty low on the ground, so these are changes that seem to make _logical_ sense, but others will have to determine whether they make _practical_ sense.
- Make it easy to continue using the experimental tests while the cslots feature is still in development.
- Remove `default_int_value` as it appears to be a duplicate value store, and isn't strictly needed in the one place it is used.
- Allow `IntegerSlot` descriptors to re-open a compressed object automatically, matching behaviour of the generic `Slot` descriptor.
> Suggestions for cslots

- renpy/display/render.pyx
- renpy/display/video.py
When the next video frame is not ready, the previous one is returned by `get_movie_texture_web()`. Normally, this is just a GLTexture instance, but when using a mask, that frame is a Render instance instead. The problem is that Render instances get killed soon after they have been drawn, so `get_movie_texture_web()` returns a dead instance when re-using the previous frame which causes a crash because of missing uniforms when drawing the screen.
Ideally, we should prevent the Render from being killed as long as it is part of `renpy.display.video.texture`, but I'm not sure how to do that (maybe visiting that dict in [`mark_sweep()`](https://github.com/renpy/renpy/blob/77aaeaa51445a0f0d3eddd26741a23e8b7876b0e/renpy/display/render.pyx#L493)?). At least with this PR, there is no more crash, …
> Do not kill Renders that cache the last video frame on Web

- renpy/__init__.py
- renpy/gl2/gl2draw.pyx
- Took @Kassy2048's suggestion from https://github.com/renpy/renpy/issues/6067#issuecomment-2575906582 to skip the Windows version check, since we already know we're on Windows, and that's all we care about in `__init__`.
- Revisited 919e22059b327063d95ea4c754b0ebb566261aae to remove the conditional block completely as it was intended to only apply to version 7 of Windows and older, and with support dropped the whole condition block is no longer relevant.
Potentially the whole `get_windows_version` function could be removed, _if_ it's not considered part of the public API. It doesn't appear to be documented, and running it on Linux (and I suspect any non-Windows platform) yields `(10, 0)` so any use it did have seems like it would be limited.
> Small clean up of Windows platform checks

- renpy/common/00definitions.rpy
- renpy/display/transform.py
Fixes https://github.com/renpy/renpy/issues/6083.
The built-in reset transform will now reset all transform properties rather than only a small subset. This makes it more predictable (no more guessing which properties it will reset) and also future proof as it no longer requires being kept up to date as an explicit definition.
> Improve standard reset transform

- renpy/__init__.py
This was previously used to make allowances for Windows 7 and below, however those conditions have been dropped along with Windows 7 support and so there's no need to keep this function around.
API wise, I've looked through the docs and to the best of my knowledge it's completely undocumented and was only ever intended to be used internally during boot.
> Remove disused internal function

- launcher/game/distribute.rpy
- renpy/main.py
This ensures that any subdirectories between the requested rpa archive path and project root are built before creating the rpa file.
Example build using a modified `the_question`:
```diff
the_question/game/options.rpy
@@ -192,6 +192,12 @@ init python:
build.classify('**/#**', None)
build.classify('**/thumbs.db', None)
+    build.archive("arc_png")
+    build.classify("game/images/*.png", "arc_png")
+
+    build.archive("assets/jpg")
+    build.classify("game/images/*.jpg", "assets/jpg")
+
```
Build:
```text
> ./renpy.exe launcher distribute the_question
Scanning project files...
Archiving files... - 8 of 8
Archiving files... - 4 of 4
Scanning Ren'Py files...
Writing the pc zip package. - 1713 of 1713
Writing the linux tar.bz2 package. - 1697 of 1697
Writing the mac app-zip package. - 1702 …
```
> Implement creating rpa archives in subdirectories

- renpy/display/layout.py
- sphinx/source/screens.rst
https://www.renpy.org/doc/html/screens.html#nearrect is missing documentation for the properties `preferred_side` and `invert_offsets` added in #5114 . Additionally, `class Nearrect` is missing documentation for the `focus` keyword.
This PR also contains a first stab at updating the layout description to account for the fact it can now run in either axis as appropriate.
Apologies if the documentation contains any build errors, I currently have no way to build it.
> Update `nearrect` documentation

- renpy/common/_layout/classic_load_save.rpym
Found logical error that prevented one ancient VN from viewing manual saves. Fix is plain and simple.
> Handle newest_mtime initialized as None while determining newest game save

- renpy/character.py
- renpy/display/behavior.py
- renpy/exports/contextexports.py
- renpy/exports/displayexports.py
- renpy/exports/platformexports.py
- renpy/exports/predictexports.py
- renpy/exports/restartexports.py
- sphinx/source/audio.rst
- sphinx/source/config.rst
- sphinx/source/displayables.rst
- sphinx/source/label.rst
- sphinx/source/matrixcolor.rst
- sphinx/source/other.rst
- sphinx/source/quickstart.rst
- sphinx/source/translation.rst
Edited the explanation of "premultiplied alpha" slightly to be more newbie friendly, while hopefully keeping it technically correct.
Rewrote "Audio Namespace and Directory" into "Audio Directory and Namespace". More user friendly section allowed it to be moved to the top of Audio doc page, keeping it consistent with "Displaying Images" doc page. 
- Some typos
- Removed Editra from Quickstart page and recommended VSCode instead
- Corrected default values of config variables
- Commented out `config.web_video_prompt` (see #6133 ).
> Doc changes - Colormatrix, Audio, general cleanup

- renpy/display/error.py
- renpy/exports/displayexports.py
- renpy/loader.py
- renpy/main.py
Fixes #6135.
---
**Old behaviour**
- Load extensions.
- Deep glob each directory in `config.searchpath` looking for archives.
- Set `config.archives` to stems of the found archives, throwing away the full path and extension.
- Index archives
- Use trial and error to try and locate the archives we just globbed in `config.searchpath` directories.
- Use trial and error to match the header of a found archive to a handler.
- Store the relative path of the archive and its index.
- `listfilesdir`
- Compile file lists (including a full scan of `config.searchpath` directories).
- Load from archive
- Use trial and error to find archive in `config.searchpath`.
**New behaviour**
- Load extensions (nominal improvements, see first commit).
- Index files
- Trigger `listfilesdir`
- Collect archive file …
> Optimise startup file scan

- renpy/__init__.py
- renpy/common/_errorhandling.rpym
- renpy/display/error.py
- renpy/lexer.py
- renpy/parser.py
- renpy/python.py
- renpy/script.py
- renpy/translation/__init__.py
This PR improves how RenPy reports parse errors in Python code (this can later be expanded to RenPy code).
Before:
After:
---
Parse errors screen now automatically highlights error part of parse error if its message has more that one caret, e.g.
```
I'm sorry, but errors were detected in your script. Please correct the
errors listed below, and try again.
File "game/script.rpy", line 41: did you forget parentheses around the comprehension target?
[x, y for x, y in zip([1, 2, 3], [3, 2, 1])]
^^^^
File "game/script.rpy", line 45: Generator expression must be parenthesized
bar(1, i for i in range(3), 2)
^^^^^^^^^^^^^^^^^^^
File "game/script.rpy", line 48: cannot assign to True
True = False
^^^^
File "game/script.rpy", line 51: expected '('
def foo:
^
File "game/script.rpy", line 55: expected …
```
> First bit of PEP 657 in RenPy

- renpy/display/particle.py
This PR removes the import of renpy.display.render.BLIT from renpy/display/particle.py. A previous commit removed the use of BLIT.
> Remove unused import

- renpy/lexer.py
- renpy/python.py
This moves munging to AST, so column offsets match source code, so tracebacks display correct carets on lines with munged names. E.g. for input
```
"""renpy
init python:
"""
def __pass():
...
def foo():
try:
__pass(), __pass(), 1 / 0, 1 / 0, 1 / 0, 1 / 0, 1 / 0, 1 / 0
except Exception as e:
__exception(e), (lambda x: [i for i in range(x) if i])(100000)
def __exception(e):
raise e
foo()
```
Right now it render this
```
Traceback (most recent call last):
...
File "renpy/common/00db_ren.py", line 37, in foo
__exception(e), (lambda x: [i for i in range(x) if i])(100000)
^^^^^^^^^^^^^^^^^^^^^^
File "renpy/common/00db_ren.py", line 41, in _m1_00db__exception
raise e
File "renpy/common/00db_ren.py", line 35, in foo
__pass(), __pass(), 1 / 0, 1 / 0, 1 / 0, 1 / 0, 1 / 0, 1 / 0
^^^^^ …
```
> Fix incorrect column offsets of munged names.

- renpy/text/hbfont.pyx
Fixes the issue described in (https://github.com/renpy/renpy/issues/6202). May or may not also fix (https://github.com/renpy/renpy/issues/2268) (Untested). I don't think freetype adjusts offsets of glyphs, so there isn't a reasonable way of fixing this for that.
> Fix glyph offsets in HarfBuzz.

- renpy/gl2/gl2draw.pyx
Missed call `draw_render` in d2ee4e395282bcaa215ad907096d722df06815db
Broken call `Matrix.cscreen_projection` by tuples in d2ee4e395282bcaa215ad907096d722df06815db.
And adding `set_text_rect` to alocate memory inside the method.
> gl2: fix opaque by `draw_render` & `cscreen_projection` call

- renpy/ast.py
- renpy/config.py
- renpy/persistent.py
- sphinx/source/changelog.rst
- sphinx/source/config.rst
A callback is needed for this as a `persistent` file can be loaded at any time by the save-scanning thread. The most common example of when this would occur is immediate after using Ren'Py Sync to retrieve remote save files, but can also occur if a player drops a newer `persistent` file into one of the various save locations observed by the scan thread.
The callback should be set "early", and has been added to `renpy.ast.EARLY_CONFIG` and documented accordingly. This is so it is already in-place by the time `renpy.persistent.init()` is called in `renpy.main.main`.
In addition `persistent._version` is set to the current version of the game, if is not already set. This felt like a good addition which seeks to parallel the behaviour of `store._version` defined in normal save files, which can …
> Add callback for when persistent file is loaded

- renpy/persistent.py
- renpy/savelocation.py
Ren'Py currently holds on to loaded data long past necessary (in `FileLocation` objects), and for larger games especially this can result in a non-trivial amount of memory being consumed, especially as there are typically at least three copies of persistent: game, user, and sync.
This patch frees the persistent object in `FileLocation` when it is pulled for merging into the main persistent object, while leaving the mtime value, used to determine when to reload it, untouched.
A happy side effect of this is that the amount of operations done when evaluating whether a merge is needed is reduced significantly.
> Avoid storing persistent data replicas in memory

- renpy/persistent.py
- renpy/savelocation.py
More detailed rationale in the respective commits, but here's the headlines:
- Right now a typical boot performs six persistent data load operations (user x3, game x2, sync x1), even though most of this data is ignored due to `mtime` checks.
- The first commit reuses `FileLocation` objects to reduce this to four (user x2, game x1, sync x1).
- Second commit uses the established `mtime` behaviour to cut this down to between one and three (user x1, game x1, sync x1), by skipping game and sync loads if they don't have a newer `mtime`. Anecdotally two was most common, then three, then one. This was due to the write order of files (and thus mtime), and prompted the next commit.
- Finally the third commit reverses the order of `FileLocation`s when saving persistent data. This ensures the user …
> Reduce number of times persistent files are loaded during boot

- renpy/character.py
- renpy/config.py
- tutorial/game/tl/french/tutorial_nvlmode.rpy
- tutorial/game/tl/french/tutorial_quickstart.rpy
- tutorial/game/tl/japanese/tutorial_nvlmode.rpy
- tutorial/game/tl/japanese/tutorial_quickstart.rpy
- tutorial/game/tl/korean/tutorial_nvlmode.rpy
- tutorial/game/tl/korean/tutorial_quickstart.rpy
- tutorial/game/tl/piglatin/tutorial_nvlmode.rpy
- tutorial/game/tl/piglatin/tutorial_quickstart.rpy
- tutorial/game/tl/russian/tutorial_nvlmode.rpy
- tutorial/game/tl/russian/tutorial_quickstart.rpy
- tutorial/game/tl/schinese/tutorial_nvlmode.rpy
- tutorial/game/tl/schinese/tutorial_quickstart.rpy
- tutorial/game/tl/spanish/tutorial_nvlmode.rpy
- tutorial/game/tl/spanish/tutorial_quickstart.rpy
- tutorial/game/tl/ukrainian/tutorial_nvlmode.rpy
- tutorial/game/tl/ukrainian/tutorial_quickstart.rpy
- tutorial/game/tutorial_nvlmode.rpy
- tutorial/game/tutorial_quickstart.rpy
This pull request addresses a few spelling errors or grammatical mistakes I noticed in the code comments and documentation. 
A few of the tutorial strings were also updated to fix grammatical errors that I had noticed.
Fixed spelling errors in code comments and documentation for:
character.py
config.py
Replaced “rather then” with “rather than” in tutorial_nvlmode.rpy
Corrected the capitalization in dialogue in tutorial_quickstart.rpy
Removed the double contraction "that's it's" in tutorial_quickstart.rpy
No functional code changes were made, only changes to improve text accuracy and readability.
> Fix typo in documentation and tutorial

- renpy/character.py
one line addition to have more visual options for ctc's
fix for #6197
> Show ctc_pause when using extend

- renpy/gl2/gl2texture.pyx
- renpy/gl2/gl2uniform.pyx
Potential fix for https://github.com/renpy/renpy/issues/6261.
The scaling filters of a texture are now left for the texture itself to determine, unless explicitly overridden. This allows the MIN filter to be based on whether mipmaps are available.
You can see the existing code for setting the scaling filters per texture here:
https://github.com/renpy/renpy/blob/f0cb787964544a08c5fd665631047a991b9397e2/renpy/gl2/gl2texture.pyx#L604-L607
Previously, even if a texture had realised that it should use `GL_LINEAR` rather than `GL_LINEAR_MIPMAP_NEAREST` due a lack of mipmaps, the default would override that in the `Sampler2DSetter`.
> Remove implicit override of texture_scaling

- renpy/__init__.py
Previously the `Early init took` log line would include all the time since the last boot/reload, which was frustrating when working in that area of the codebase.
> Ensure sane clock times in log after reload

- renpy/display/presplash.py
Fixes #6271.
Core of the change is that the presplash will now include common script files when calculating how many pumps it is expecting. Additionally the calculation of the expected total is now only done once (allowing some short-circuit checks to be simplified), and the magical `23` number representing the static number of expected `log_clock` calls during boot has been moved to a variable hinting at its purpose.
> Update presplash progress after load order changes

- renpy/display/presplash.py
- renpy/main.py
- renpy/style.pyx
- renpy/translation/__init__.py
**Problem**
The change in https://github.com/renpy/renpy/commit/45352847ab94b8e41592740aac9ba6913d4f7eef resulted in styles being regenerated and screens being reprepared each time a new context was begun — typically when starting a new game, loading a earlier save, or launching a replay. This introduced click lag when performing these actions, most noticeably in games with a high screen count.
**Solution**
Per-discussion on Discord, this PR takes a broader approach to tackle the problem with the aim to reduce the impact of language initialisation and related tasks more generally. This is achieved by only doing them when necessary and eliminating repeated work both during boot, and when starting contexts.
Rough commit-by-commit synopsis. More details in commit messages.
1. Move …
> Optimise language initialisation

- renpy/text/text.py
Fixes #6287.
The `depth` value for outlines was being calculated in a separate loop to where it was being used, the result of which being that each outline was given the same final value of `depth` from the first loop instead of one relevant to the iteration.
<details><summary>Test case code</summary>
```rpy
label main_menu:
$ _confirm_quit = False
return
label start:
scene bg
show screen test()
pause
return
define config.default_textshader = "typewriter"
screen test():
text '{shader=test}Hello World!{/shader}':
at transform:
align (0.5, 0.5)
zoom 10
outlines ((20, 'f77', 0, 0),
(15, 'f77', 0, 0),
(10, 'f77', 0, 0),
(5, 'f77', 0, 0))
init python:
renpy.register_textshader(
"test",
variables="""
uniform float u_text_depth;
""",
fragment_500="""
gl_FragColor.rgb *= u_text_depth / 6.;
""") …
```
> Move depth tracking to correct loop

- renpy/common/_audio.js
Initializing the gain to 0 for new channels makes sure the fade-in starts from 0 for the first audio clip played on the channels. If no fadein is given for it, the gain will be set to max by start_playing() and there is no reason for the first audio clip to have the fadeout property set in start_playing().
Fixes #6291
> Fix fade-in for first audio clip on Web

- renpy/bootstrap.py
- renpy/common/00console.rpy
- renpy/common/_errorhandling.rpym
- renpy/config.py
- renpy/display/error.py
- renpy/error.py
- renpy/execution.py
- renpy/game.py
- renpy/lexer.py
- renpy/log.py
This PR adds support for [Fine Grained Error Locations](https://peps.python.org/pep-0657/) in Ren'Py error handling.
That allow to render different color in exception screen and precice carets in traceback file.
In this PR I adopted some code from Python 3.14 traceback module, adding handling of Ren'Py `_ren.py` extra indent and munged names, and also added ExceptionPrintContext abstract class that actually emits output to abstract printer and implemented it for console attached to the process, traceback.txt file and exception screen.
Things to fix before it can be merged:
1. Handle non-ASCII text in lines.
2. Handle wide chars in console and text file.
3. Handle SyntaxErrors in new system.
4. Update Ren'Py console to use new system.
5. Test it thoroughly.
> Initial implementation of PEP 657

- launcher/game/front_page.rpy
- launcher/game/images/folder.svg
- launcher/game/preferences.rpy
- launcher/game/project.rpy
- launcher/game/style.rpy
This adds the following:
- Support for folders in the launcher for Projects, Libraries and Templates.  Folders only appear to the user if they have libraries or templates, by default they will not appear.
- Adds a new project type, "Libraries".  Uses the same JSON file method as Templates.
- Cleans up the "clear" launcher style and integrates it into the standard light mode.
- Adds preferences for showing/hiding the default projects (The Question and Tutorial) as well as Templates (This was already in the code, just unused).
- Adds one 646 byte image for the folder icon.
> Launcher Folders

- renpy/lint.py
Hi,
Just noticed that our CI had been logging linting problems for a while without failing, thus not prompting us to fix/investigate further.
This PR allows to keep the current differentiation between errors and problems but allows to opt in to more strict linting rules by returning an error code even if only problems occured.
This is quite important for us as Ren'Py's linting output is quite verbose even if no error occurs (a huge amount of game characters makes it so that problem logs are not even visible on the screen), is not very parseable, and the amount of deprecated stuff that is only reported as a problem and not an error will end up biting us hard if not taken care of as it gets deprecated.
Thanks in advance,
> Support returning an error code when a problem is encountered during linting

- renpy/display/layout.py
- renpy/sl2/sldisplayables.py
- sphinx/source/screens.rst
These properties combined with transpose allow for 8 different ways to fill a grid. The way grid is rendered had to be changed slightly.  
Tested for all types of grid (square, more-rows rectangle, more-columns rectangle).  
Behind-the-scenes of the grid was changed. It now generates a gridmap (dict of {child : (col, row)}), and children are placed according to it, rather than always being filled in row-major order. Offsets are also sorted based on gridmap.  
This shouldn't break anything in existing code.   
Closes #6007
> Add right_to_left and bottom_to_top Grid properties.

- renpy/common/_errorhandling.rpym
- renpy/error.py
- Drop "Traceback (most recent call last):" lines.
We provide our own more specific context to traces already, no need for two.
- Prevent double indentation of stack frames in text file output.
Fewer characters is nice in some scenarios (such as pasting traces into Discord).
Also makes each increase in indentation level consistent, and matches how it appeared in 8,3 and previous.
- Restore breathing room around tracebacks on exception screen.
- Include the initial "File " of frames in the location hyperlink.
I noticed this when scanning the left side of traces, having each line start the same colour was distracting in a way that I hadn't previously remembered, and I believe this was why.
Also matches how we dynamically highlight parse errors: …
> Preserve some niceties of older traceback style

- sphinx/source/config.rst
The explanation for the following config variables is identical, motivating this adjustment.
- https://www.renpy.org/doc/html/config.html#var-config.bottom_layers
- https://www.renpy.org/doc/html/config.html#var-config.top_layers
This adjustment is a guess on my part, since I'm not intimately familiar with the source code and have no idea how to look it up.
> Adjustment in config.bottom_layers docs

- renpy/common/_errorhandling.rpym
- renpy/error.py
Revisits #6304 to simplify the approach to context lines, and in the process resolve #6321.
Effectively reverts 7a95e5be21934792a21048d9a15ac1e6cc0d4465, replacing it with a simpler alternative, and leaves context lines to the calling code as was previously the case.
> Fix context lines of chained exceptions

- renpy/loadsave.py
For https://www.renpy.org/doc/html/save_load_rollback.html#renpy.can_load
- Returns true if `filename` exists as a save slot, and False otherwise.
+ Returns true if `filename` (e.g. '3-2' for page 3, slot 2) exists as a save slot, and False otherwise.
> Added extra information because of dubious use of "filename" instead of "save slot"

- renpy/config.py
- renpy/display/image.py
- renpy/display/screen.py
- renpy/error.py
- renpy/script.py
- renpy/sl2/slast.py
This PR adds error suggestions to Ren'Py error handling. This works by adding `config.error_suggestion_handlers` (is hook a better term here?) dictionary from exception type to function that takes raised exception and returns suggestion text.
Also it adds handlers for AttributeError, NameError and ImportError from Python, and Ren'Py specific handlers for unknown label names, screen names and image tags (but not attributes).
> Error suggestions

- renpy/text/ftfont.pyx
- renpy/text/hbfont.pyx
- renpy/text/text.py
- src/_renpybidi.pyx
- src/renpybidicore.c
- src/renpybidicore.h
Builds on and supersedes #6313, fixes #6284.
Credit for figuring out the problem, and how to solve it goes to @TDCMC, I mostly just wrapped it in a bit of Python.
Main goals were to:
- Have RTL text in the middle of a LTR paragraph display correctly when using `harfbuzz`.
- Avoid needing to create duplicate/copy `TextSegment` objects.
- Avoid holding directionality as part of a font's state.
- Slice `str`s rather than rebuild them using per-character concatenation (`+=`).
<details><summary>Finally, here's the script I've been using to test it.</summary>
```rpy
define config.rtl = True
label start:
"This is a \u0646\u0648\u0634\u062A\u0647 in rtl."
"This is a \u0646\u0648\u0634\u062A\u0647 in rtl." (show_shaper='freetype')
"\u0633\u0644\u0627\u0645 player …
```
> Support embeded RTL when using harfbuzz as shaper

- renpy/error.py
Fixes #6302, problem 2.
Previously the caret string could be shorter than the line, and crash out when using zip.
https://github.com/renpy/renpy/blob/f65804c4f8c8f6f6c4943ab7ed619ef8e81ebfbc/renpy/error.py#L317
> Prevent exception during handling of some syntax errors

- renpy/gl2/live2dmodel.pyx
Error was
```
File "renpy/gl2/live2dmodel.pyx", line 559, in renpy.gl2.live2dmodel.Live2DModel.render
AttributeError: 'NoneType' object has no attribute 'add_shader'
```
> Fix critical error in Live2D render.

- renpy/loader.py
Per #4644
This rewrities RenpyImporter to modern standarts with following changes:
1. Create only one instance of the class, and add prefixes by a method.
2. Cache modules discovery, so scanning happens only once, and during import it is cache lookups.
3. Add support for [namespace packages](https://peps.python.org/pep-0420/) even inside archives.
4. Correctly set `mod.__file__` and `mod.__spec__.origin` to absolute path when it is avaliable, but sets to relative path when actual file is in archive or apk.
> Rewrite RenpyImporter to be more align with new import strategies.

- renpy/loadsave.py
- sphinx/source/save_load_rollback.rst
- Added a section delving deeper into the organization of a save file, and listing the built-in metadata.
- Added extra information and examples to renpy.save, renpy.list_saved_games, and renpy.slot_json.
I'm not familiar with the markup language these files use, and tried to follow existing styles.  
If I made any factual mistakes or syntax errors, I'm happy to make corrections.
> Documentation enhancement about savefiles and metadata

- renpy/pyanalysis.py
- renpy/python.py
when the function / variable has been marked as `pure` / `const`
the idea is that
```rpy
init python in my_store:
@renpy.pure
def my_pure_function(): pass
my_const = 1
renpy.const("my_store.my_const")
init python in my_other_store:
from store.my_store import my_pure_function, my_const
```
doesn't mark `my_other_store.my_pure_function` as `pure`, nor `my_other_store.my_const` as `const`
you could do that manually, of course, but it's not practical when you have a lot of things to import
PR is a draft because of 3 things:
for n°1, when compiling an `init python`, we could set a variable to the store's name, which we could grab in visit_ImportFrom
for n°2, one way of doing it would be to add a tuple of (fullname, after_import_fullname) to a list somewhere, and then loop over these tuples …
> mark imported function / variable as `pure` / `const` in the importing store

- renpy/display/dragdrop.py
It says about "drag_name": "available as the `name` property of draggable objects". In fact, using `Drag.name` causes an exception. The correct property name is `drag_name`, so I believe this should be corrected.
> Update dragdrop.py docstring

- sphinx/source/build.rst
Based on the code in launcher\game\distribute.rpy, and renpy\script.py, expanded on how old-game is involved in the creation of updated rpyc files.
> Docs enhancement about old-game

- renpy/common/_audio.js
Only the "url:" scheme is supported for video playback (i.e., video files stored on a web server).
Supporting video playback from game.zip entries is probably possible by:
1. reading the whole file in memory using FS.readFile()
2. wrapping the result in a Blob
3. create an URL for it using URL.createObjectURL()
4. using that url as if we extracted it from a "url:" scheme.
But storing videos in game.zip is probably a bad practice because of the files size and the need to read the whole file in memory before being able to play it, so do we really want to support that anyway?
> Raise an error when playing a video stored in game.zip

- renpy/lexer.py
Script files are read in universal newlines mode to better leverage various built-in Python code processing features such as linecache, and significantly simplify our line handling during lex/parsing.
This is great for script processing, but less ideal for script editing, where collapsed CRLFs can introduce problems with line start and end offsets. To compensate for this, when populating scriptedit.lines we now read the raw file and, when necessary, accumulate the drift caused by CR characters before using it to adjust the start and end offsets.
Fixes #6364.
> Compensate for carriage return in scriptedit

- renpy/common/00compat.rpy
- renpy/config.py
- renpy/display/tts.py
ab09cd29f0797d20c3b286974888039357223e48 (8.2.2) introduced a queue for TTS texts. While this is the ideal way to handle TTS text going forward, some older games (8.0.x) have layouts which cause problems with how TTS texts get queued - f.e. texts which get queued before a screen transition and are no longer displayed but still read.
This PR adds a config flag that gets disabled for games <= 8.2.1 to fix this, and to allow developers to use the old TTS behavior if they so desire for whatever reason - f.e. because fixing their layouts shortly before release while staying on a newer RenPy version isn't as feasible.
> tts: Allow disabling queueing via config + compat

- renpy/display/focus.py
As hinted at by #6441, `old_max_default_focus_name` was never updated, causing spontaneous questionable focus switches and even blocking navigation in some scenarios. This has been effectively broken since 8.2.1 (cf3163d37be3e77ebd5e639cfaced27d78f5e7ed, the very change which introduced this).
This commit sets `old_max_default_focus_name` the same way `old_max_default` is being set.
A member of my team (thank you, Liwia!) has prepared a repro by changing The Question to match our broken scenario:
- Enable self-voicing,
- start a new game,
- and using the keyboard only, proceed to the first list of choices.
- Then try to navigate to the quick menu by pressing left / up.
With 8.2.0 or older, the player can navigate just fine.  
With cf3163d37be3e77ebd5e639cfaced27d78f5e7ed (8.2.1), the …
> focus: Fix focus being stolen by same old "new" max default focus

- renpy/compat/pickle.py
- renpy/loadsave.py
- renpy/persistent.py
- renpy/script.py
This PR makes following changes:
1. Fixes the issue with `find_bad_reduce` reporting modules as being source of error when actual source is something unpickable at different path.
2. Adds checks for keys of mappings.
3. Adds check for `(slots, state)` case in `__reduce__`.
5. Adds error message as exception note instead of mutating args.
6. Adds bad reduction check for persistent and multipersistent pickle and deepcopy.
7. Adds bad reduction check for script AST pickle.
8. Applies [pickletools.optimize](https://docs.python.org/3/library/pickletools.html#pickletools.optimize) for rpyc data, saving ~15000 bytes to write and marginally speeds up reading of rpyc.
> Use `find_bad_reduction` in more places.

- renpy/ast.py
- renpy/statements.py
1. Store `init_priority` of the statement in registry instead of node itself, so changing it does not require recompilation.
2. If statement does not need to run its `execute_init`, do not include it into initlist.
> Several fixes for CDS init logic.

- renpy/ast.py
- renpy/statements.py
With this fix, UserStatement nodes parsed before 8.4 would call its init code with whatever priority was set on the node, and nodes parsed before 8.1 would call it with priority 0.
> Fix regression with init_priority of UserStatement parsed before 8.4

- renpy/common/00gui.rpy
Fixes #6491
Previously used a no-op `change_language` to rebuild styles. This is no longer reliable as rebuilds are now only done when the language changes. Resolve this by using the style rebuild function directly.
> Ensure styles are rebuilt in gui.SetPreference

- launcher/game/front_page.rpy
Removes the superfluous secondary "Projects" header, and as a side effects gives more space to the projects list.
`                     before                      ` | `                       after                     `
-|-
Had a quick look to make sure it doesn't end up weird when folders are used, and it looks fine since top-level projects are always listed first.
> Remove duplicated header in launcher

- renpy/common/00gui.rpy
Second attempt at a fix for #6491, properly tested in more than the most basic of setups this time. Very embarrassing. 😓
Effectively replicates the style processing in change_language but without the safe guards and resets necessary when changing language.
> Ensure deferred styles are applied in gui.rebuild

- renpy/gl2/gl2uniform.pyx
Fixes #6501.
Assumes that `u_lod_bias` is intended to be creator manageable (based on its absence from [`standard_uniforms`](https://github.com/renpy/renpy/blob/ec00ca208f8c2d7915ddcc2da91b3c235e10dde3/renpy/gl2/gl2draw.pyx#L1790-L1791)). If that assumption is invalid then a custom shader for use solely with the `pixelate` transition could be created using a differently named uniform to ameliorate 6501, as that transition is the only use in Ren'Py proper which requires this uniform be overridden.
This change prefers a `u_lod_bias` value set by `add_uniform`, but will fall back to the global default if none is provided.
> Use LOD bias uniform when provided

- renpy/gl2/gl2texture.pyx
Untested, speculative fix for #6499.
Reasoning is that this appears to be the only path whereby `self.properties` will not have the `mipmap` key set explicitly, and the code path conditional and comment (shown below) lines up with the report stating that it occurred while attempting to play movies in the web build:
https://github.com/renpy/renpy/blob/54485f25271b321093370db2c8d55234c9dfb050/renpy/gl2/gl2texture.pyx#L303-L304
<br/>I don't love the empty literal dict pass and resulting no-op lookup, but it seemed like the lesser evil given that `should_have_mipmaps` has the centralised logic to not only pull the `config` but also resolve `"auto"`.
> Ensure mipmap property gets set for videos on web

- renpy/common/_audio.js
When the game has just been loaded, the audio context is suspended by Web browsers until the user interacts with the game. Trying to resume the context before this interaction triggers a warning message in the console on Chrome (at least) for every single attempt. Because queue_depth() is called very frequently, this warning message appears a lot in the console which makes it crash on Chrome (it closes automatically). That's really annoying, especially when trying to debug something that happens soon after the game has loaded.
The message from 5db965a7093333a5ae0ea4e434af908483a801c4 indicates the intent is to resume the context if it has been interrupted by Safari on iOS. In this case, the context state will be set to "interrupted", so better use that to check if it needs to be resumed …
> Only try to resume audio context if interrupted (fix devtools crash)

- renpy/add_from.py
- renpy/lexer.py
Reverts the original solution to #6364 (#6399, which caused #6503) in favour of a much simpler solution now that the issue is better understood.
Problem:
- The `add_from` feature was accessing script files in binary mode and manually decoding, allowing it to see `\r` characters.
- The original fix was to adjust offsets for `\r` characters when creating data for use with `scriptedit`, data `add_from` needed.
- That in turn caused 6503, as `scriptedit` proper expects to operate with `\r` characters abstracted away.
- The mismatch between `scriptedit` and `add_from` meant that fixing one always broke the other.
Solution:
- Pull out the original fix which mangled character offsets, leave it `\r`-agnostic.
- This fixes 6503, allowing `scriptedit` to once again function normally.
- Change …
> Fix scriptedit line metadata

- renpy/display/layout.py
Fixes #6534.
This is a very basic fix. I don't know it this path would benefit from either of the following:
- ~~A short circuit to return `self` if `not self.children`.~~
- Combining
https://github.com/renpy/renpy/blob/99456f2f26e89799e86eaf93796bf9403e7e5562/renpy/display/layout.py#L678-L679
into
```py
if self.layer_name is not None and self.scene_list is not None:
```
such that it can fallback to the else clause (passing `elif self.layers`) which already does the right thing:
https://github.com/renpy/renpy/blob/99456f2f26e89799e86eaf93796bf9403e7e5562/renpy/display/layout.py#L731-L732
<br/>Also checked other instances of `return self` and all appear to correctly check for changes beforehand.
> Ensure _in_current_store call in transformed layer

- sphinx/source/python.rst
`exec.py` has been removed from the core since commit acba6a2 a year ago.  
It's however still referenced in the docs, in the Python statements page:
This commit removes any reference to `exec.py` so that the docs are up-to-date also.
> Remove any references to deprecated file exec.py from the docs

- renpy/text/font.py
Fixes #5830.
Signature of the glyphs function changed in May but was missed in the ImageFont implementation.
> Fix internal image font API

- gui/game/testcases.rpy
- renpy/test/testast.py
- renpy/test/testexecution.py
- renpy/test/testparser.py
- sphinx/source/testcases.rst
- testcases/game/tests/global.rpy
- testcases/game/tests/test_game_flow.rpy
- testcases/game/tests/test_testcase.rpy
- the_question/game/testcases.rpy
- tutorial/game/testcases.rpy
As per #6644, this PR:
- Modifies the screen selector so it takes a quoted screen name
- Bug fixed: If you use `exit`, the case/hook is correctly marked as run
I also want to confirm that gl_vsync works now
> Testcase patch 1

- sphinx/source/screens.rst
Additional a bit of clarification about the specific circumstances the events trigger, as described in #6646, explanation courtesy of @juniorthejunior.
> Add info about events for the 'on' screen statement.
