renpy/renpy

- launcher/game/tl/japanese/android.rpy
- launcher/game/tl/japanese/choose_directory.rpy
- launcher/game/tl/japanese/common.rpy
- launcher/game/tl/japanese/front_page.rpy
- launcher/game/tl/japanese/ios.rpy
- templates/japanese/game/tl/None/common.rpy
- tutorial/game/tl/japanese/common.rpy
> Update japanese template

- launcher/game/preferences.rpy
Change "Show edit buttons" string to "Show edit file section".
> Replace "Show edit buttons" string.

- README.rst
> Fix typo (missing end quote)

- launcher/game/tl/japanese/common.rpy
- launcher/game/tl/japanese/distribute_gui.rpy
- launcher/game/tl/japanese/preferences.rpy
- templates/japanese/game/tl/None/common.rpy
I updated translations for Japanese.
> update translation for japanese

- templates/italian/game/tl/None/common.rpy
Update Italian template thanks to LSF user Corvo.
> Update Italian template (by Corvo)

- launcher/game/tl/korean/ios.rpy
This adds new Korean translations for an iOS support screen.
> Add Korean translation for ios screen

- renpy/common/00action_file.rpy
FileSave/Load have some useful arguments, this
allows to use them throw generic FileAction
> Pass arguments from FileAction to FileSave/Load

- launcher/game/android.rpy
It would be more user friendly to copy Android distribution files to the same directory, where other distributions are.
This is my first attempt to do so. I'm still finding my way around the Launcher, so let me know if I should change something or if you have some questions.
> Copy Android distributions to distributions directory.

- launcher/game/tl/korean/android.rpy
- launcher/game/tl/korean/choose_directory.rpy
- launcher/game/tl/korean/choose_theme.rpy
- launcher/game/tl/korean/common.rpy
- launcher/game/tl/korean/distribute_gui.rpy
- launcher/game/tl/korean/editor.rpy
- launcher/game/tl/korean/front_page.rpy
- launcher/game/tl/korean/ios.rpy
- launcher/game/tl/korean/new_project.rpy
- launcher/game/tl/korean/preferences.rpy
- launcher/game/tl/korean/project.rpy
- launcher/game/tl/korean/translations.rpy
- launcher/game/tl/korean/updater.rpy
Add some missing translations and correct typos.
> Update Korean translations

- renpy/styledata/styleutil.py
focus_mask tried to use callable as displayable.
> Fix callables in focus_mask.

- tutorial/game/screens.rpy
- tutorial/game/tl/korean/Naver Nanum Font License.txt
- tutorial/game/tl/korean/common.rpy
- tutorial/game/tl/korean/demo_character.rpy
- tutorial/game/tl/korean/demo_dynamic.rpy
- tutorial/game/tl/korean/demo_imageops.rpy
- tutorial/game/tl/korean/demo_layers.rpy
- tutorial/game/tl/korean/demo_minigame.rpy
- tutorial/game/tl/korean/demo_nvlmode.rpy
- tutorial/game/tl/korean/demo_persistent.rpy
- tutorial/game/tl/korean/demo_text.rpy
- tutorial/game/tl/korean/demo_transform.rpy
- tutorial/game/tl/korean/demo_transitions.txt.rpy
- tutorial/game/tl/korean/demo_ui.txt.rpy
- tutorial/game/tl/korean/screens.rpy
- tutorial/game/tl/korean/script.rpy
- tutorial/game/tl/korean/style.rpy
- tutorial/game/tl/korean/tutorial_atl.rpy
- tutorial/game/tl/korean/tutorial_playing.rpy
- tutorial/game/tl/korean/tutorial_quickstart.rpy
- tutorial/game/tl/korean/tutorial_sprite.rpy
- tutorial/game/tl/korean/tutorial_video.rpy
Added Korean translation for tutorial game.
...I think every sentence makes sense. I guess...
> added korean translation for tutorial

- launcher/game/tl/finnish/android.rpy
- launcher/game/tl/finnish/choose_directory.rpy
- launcher/game/tl/finnish/choose_theme.rpy
- launcher/game/tl/finnish/common.rpy
- launcher/game/tl/finnish/distribute.rpy
- launcher/game/tl/finnish/distribute_gui.rpy
- launcher/game/tl/finnish/front_page.rpy
- launcher/game/tl/finnish/interface.rpy
- launcher/game/tl/finnish/ios.rpy
- launcher/game/tl/finnish/preferences.rpy
- launcher/game/tl/finnish/updater.rpy
I have updated the Finnish translation to the most recent version of
Ren'Py. Or, at least I sincerely hope so... things didn't go well last time.
> Updated the Finnish translation

- launcher/game/translations.rpy
- renpy/translation.py
It now offers the option to strip tags or not (instead of that being the default), escape special characters, and export translatable strings in addition to the dialogue.
As a side note, because this is code I've written for a MangaGamer project, I'd appreciate it if you could credit them alongside me wherever you credit contributors, should you choose to accept this.
> Improvements to the extract dialogue system.

- renpy/common/00defaults.rpy
- sphinx/source/config.rst
I would like to have something like this, not sure if the "set_volume" code syntax is correct ;)
> Configuration variables for audio volumes

- renpy/common/00action_other.rpy
- renpy/common/00layout.rpy
- sphinx/source/inc/replay
An option to confirm the EndReplay(), I edit the "sphinx/source/inc/replay" cause I didn't know how
it get automatically generated.
> Confirm EndReplay()

- renpy/display/dragdrop.py
Passing a delay argument to Drag.snap() doesn't work, with the snap being instantaneous.  The cause of this seems to be the condition for deciding the snap is over: `if at >= (self.target_at - self.at)` , which is going to be true almost all the time.  So I changed it to what it looked like it should have been, `at >= self.target_at` .
That exposed another problem, which is that snap() doesn't account for the last render time stored in `self.at` being potentially out of date.  E.g., if the drag is moved and then held still without being dropped for 3 seconds, then dropped, any snap called in the drop handlers will see `self.at` as three seconds prior because there have been no calls to render() since the drag stopped moving.
So I added another property, `target_at_delay`, that tells the …
> Fixed Drag.snap() animation to use delay

- renpy/gl/gldraw.pyx
> Fix a minor typo succesful -> successful

- launcher/game/tl/finnish/about.rpy
- launcher/game/tl/finnish/add_file.rpy
- launcher/game/tl/finnish/android.rpy
- launcher/game/tl/finnish/choose_directory.rpy
- launcher/game/tl/finnish/choose_theme.rpy
- launcher/game/tl/finnish/common.rpy
- launcher/game/tl/finnish/distribute.rpy
- launcher/game/tl/finnish/distribute_gui.rpy
- launcher/game/tl/finnish/editor.rpy
- launcher/game/tl/finnish/front_page.rpy
- launcher/game/tl/finnish/interface.rpy
- launcher/game/tl/finnish/ios.rpy
- launcher/game/tl/finnish/mobilebuild.rpy
- launcher/game/tl/finnish/navigation.rpy
- launcher/game/tl/finnish/new_project.rpy
- launcher/game/tl/finnish/preferences.rpy
- launcher/game/tl/finnish/project.rpy
- launcher/game/tl/finnish/style.rpy
- launcher/game/tl/finnish/translations.rpy
- launcher/game/tl/finnish/updater.rpy
The translation has now been updated to reflect the changes made between the previous translation and Ren'Py version 6.99.10.1227. (Unfortunately I don't use development versions often.)
> Updated Finnish translation of Ren'Py

- templates/spanish/game/options.rpy
- templates/spanish/game/tl/None/common.rpy
- common.ryp: Added some new strings.
- options.rpy: deleted the config.developer = True line with its comments
> Update Spanish template translation

- launcher/game/tl/indonesian/script.rpy
As update 11.1626 launched translation was updated with 3 new files 
this is the 1st pull request out of 3 pull request.
next pull request will be options.rpy
and gui.rpy
> Pull request to add script.rpy to launcher\game\tl\indonesian

- launcher/game/tl/indonesian/options.rpy
As update 11.1626 launched translation was updated with 3 new files 
this is the 2nd pull request out of 3 pull request.
next pull request will be gui.rpy
> Pull request to add options.rpy to launcher\game\tl\indonesian

- tutorial/game/tl/indonesian/about.rpy
Adding tutorial\game\tl\indonesian\about.rpy
> adding tutorial\game\tl\indonesian\about.rpy

- tutorial/game/tl/indonesian/add_file.rpy
adding tutorial\game\tl\indonesian\add_file.rpy
> adding  tutorial\game\tl\indonesian\add_file.rpy

- tutorial/game/tl/indonesian/demo_dynamic.rpy
adding tutorial\game\tl\indonesian\demo_dynamic.rpy
> adding tutorial\game\tl\indonesian\demo_dynam~.rpy

- tutorial/game/tl/indonesian/demo_imageops.rpy
adding  tutorial\game\tl\indonesian\demo_imageops.rpy
> adding  tutorial\game\tl\indonesian\demo_imag~.rpy

- tutorial/game/tl/demo_minigame.rpy
adding tutorial\game\tl\indonesian\demo_minigame.rpy
> adding tutorial\game\tl\indonesian\demo_minig~.rpy

- tutorial/game/tl/indonesian/demo_nvlmode.rpy
adding  tutorial\game\tl\indonesian\demo_nvlmode.rpy
> adding  tutorial\game\tl\indonesian\demo_nvlm~.rpy

- tutorial/game/tl/indonesian/screens.rpy
adding  tutorial\game\tl\indonesian\screens.rpy
> adding  tutorial\game\tl\indonesian\screens.rpy

- tutorial/game/tl/indonesian/demo_transform.rpy
adding  tutorial\game\tl\indonesian\demo_transform.rpy
> adding  tutorial\game\tl\indonesian\demo_tran~.rpy

- tutorial/game/tl/indonesian/demo_persistent.rpy
adding  tutorial\game\tl\indonesian\demo_persistent.rpy.rpy
> adding  tutorial\game\tl\indonesian\demo_pers~.rpy

- tutorial/game/tl/indonesian/tutorial_video.rpy
adding tutorial\game\tl\indonesian\tutorial_video.rpy
> adding  tutorial\game\tl\indonesian\tutori~_v.rpy

- tutorial/game/tl/tutorial_sprite.rpy
adding  tutorial\game\tl\indonesian\tutorial_sprite.rpy
> adding  tutorial\game\tl\indonesian\tutorial_s~.rpy

- tutorial/game/screens.rpy
added textbutton "Indonesian" action Language("indonesian") on line 397
> On line 397@screens@tutorial add button to switch to indonesian lang

- tutorial/game/tl/indonesian/demo_layers.rpy
adding  tutorial\game\tl\indonesian\demo_layers.rpy
> adding  tutorial\game\tl\indonesian\demo_laye~.rpy

- launcher/game/tl/indonesian/gui.rpy
adding  tutorial\game\tl\indonesian\gui.rpy
> adding  tutorial\game\tl\indonesian\gui.rpy

- add.py
- distribute.py
- launcher/game/EasyDialogsWin.py
- launcher/game/change_icon.py
- launcher/game/pefile.py
- module/generate_linebreak.py
- module/setup.py
- module/setuplib.py
- renpy.py
- renpy/__init__.py
- renpy/audio/androidhw.py
- renpy/bootstrap.py
- renpy/display/core.py
- renpy/display/im.py
- renpy/display/screen.py
- renpy/easy.py
- renpy/error.py
- renpy/execution.py
- renpy/exports.py
- renpy/lint.py
- renpy/loader.py
- renpy/log.py
- renpy/main.py
- renpy/memory.py
- renpy/parser.py
- renpy/python.py
- renpy/script.py
- renpy/test/testfocus.py
Used py2to3 to convert everything.
Skipped the scripts and sphinx directories, wasn't sure if changing them was required for ren'py.
In launcher/game there were some files where it wasn't immediately clear if any of the code in there was from a 3rd party. I had to modify them to get renpy.exe to run.
Took the opportunity to run autopep8 with the following rules on the effected files:
E26  - Fix spacing after comment hash for inline comments.
E301 - Add missing blank line.
E302 - Add missing 2 blank lines.
E303 - Remove extra blank lines.
A very quick test had renpy running with all the changes, but it certainly needs to be heavily tested. If there's some test cases for features that use print, that would help.
> Replace print statement with print function

- renpy/character.py
- renpy/display/core.py
- renpy/parser.py
+ PEP8 style fixes while I'm in there.
+ Replaced instances of "if not x in y" with "if x not in y"
+ Replaced multiple "or" check with a "in list" check.
(set or tuple check could theoretically be faster, but for such a tiny collection, I doubt there's a huge difference.)
> Fix a few typos in docstrings

- launcher/game/tl/japanese/screens.rpy
> Update Japanese translation

- launcher/game/tl/spanish/gui.rpy
- launcher/game/tl/spanish/launcher.rpy
- launcher/game/tl/spanish/options.rpy
- launcher/game/tl/spanish/screens.rpy
> Update spanish translation

- renpy/common/00keymap.rpy
Simply bind 'a' to toggle afm ...
> toggle_afm

- launcher/game/tl/italian/common.rpy
- launcher/game/tl/italian/developer.rpy
- launcher/game/tl/italian/error.rpy
- launcher/game/tl/italian/gui.rpy
- launcher/game/tl/italian/launcher.rpy
- launcher/game/tl/italian/options.rpy
- launcher/game/tl/italian/screens.rpy
- launcher/game/tl/italian/script.rpym
Complete Italian translation of launcher and GUI.
All credits to Lemmasoft Forum member [gas](https://lemmasoft.renai.us/forums/memberlist.php?mode=viewprofile&u=2428)
> Update Italian translation (complete!)

- launcher/game/tl/russian/gui.rpy
- launcher/game/tl/russian/screens.rpy
Deletion of old strings and user-experienced improvements.
> Little improvements to russian translation.

- launcher/game/tl/arabic/gui.rpy
> Arabic translation for 6.99 gui.rpy

- launcher/game/tl/arabic/developer.rpy
> Arabic Translation for 6.99 developer.rpy

- launcher/game/tl/arabic/common.rpy
> Arabic translation for 6.99 common.rpy

- renpy/common/00voice.rpy
This "selected" option is a simple c&p from the Play() function. Lets say you wanna use PlayCharacterVoice() in your sound preferences screen or like in this example, in the history screen:
for h in _history_list:
button action If(h.voice.filename, true=PlayCharacterVoice(h.voice.tag, h.voice.filename), false=None):
selected (renpy.sound.get_playing(channel="voice") == h.voice.filename)
vbox:
xfill True
if h.who:
text h.who + '\n' + h.what
else:
text h.what
This doesn't update the button state properly( dunno if it's the fault because it's in a viewport) but if you scroll
the viewport during the playback the button state gets updated. Missing renpy.restart_interaction?
Anyway, Tom if you have a better solution feel free to change it ;)
> Add selected option to PlayCharacterVoice()

- launcher/game/tl/italian/screens.rpy
> Minor update Italian translation

- launcher/game/tl/russian/launcher.rpy
Temp post for making russian renpy uptodate =D
So, adding legacy options…
> Updating russian tl for new version

- tutorial_7/game/script.rpy
Hi! I just changed some links to use https to avoid automatic redirects. ^ _ ^
> Updated links to use https

- launcher/game/tl/french/common.rpy
- launcher/game/tl/french/developer.rpy
- launcher/game/tl/french/error.rpy
- launcher/game/tl/french/gui.rpy
- launcher/game/tl/french/launcher.rpy
- launcher/game/tl/french/options.rpy
- launcher/game/tl/french/screens.rpy
> French translation

- launcher/game/tl/russian/common.rpy
- launcher/game/tl/russian/developer.rpy
- launcher/game/tl/russian/error.rpy
- launcher/game/tl/russian/gui.rpy
- launcher/game/tl/russian/launcher.rpy
- launcher/game/tl/russian/screens.rpy
- tutorial/game/tl/russian/01example.rpy
- tutorial/game/tl/russian/common.rpy
- tutorial/game/tl/russian/indepth_character.rpy
- tutorial/game/tl/russian/indepth_minigame.rpy
- tutorial/game/tl/russian/indepth_style.rpy
- tutorial/game/tl/russian/indepth_text.rpy
- tutorial/game/tl/russian/indepth_transitions.rpy
- tutorial/game/tl/russian/screens.rpy
- tutorial/game/tl/russian/script.rpy
- tutorial/game/tl/russian/tutorial_atl.rpy
- tutorial/game/tl/russian/tutorial_director.rpy
- tutorial/game/tl/russian/tutorial_playing.rpy
- tutorial/game/tl/russian/tutorial_quickstart.rpy
- tutorial/game/tl/russian/tutorial_screen_displayables.rpy
- tutorial/game/tl/russian/tutorial_screens.rpy
Well, I found some more issues and sorting them:
I think, this is because of using variables and text tags.
- eslow "The nw tag causes Ren'Py to continue past slow text,{nw}" ### english example. next string is russian, lol
- e "To interpolate a variable, write it in square brackets. Isn't that right, [name]?" ### english example
- e "Variable interpolation also works with other variables. Here, the answer is [answer] and the flag is [flag]." ### example no translation
- old "The answer is [answer]." ### english example
- old "Text tags {color=#c8ffc8}work{/color} in screens." ### english example
- e "For example, we might want to have text that is {b}bold{/b}, {i}italic{/i}, {s}struckthrough{/s}, or {u}underlined{/u}." ### english example
- e "The a text tag …
> Updating russian translation and some more notes.

- gui/game/options.rpy
- sphinx/source/config.rst
> Add config.intra_transition to options.rpy and update docs

- launcher/game/tl/indonesian/common.rpy
> Updated Indonesian Translation common.rpy #13.2717

- launcher/game/tl/indonesian/error.rpy
> Updated Indonesian Translation error.rpy #13.2717

- launcher/game/tl/indonesian/gui.rpy
> Updated Indonesian Translation gui.rpy #13.2717

- launcher/game/tl/indonesian/launcher.rpy
> Updated Indonesian Translationlauncher.rpy#13.2717

- launcher/game/tl/indonesian/options.rpy
> Updated Indonesian Translationsoptions.rpy#13.2717

- launcher/game/tl/indonesian/screens.rpy
> Updated Indonesian Translation screens.rpy#13.2717

- launcher/game/gui7.rpy
- launcher/game/tl/russian/common.rpy
- launcher/game/tl/russian/gui.rpy
- launcher/game/tl/russian/launcher.rpy
- launcher/game/tl/russian/screens.rpy
Main feature: Custom resolution now translatable in launcher.
Other is just update.
> Translation update for custom resolution and russian

- launcher/game/tl/russian/common.rpy
- launcher/game/tl/russian/launcher.rpy
https://github.com/renpy/renpy/issues/1262
> Update russian launcher

- sphinx/source/other.rst
I have seen some newer visual novels break the 4th wall in interesting ways using these functions, but they aren't documented anywhere for a newer developer to find them.
> Add OS Functions to Other Functions docs

- launcher/game/tl/russian/gui.rpy
- launcher/game/tl/russian/options.rpy
- launcher/game/tl/russian/screens.rpy
More for developers than for players. 
- "user" changed to "player"
- some sentences have been rewritten for better understanding
> Minor russian stylistic update

- launcher/game/tl/russian/gui.rpy
https://github.com/renpy/renpy/issues/1262
> Let's translate gui.nvl_list_length to Russian

- the_question/game/screens.rpy
- the_question/game/script.rpy
- the_question/game/tl/russian/common.rpy
- the_question/game/tl/russian/options.rpy
- the_question/game/tl/russian/screens.rpy
- the_question/game/tl/russian/script.rpy
> Ria: So, in new The Question we learned that %Me% and Sylvie made that boy's love game first...
We're used in our translation russian old The Question (https://github.com/renpy/renpy/pull/1212)
Also, is the config.version (Ren'Py 7 Edition) shown by gui.show_name in Main menu not translatable at all?
> Russian The Question (Ren'Py 7 edition)

- launcher/game/tl/russian/common.rpy
- launcher/game/tl/russian/developer.rpy
- tutorial/game/tl/russian/tutorial_screens.rpy
- tutorial/game/tl/russian/tutorial_video.rpy
1. Obsolete strings  deleted
2. Some translation strings moved from common.rpy to developer.rpy
3. Some small fixes for tutorial
> Russian translation update

- renpy/common/_developer/developer.rpym
No need for comments. This must be added long ago. =D
> Image Location Picker must support .webp

- sphinx/source/screens.rst
> Fix typo in transclude docs

- sphinx/source/changelog.rst
`config.loadable` callback => `config.loadable_callback`
targer => target
> Fixes for changelog (doc)

- launcher/game/tl/russian/developer.rpy
> Russian 6.99.14.1

- launcher/game/editor.rpy
- launcher/game/tl/russian/launcher.rpy
- launcher/game/tl/russian/options.rpy
Also, 
1. Make "System Editor" and "None" translatable, so "create translations" make translations for them too.
2. Something with design. I will miss about big "Проверить сценарий (Lint)" in Russian at first line after "Navigate Script" that not so many people use T__T. New translation make it "Проверить скрипт (Lint)", so 2 "Actions" columns  more or less equal.
> Russian update 6.99.14.1 (2

- renpy/text/font.py
A `self.baseline` was already implemented for `ImageFont` and even loaded in `BMFont`, but never used.  Now it's used and exposed to `register_sfont`, which is useful for mixing an sfont with descenders with some other font.
Actual motivating example: I wanted to inject a few colorful custom glyphs, so I put them in a quick sfont and used it alongside my (truetype) dialogue font.  Unfortunately, they sit right on the baseline, which shoves the ascent higher and changes the height of the whole line:
I could shrink them a bit, of course, but they were really designed to fill the entire line height.  With this patch and `baseline=-2`:
> Allow specifying the baseline for an SFont

- launcher/game/tl/russian/launcher.rpy
- launcher/game/tl/russian/obsolete.rpy
Update for Atom, Editra and 'Open project'. Also, added some translations of obsoletes.
> Russian Update 6.99.14.2

- README.rst
I updated urls to use https when possible to avoid redirects.
> Updated URLs to use https when possible. (Readme file only)

- launcher/game/tl/russian/common.rpy
- launcher/game/tl/russian/developer.rpy
- launcher/game/tl/russian/error.rpy
- launcher/game/tl/russian/launcher.rpy
- launcher/game/tl/russian/screens.rpy
- the_question/game/tl/russian/common.rpy
- the_question/game/tl/russian/options.rpy
- the_question/game/tl/russian/screens.rpy
- the_question/game/tl/russian/script.rpy
- tutorial/game/tl/russian/01example.rpy
- tutorial/game/tl/russian/common.rpy
- tutorial/game/tl/russian/indepth_minigame.rpy
- tutorial/game/tl/russian/screens.rpy
- tutorial/game/tl/russian/script.rpy
That was hard, and I need to process translation one more time. Because I still catch some bugs...
1. TTS read slots with short month. Apr, but not April. Mar, but not March.
2. Extra space at the end of lines
00library.rpy:147
old "Clipboard voicing enabled. "
00library.rpy:148
old "Self-voicing enabled. "
3. Not a bug, but increase/decrease works also for scrollbars, so when we have to go down in viewport and we activate scrollbar and use arrow keys, TTS says "increase".
00library.rpy:157
old "increase"
00library.rpy:158
old "decrease"
4. After adding russian translation to Launcher and create new project, I have strange bug ():
> I'm sorry, but an uncaught exception occurred.
> 
> While running game code:
> Exception: DynamicImage [u'gui/button/navigation_[prefix_]background.png', …
> Russian TTS Update

- the_question/game/screens.rpy
- the_question/game/tl/french/common.rpy
- the_question/game/tl/french/options.rpy
- the_question/game/tl/french/screens.rpy
- the_question/game/tl/french/script.rpy
This is the french translation for "The Question".
Here is the result of lint process
```
Ren'Py 7.0.0.51 lint report, generated at: Wed May 02 09:23:28 2018
Statistics:
The game contains 70 dialogue blocks, containing 743 words and 3,919
characters, for an average of 10.6 words and 56 characters per block.
The french translation contains 70 dialogue blocks, containing 825 words and
4,625 characters, for an average of 11.8 words and 66 characters per block.
The russian translation contains 70 dialogue blocks, containing 668 words and
4,012 characters, for an average of 9.5 words and 57 characters per block.
The game contains 2 menus, 0 images, and 23 screens.
Lint is not a substitute for thorough testing. Remember to update Ren'Py
before releasing. New releases fix bugs and improve …
```
> French translation of "The Question" game.

- sphinx/source/config.rst
- sphinx/source/layeredimage.rst
This focuses on typo corrections to the Layered Images documentation.
> Documentation corrections

- tutorial/game/tl/french/common.rpy
- tutorial/game/tl/french/indepth_character.rpy
- tutorial/game/tl/french/indepth_displayables.rpy
- tutorial/game/tl/french/indepth_minigame.rpy
- tutorial/game/tl/french/indepth_style.rpy
- tutorial/game/tl/french/indepth_text.rpy
- tutorial/game/tl/french/indepth_transitions.rpy
- tutorial/game/tl/french/indepth_translations.rpy
- tutorial/game/tl/french/script.rpy
- tutorial/game/tl/french/tutorial_atl.rpy
- tutorial/game/tl/french/tutorial_distribute.rpy
- tutorial/game/tl/french/tutorial_nvlmode.rpy
- tutorial/game/tl/french/tutorial_playing.rpy
- tutorial/game/tl/french/tutorial_quickstart.rpy
- tutorial/game/tl/french/tutorial_screen_displayables.rpy
- tutorial/game/tl/french/tutorial_screens.rpy
Grammar and typo corrections in the french version of the tutorial
> Grammar and typo corrections (french)

- launcher/game/tl/french/common.rpy
- launcher/game/tl/french/error.rpy
- launcher/game/tl/french/launcher.rpy
- launcher/game/tl/french/options.rpy
- launcher/game/tl/french/screens.rpy
- launcher/game/tl/french/script.rpym
- the_question/game/tl/french/common.rpy
- the_question/game/tl/french/options.rpy
- the_question/game/tl/french/script.rpy
- tutorial/game/tl/french/common.rpy
This adds grammar and typo corrections in the french translations of "the question" and the launcher itself :)
> More french typo/grammar fixes

- TRANSLATORS.rst
- launcher/game/tl/malay/common.rpy
- launcher/game/tl/malay/developer.rpy
- launcher/game/tl/malay/error.rpy
- launcher/game/tl/malay/gui.rpy
- launcher/game/tl/malay/launcher.rpy
- launcher/game/tl/malay/options.rpy
- launcher/game/tl/malay/screens.rpy
- launcher/game/tl/malay/script.rpym
- launcher/game/tl/malay/style.rpy
- the_question/game/screens.rpy
- the_question/game/tl/malay/common.rpy
- the_question/game/tl/malay/options.rpy
- the_question/game/tl/malay/screens.rpy
- the_question/game/tl/malay/script.rpy
**This is part 1 of 4 Malay translation works.**
Part 1 and 2 involves translating to Malay in Latin-based Rumi script whereas part 3 and 4 involves translating to Malay in Arabic-based Jawi script.
- Add Malay to TRANSLATORS.rst
- Translate Ren'Py Launcher to Malay (Rumi)
- Translate The Question to Malay (Rumi)
- Translate Tutorial to Malay (Rumi)
- Translate Ren'Py Launcher to Malay (Jawi)
- Translate The Question to Malay (Jawi)
- Translate Tutorial to Malay (Jawi)
I originally thought of making all of them ready and create single pull request, but the fact that the Tutorial is so big made me split this to 4 parts. The other parts will be in their own separate pull requests once they're ready. I'll also work on the documentation translations after I complete these 4 parts translation.
> Add Malay translation (part 1)

- module/generate_styles.py
- renpy/common/00style.rpy
- renpy/common/_errorhandling.rpym
- renpy/display/layout.py
- renpy/screenlang.py
- renpy/sl2/slproperties.py
> Added new box_wrap_spacing style property

- launcher/game/tl/korean/common.rpy
- launcher/game/tl/korean/screens.rpy
Old translations are missing a bunch of new content around the new GUI.
> Update Korean translations for Ren'py 7

- launcher/game/tl/german/launcher.rpy
I noticed that a few strings are not translated to German, especially in the main launcher menu screens, so I added those that I found.
I also replaced the ellipsis characters with three regular dots as in the original english strings.
I'm a native German speaker, so I think this should be good enough :)
> translation: Translated more strings to German, fixed ellipses.

- launcher/game/tl/french/screens.rpy
- tutorial/game/tl/french/screens.rpy
replicated from 53261a7a5241caa0a188ed29a6ff4aaf0dbea20d
> Fixes to French translation

- tutorial/game/indepth_character.rpy
- tutorial/game/tl/french/indepth_character.rpy
- tutorial/game/tl/piglatin/indepth_character.rpy
- tutorial/game/tl/russian/indepth_character.rpy
Fixed the same typo in all 4 commits.
> Fixed some typos

- renpy/audio/audio.py
> audio: fix deadlock on quit

- sphinx/source/displaying_images.rst
Use the newer (documented) function name
> doc fix: layer_at_list -> show_layer_at

- sphinx/source/gui.rst
gui.font_size -> gui.text_size
> Doc fix: gui.font_size -> gui.text_size

- launcher/game/pefile.py
changed to return False
found by https://lgtm.com/projects/g/renpy/renpy/
> fix an illegal raise False

- renpy/python.py
Reduce copies of the game store
> GC optimizations

- renpy/__init__.py
- renpy/config.py
- sphinx/source/config.rst
Fixes https://github.com/renpy/renpy/issues/1800
> Python module reloading support

- renpy/common/00compat.rpy
- renpy/config.py
- renpy/display/layout.py
- renpy/parser.py
- sphinx/source/config.rst
- sphinx/source/screens.rst
> Side render order

- launcher/game/tl/spanish/common.rpy
- launcher/game/tl/spanish/launcher.rpy
> Spanish translation update

- TRANSLATORS.rst
- launcher/game/tl/turkish/common.rpy
- launcher/game/tl/turkish/developer.rpy
- launcher/game/tl/turkish/error.rpy
- launcher/game/tl/turkish/gui.rpy
- launcher/game/tl/turkish/launcher.rpy
- launcher/game/tl/turkish/options.rpy
- launcher/game/tl/turkish/screens.rpy
- launcher/game/tl/turkish/script.rpym
The Turkish localisation strings of the launcher project.
> Turkish translation

- renpy/text/extras.py
Small fix for 9a30c95011af6d1d7ed6c3fef5696acb74643fff
> Added self closing custom_tags to check_text_tags

- renpy/display/screen.py
> Use scope when evalling screen sensitivity

- launcher/game/tl/korean/common.rpy
- launcher/game/tl/korean/launcher.rpy
- the_question/game/tl/korean/common.rpy
- tutorial/game/tl/korean/common.rpy
> Update Korean strings.

- renpy/common/00barvalues.rpy
- renpy/display/behavior.py
- renpy/display/viewport.py
- renpy/ui.py
- sphinx/source/screen_actions.rst
- sphinx/source/screen_python.rst
A test script that demonstrates the changes
[script.zip](https://github.com/renpy/renpy/files/3469953/script.zip)
> Adjustment force_step

- renpy/display/behavior.py
- renpy/exports.py
- sphinx/source/preferences.rst
> Doc afm enabled

- renpy/audio/audio.py
- renpy/common/00action_data.rpy
call queue_empty_callback only if the queue is really empty
> fixed sound-queue call_back

- renpy/loadsave.py
On some platforms, the amount of thread resources are limited.
To avoid reaching the limit quickly, join the previous autosave thread before spawning a new one.
> Join previous autosave thread before spawning a new one

- renpy/common/00preferences.rpy
Preference("font vertical spacing") --> Preference("font line spacing")
> Correct preference 'font vertical spacing' to 'font line spacing'

- sphinx/source/config.rst
- sphinx/source/displayables.rst
A few typos found in these two files while on the documentation site.
> Some typo fixes on config.rst and displayables.rst

- renpy/display/dragdrop.py
> Set the style prefix for dragged set even after update screen

- renpy/display/image.py
Some fixes for 82caa0a66abf20818931e399711a2f7fae45fc1f
> Fix dynamic image

- launcher/game/change_icon.py
- launcher/game/pefile.py
- module/generate_linebreak.py
- module/setuplib.py
- renpy/bootstrap.py
- renpy/dump.py
- renpy/error.py
- renpy/loader.py
- renpy/persistent.py
- renpy/script.py
- renpy/text/font.py
- sphinx/game/doc.py
file() doesn't exist anymore in Py3.
> [Py3] Use open() instead of file()

- renpy/common/_errorhandling.rpym
> Wrap actions box on overlap in exception screen.

- renpy/curry.py
This may have backward compatibility problem. But I don't see a way to solve it.
> Curry name

- the_question/game/screens.rpy
- the_question/game/tl/japanese/common.rpy
- the_question/game/tl/japanese/options.rpy
- the_question/game/tl/japanese/screens.rpy
- the_question/game/tl/japanese/script.rpy
I added the_question Japanese translation.
> added the_question japanese translation

- sphinx/source/quickstart.rst
> Fix doc typo

- renpy/common/00console.rpy
> Console prettyprint

- module/ffmedia.c
- module/renpysound_core.c
Prevents data aborts on memory allocation error and media open error
> More pointer validation in ffmedia and renpysound_core

- tutorial/game/tl/korean/tutorial_quickstart.rpy
> Update tutorial Ko-tl

- renpy/common/_shaders.rpym
> Fix int-float type in blur shader

- renpy/gl/gldraw.pyx
- renpy/gl2/gl2draw.pyx
> Py3 exceptions form

- renpy/common/00gltest.rpy
- sphinx/source/config.rst
It turns out that this has nothing to do with *performance* now, but the names are still old. Perhaps it makes sense to update it.
> Update performance test

- renpy/common/00start.rpy
Faster, technically, but I think this makes it easier to read
> Use or operator instead of if statement

- renpy/atl.py
- sphinx/source/atl.rst
- sphinx/source/custom_text_tags.rst
Very basic (static elasticity) Catmull-Rom implementation to work with knots in ATL. Slight tweak to allow a knot to be a tuple of tuples and minor documentation changes.
> Catmull-Rom from ATL knots

- renpy/display/presplash.py
Recently I was toying around with adding a presplash screen to a game I'm involved in because it's gotten quite large and takes a while to start up on older computers.
I experimented a bit and eventually implemented what's in this pull request, which is a way of defining a themable progress bar as the presplash which shows the actual progress towards main window creation.
A presplash is a great way of showing that the game has actually launched before the main window appears (which happens between 5 and 30 seconds after launching our game based on user reports). However, I found a static image quite uninspiring. Generally it is often times helpful to visually convey to the user that actual work is being done, hence this proposal. It also helps with estimating startup duration on the …
> Add ability to show progress bar instead of static presplash

- renpy/display/behavior.py
> Encode and decode the text during copypaste

- renpy/sl2/slast.py
> Fix the problem when SL for index refers to tuple member

- renpy/audio/androidhw.py
- renpy/audio/ioshw.py
- renpy/common/000statements.rpy
- renpy/common/00compat.rpy
- renpy/common/00updater.rpy
- renpy/common/00voice.rpy
- renpy/common/_developer/developer.rpym
- renpy/display/controller.py
- renpy/display/core.py
- renpy/display/im.py
- renpy/error.py
- renpy/gl2/gl2shadercache.py
- renpy/gl2/live2d.py
- renpy/gl2/live2dmodel.pyx
- renpy/gl2/live2dmotion.py
- renpy/loader.py
- renpy/loadsave.py
- renpy/main.py
- renpy/parser.py
- renpy/pyanalysis.py
- renpy/savelocation.py
- renpy/script.py
- renpy/sl2/slast.py
- renpy/text/font.py
- renpy/translation/__init__.py
Use the `with` statement to ensure that file or file-like objects get closed when out of scope. This ensures that files get closed when the block is out of scope or when an exception occurs.
> Refactor to use context manager

- renpy/gl2/live2d.py
1. Since it makes no sense for a motion and expression to have the same name, raise an error pointing out the problem.
2. Prohibit the accidental overwriting with an alias of an other existing motion or expression.
3. If the setting of an alias or a nonexclusive expression refers to a non-existent value, raise an error pointing out the problem.
4. Set nonexclusive expressions before aliases, so then the value of original expression does not remain as an possible expression.
> Fixes for Live2D

- sphinx/source/achievement.rst
Fixes broken style for achievement.steam_position at https://www.renpy.org/doc/html/achievement.html
> Fix variable formatting in achievement.rst

- renpy/ast.py
Hope I got the object types correct.
> Fix incorrect docstring for Screen class in ast.py

- module/ffmedia.c
- renpy/config.py
- renpy/display/layout.py
- renpy/sl2/sldisplayables.py
- sphinx/source/config.rst
> Allow underfull grids

- sphinx/source/live2d.rst
Parameter name was slightly wrong
> Correct Live2D aliases example

- the_question/game/tl/japanese/common.rpy
- the_question/game/tl/japanese/screens.rpy
- tutorial/game/tl/japanese/common.rpy
- tutorial/game/tl/japanese/indepth_style.rpy
- tutorial/game/tl/japanese/screens.rpy
> Update Japanese translations

- renpy/common/00layeredimage.rpy
- renpy/common/00placeholder.rpy
- sphinx/source/conditional.rst
- sphinx/source/text.rst
- sphinx/source/translation.rst
Another version of #2507 without the messy merge commit and the matrixcolor fix
> Random fixes in the doc - 2

- launcher/game/tl/japanese/launcher.rpy
Fixed Japanese translation in lancher
> Japanese_update

- launcher/game/tl/korean/launcher.rpy
> Update Korean strings

- tutorial/game/tutorial_quickstart.rpy
I'm a new Ren'Py user and thought I'd see if this suggestion might help make the documentation a bit clearer.
I'd be happy to update this PR with translations if my suggestion is helpful.
> Update show statement documentation

- renpy/color.py
- renpy/common/00matrixcolor.rpy
Add attribute _rgba and property rgba to Color class and update TintMatrix to use that property
> Add rgba property to Color

- renpy/text/ftfont.pyx
This will only be effective when the Python enviroment was built with UCS-2 unicode type (e.g. official Ren'Py binary distribution). Once triggered, it will decode the surrogate pair to an FT_ULong before passing it to the glyph lookup routine in FreeType. Variation sequences are also handled when needed (i.e. `<upper surrogate> <lower surrogate> <variation>`).
Closes #2642
---
Currently not tested because lack of UCS-2 Python environment. Doesn't seem to have regressions when ran on UCS-4 Python.
> Implement surrogate pair decoding.

- renpy/text/font.py
> Add character remapping to FontGroup

- launcher/game/tl/french/common.rpy
As pointed out in #2695, plus fixing an inconsistency
> Harmonizing and correcting french translation

- renpy/common/00achievement.rpy
Added the `register` method, so the `stat_max` value is given.
Added achievement granting when the progress reaches the `stat_max` value.
> Improvements to default achievement backend

- renpy/gl2/live2dmotion.py
This is one of the fixes of #2717 that was recently reverted.
> Add implicit Step with last reached value till the end of the motion

- renpy/memory.py
The current set of such containers includes: defined images, defined screens, several caches and Script instance.
This is disabled by default, so it is backwards compatible.
> Add `skip_constants` keyword for memory profile functions

- sphinx/source/display_problems.rst
> Fix problems.rst problem

- renpy/main.py
It makes possible to put rpa archives in Android overwrite folder
> Search archives in all searchpaths, not just gamedir

- renpy/lint.py
Title pretty much says it all. 🙂
> Ensure lint checks temporary say attributes

- .gitignore
- launcher/game/tl/schinese/launcher.rpy
update launcher.rpy Chinese translate file
> update Chinese translator file

- renpy/parser.py
This allow to write
```renpy
menu:
who "What" nointeract id i_have_an_id
"Caption":
pass
```
> Allow additional say clauses in menu say statement

- renpy/display/transition.py
> Reflect color's keyword-only behavior in Fade

- renpy/arguments.py
- renpy/ast.py
- renpy/audio/audio.py
- renpy/character.py
- renpy/compat/__init__.py
- renpy/display/behavior.py
- renpy/display/core.py
- renpy/display/focus.py
- renpy/display/im.py
- renpy/display/image.py
- renpy/display/pgrender.py
- renpy/display/presplash.py
- renpy/display/video.py
- renpy/easy.py
- renpy/lint.py
- renpy/loader.py
- renpy/minstore.py
- renpy/persistent.py
- renpy/python.py
- renpy/screenlang.py
- renpy/script.py
- renpy/translation/__init__.py
- renpy/translation/extract.py
- renpy/webloader.py
See commit comments for more specific details.
The json.load matter may be more problematic than the others, since the `encoding` (kw)arg is not explicitely documented anymore.
> Some pylint and py3 preparation

- renpy/common/00layeredimage.rpy
> Use At instead of transforms' `__call__`

- renpy/lint.py
> Add character stats in lint

- renpy/common/00console.rpy
- sphinx/game/script.rpy
- sphinx/source/developer_tools.rst
I added doc console command helps
> add doc cosole commands

- renpy/exports.py
- renpy/parser.py
- sphinx/source/config.rst
- sphinx/source/keymap.rst
> Update Ren'Py parameters and arguments parser to match python 3

- launcher/game/install.rpy
> Update Live2D libraries install directories #3363

- renpy/common/00action_control.rpy
What about adding an easier way to hide current screen? This is really efficient for projects that use a lot of them.
> Hide current screen

- renpy/display/transform.py
- renpy/sl2/sldisplayables.py
> Allow to set alt text for displayable and add it to SL2 add statement

- launcher/game/translations.rpy
- renpy/translation/dialogue.py
This make lancher extract dialogue in preferences.language in that game
#1992
> extract dialogue in preferences.language in that game

- launcher/game/distribute.rpy
- launcher/game/distribute_gui.rpy
> Add command line and GUI command to backup rpyc files in old-game

- renpy/common/00compat.rpy
- renpy/common/00layeredimage.rpy
- renpy/config.py
- sphinx/source/config.rst
- sphinx/source/incompatible.rst
- sphinx/source/layeredimage.rst
follows c98ab1a06da930ad60a09fe589824165c5900931
> Compat offer_screen and integrate it in layeredimage

- sphinx/source/style_properties.rst
That is, when offer_screen isn't a thing.
> Document how the fixed properties work

- renpy/revertable.py
> Save more fields for more mutator functions

- renpy/common/00keymap.rpy
- testcases/game/mygallery.rpy
- testcases/game/screens.rpy
Support web-based help URLs
Wire up Help, Navigation buttons in testcases
> 00keymap, Testcases project enhancements

- renpy/atl.py
Fix for #3439 via small targeted reversion of #3370.
> Restore positional parameter info

- sphinx/source/atl.rst
> Document #2462

- renpy/preferences.py
- sphinx/source/preferences.rst
Which I believe was the intent of this comment: <https://github.com/renpy/renpy/issues/2645#issuecomment-1073146049>.
> Make disabling sound on minimise opt-in

- launcher/game/android.rpy
- launcher/game/distribute.rpy
- launcher/game/front_page.rpy
- launcher/game/mobilebuild.rpy
- launcher/game/web.rpy
- renpy/common/00action_other.rpy
> Make OpenDirectory public and compat it in launcher

- sphinx/source/text.rst
Sources : https://www.renpy.org/doc/html/language_basics.html#elements-of-statements and https://www.renpy.org/dev-doc/html/incompatible.html#incompatible-6-13
> Add % to protectable characters

- renpy/common/00audio.rpy
FLAC is supported, this allows flac files to be automatically defined.
> Add FLAC support  to _scan_audio_directory()

- renpy/display/transform.py
> Fix an incorrect child assignment in transforms.

- launcher/game/new_project.rpy
- launcher/game/preferences.rpy
- launcher/game/tl/arabic/launcher.rpy
- launcher/game/tl/finnish/launcher.rpy
- launcher/game/tl/french/launcher.rpy
- launcher/game/tl/german/launcher.rpy
- launcher/game/tl/greek/launcher.rpy
- launcher/game/tl/indonesian/launcher.rpy
- launcher/game/tl/italian/launcher.rpy
- launcher/game/tl/japanese/launcher.rpy
- launcher/game/tl/korean/launcher.rpy
- launcher/game/tl/malay/launcher.rpy
- launcher/game/tl/piglatin/launcher.rpy
- launcher/game/tl/polish/launcher.rpy
- launcher/game/tl/portuguese/new_project.rpy
- launcher/game/tl/russian/launcher.rpy
- launcher/game/tl/schinese/launcher.rpy
- launcher/game/tl/spanish/launcher.rpy
- launcher/game/tl/tchinese/launcher.rpy
- launcher/game/tl/turkish/launcher.rpy
- launcher/game/tl/vietnamese/launcher.rpy
> Translate language names in their specific languages in the launcher

- renpy/rollback.py
Attempt to take and run with the ideas from a851baff1b45eee94f2ca47e399fcc808d9a8cf0.
Fixes https://github.com/renpy/renpy/issues/3563.
Taking this commit-by-commit (and maybe hiding whitespace) should make for a much saner experience when reviewing.
> Fix rollback purging

- distribute.py
- launcher/game/distribute.rpy
- launcher/game/installer.py
- launcher/game/mobilebuild.rpy
- module/tinyfiledialogs/tinyfiledialogs.c
- renpy/atl.py
- renpy/common/00steam.rpy
- renpy/python.py
- renpy/rollback.py
I'm not too sure about the C file though, maybe it should be excluded.
> Rmove bare excepts from the repository - 2

- launcher/game/tl/german/launcher.rpy
Generated new translations, added the most important ones, and edited some of the existing ones
> Update most commonly used German terms

- renpy/common/00action_audio.rpy
- renpy/common/00action_control.rpy
- renpy/common/00action_data.rpy
- renpy/common/00action_other.rpy
- renpy/display/layout.py
- renpy/text/text.py
- sphinx/source/audio.rst
- sphinx/source/config.rst
- sphinx/source/displayables.rst
- sphinx/source/screen_actions.rst
- Documents that SetDict works (and should be used) with lists
- fixes the issues with Text and dynamic displayables' doc
(The first 7 commits can be ignored, as they have already been squashed and merged.)
> Doc additions

- renpy/dump.py
- scripts/generate_pyi.py
If Python [says so](https://docs.python.org/3/library/sys.html#sys.modules), better to do it.
> Iterate over a copy of sys.modules

- sphinx/source/displayables.rst
- sphinx/source/screen_python.rst
- sphinx/source/screens.rst
Inspired by wikipedia. Some pages bear special relations with other pages, because of closely related subjects, because one page extends another...
> Add See also sections in the doc

- sphinx/source/screen_actions.rst
Add a link from screen_actions to the Action class
> Link to the Action class at the end of the actions list

- sphinx/source/config.rst
attempt to fix #3597. I hope I understood how Sphinx works.
> Add scattered configuration variables to main list

- renpy/exports.py
```
label start:
code = renpy.input("Paste the secret code", copypaste=True)
"The secret code is [code]"
```
> copypaste in renpy.input() just like the input in screens

- renpy/common/00console.rpy
- renpy/config.py
Alternative to #3699, per discussion there.
> Add _trace_screen to per_frame_screens

- launcher/game/tl/japanese/screens.rpy
- the_question/game/tl/japanese/screens.rpy
- tutorial/game/tl/japanese/indepth_character.rpy
- tutorial/game/tl/japanese/indepth_displayables.rpy
- tutorial/game/tl/japanese/indepth_style.rpy
- tutorial/game/tl/japanese/indepth_text.rpy
- tutorial/game/tl/japanese/indepth_transitions.rpy
- tutorial/game/tl/japanese/indepth_translations.rpy
- tutorial/game/tl/japanese/screens.rpy
- tutorial/game/tl/japanese/script.rpy
- tutorial/game/tl/japanese/tutorial_atl.rpy
- tutorial/game/tl/japanese/tutorial_director.rpy
- tutorial/game/tl/japanese/tutorial_distribute.rpy
- tutorial/game/tl/japanese/tutorial_nvlmode.rpy
- tutorial/game/tl/japanese/tutorial_playing.rpy
- tutorial/game/tl/japanese/tutorial_screen_displayables.rpy
- tutorial/game/tl/japanese/tutorial_screens.rpy
- tutorial/game/tl/japanese/tutorial_video.rpy
> Japanese translate 220717

- launcher/game/translations.rpy
- renpy/translation/dialogue.py
I added combine option to extract dialogue.
This combine special characters (%, {, [) which need to be double in dialogue into one.
> add combine option to extract dialogue

- renpy/translation/dialogue.py
This considers {{ in extract dialogue with notags option.
current notags option behavior
"{this is tagged} and {{this is not tagged}" -> " and this is not tagged"
new behavior
"{this is tagged} and {{this is not tagged}" -> " and {this is not tagged}"
> consider {{ in exatract_dialogue

- renpy/text/extras.py
I added below the sample code for ParameterizedText.
image top_text = ParameterizedText(xalign=0.5, yalign=0.0)
show top_text "This text is shown at center-upper"
> [Doc] add ParameterizedText sample code

- renpy/script.py
It was simpler than I thought.
> Fix duplicate label errors

- renpy/common/_shaders.rpym
I'm not sure when these are called, I just saw the code and tested an improvement.
Timeit shows a 2x faster calculation.
> Use c-boosted mul function instead of python-defined one

- renpy/common/00console.rpy
This fixes #3843.
Note, target branch is maint-8.0.
> Fixes of console pretty repr

- renpy/lexer.py
- sphinx/source/ren_py.rst
I started adding a supplementary error and got a bit carried away.
Needs to be tested.
> Add a syntax error to _ren.py parsing, and tweak its doc

- renpy/lexer.py
https://docs.python.org/3/library/stdtypes.html#str.splitlines
> Make _ren.py accept windows-ending (CRLF) files

- renpy/__init__.py
Very simple draft that enables the convenience methods for indexing properties while remaining backwards compatible.
> Use a NamedTuple for version_tuple (for #3755)

- renpy/parser.py
This pull request fixed #3912.
The problem is that the last argument was a newline character.
> fix: issue-3912

- renpy/common/_shaders.rpym
- renpy/display/viewport.py
Do not let the texture disappear if the final weight is zero.
Fixes: https://github.com/renpy/renpy/issues/3939
> Additional zero check for renpy_blur

- sphinx/source/layeredimage.rst
This is a bit heavy, so I put it in a PR.
The "Several group blocks..." part with the example could be moved to after the pattern section.
> More Layeredimage documentation

- sphinx/source/displaying_images.rst
The functions edits the same data, only better.
Also, this adds better references in the page.
> Advise renpy.add_layer instead of config.layers

- renpy/exports.py
- sphinx/source/changelog.rst
This is a high-level implementation, using only documented functions. It has the advantage not to rely on existing implementation, making it virtually obsolescence-proof, but it may not be the most efficient implementation.
Anyway, this can be merged now and improved afterwards.
> Add renpy.clear_attributes

- renpy/translation/__init__.py
> Fix change_language during menu-with-say.

- sphinx/source/model.rst
Fixes #3982 by documenting the cause and recommended solution.
> Documenting the pitfall of animated shaders.

- renpy/ast.py
- renpy/atl.py
- renpy/audio/ioshw.py
- renpy/bootstrap.py
- renpy/display/anim.py
- renpy/display/joystick.py
- renpy/display/layout.py
- renpy/display/screen.py
- renpy/log.py
- renpy/translation/__init__.py
From #3994
These have no programmatic purpose and make the code longer.
> Pylint - Remove useless statements

- renpy/display/behavior.py
- renpy/display/core.py
- renpy/exports.py
- renpy/webloader.py
From #3994
Iterate over the values or items accessors for faster access.
> Pylint - Optimize dict iteration

- renpy/audio/audio.py
- renpy/loader.py
- renpy/webloader.py
> Pylint - Remove useless global statements

- renpy/display/behavior.py
- renpy/display/focus.py
- renpy/execution.py
- renpy/exports.py
- renpy/loader.py
- renpy/sl2/slast.py
- renpy/text/text.py
- renpy/ui.py
From #3994
This is the simpler cases of unused variables, the more complex ones are described in #4044.
> Pylint - Flag or remove unused variables

- renpy/__init__.py
- renpy/compat/__init__.py
- renpy/config.py
> Pylint - Avoid unnecessary reimports

- renpy/script.py
- renpy/translation/dialogue.py
From #3994
All possible uses were not implemented, only the simpler ones.
> Pylint - Use the with statements

- renpy/display/movetransition.py
- renpy/display/transition.py
From #3994
Avoids useless memory use and computation time
> Pylint - Remove useless list comprehensions

- renpy/common/00db_ren.py
- renpy/common/00speechbubble.rpy
- renpy/common/00updater.rpy
- renpy/display/core.py
- renpy/display/im.py
- renpy/python.py
- tutorial/game/01example.rpy
> Fix bare except statements

- distribute.py
- launcher/game/tl/french/launcher.rpy
- renpy/__init__.py
- renpy/ast.py
- renpy/sl2/slparser.py
- renpy/statements.py
- sphinx/source/android.rst
- sphinx/source/audio.rst
- sphinx/source/changelog.rst
- sphinx/source/ios.rst
- sphinx/source/label.rst
- sphinx/source/save_load_rollback.rst
- sphinx/source/voice.rst
This also merges the maint-8.0 branch into master, because a change needed to be based upon the maint-8 version.
> Various issues in the doc

- renpy/ui.py
> Pylint - Fix wrong formatting in exception raising

- renpy/audio/audio.py
> Reserve spaces in register_channel's names

- renpy/common/000statements.rpy
> Queue sound can now use fadein

- launcher/game/project.rpy
I'll translate it when we agree on the wording.
> Add a lint blurb to the launcher's splash

- renpy/common/00console.rpy
Alternate implementation of https://github.com/renpy/renpy/pull/4147 following brief discussion (https://github.com/renpy/renpy/pull/4147#issuecomment-1344956624).
> console: Only save command if not the same as last

- launcher/game/tl/ukrainian/launcher.rpy
Few mistakes in the Ukranian translation
> Update Ukrainian translation

- renpy/display/render.pyx
- sphinx/source/cdd.rst
Method Render.place() now returns d.place() result
> Update place method of render

- renpy/common/_developer/developer.rpym
Probably simpler than risking dubious git things on the main repo.
> Persistent devtool - Mal edition

- renpy/common/00compat.rpy
- renpy/config.py
- renpy/display/core.py
- renpy/exports.py
- sphinx/source/config.rst
Addresses just the sticky layer aspect of https://github.com/renpy/renpy/issues/4149.
> Sticky layer implementation

- sphinx/source/store_variables.rst
fixes #4204, and related to #3600
> Fix wrong config variable name

- renpy/display/screen.py
- sphinx/source/screens.rst
> Document new clauses for show screen and other statements

- sphinx/source/config.rst
> Add a entry for config.pad_bindings

- sphinx/source/3dstage.rst
- sphinx/source/config.rst
> Add an entry for config.perspective

- renpy/color.py
- renpy/config.py
- renpy/display/imagelike.py
- renpy/display/movetransition.py
- renpy/display/render.pyx
- renpy/display/transition.py
- renpy/exports.py
- renpy/sl2/slparser.py
- renpy/text/text.py
- renpy/ui.py
Similar to #4224 and #3186.
All docstrings containing customized signatures (the :args: tag) were checked, I didn't find any other issue.
> Secure documented signatures

- renpy/loader.py
Depends on https://github.com/renpy/pygame_sdl2/pull/135  
A possible solution to https://github.com/renpy/renpy/issues/3342
> loader: use RWops object from pygame_sdl2

- renpy/ui.py
- sphinx/source/save_load_rollback.rst
Looking at the commit diffs separately makes it more clear.
Squash-merge is advised.
> Upgrade the fixed rollback documentation to strip obsolete functions

- renpy/lint.py
I chose not to shorten the list (see the commented-out lines) because you usually want to catch all the obsolete translations without having to re-lint, unlike unreachable statements where one mistake can generate a lot of them at once and where each case is specific.
This may warrant a new launcher menu enabling or disabling verbose lint options, such as this one or #3878.
> Lint orphan translations

- sphinx/source/config.rst
> Upgrade example of config variable definition

- renpy/audio/webaudio.py
I forgot to commit that change during last PR.
> Only show warning message when playing a video

- renpy/display/layout.py
> Hotfix 9f96f13

- renpy/lexer.py
- renpy/parser.py
Documentation coming, if the implementation is ok.
> Implement `rpy monologue none`

- sphinx/source/changelog.rst
- sphinx/source/dialogue.rst
> Doc and changelog monologue none

- renpy/audio/music.py
> Fix docstring for renpy.music.set_pan

- sphinx/game/doc.py
> Don't get inherited docstrings if a subclass has no doc

- renpy/common/00action_data.rpy
> Fixed incorrect behaviour for ToggleDict.get_sensitive()

- renpy/python.py
> Fix name-munging

- renpy/common/00db_ren.py
The sentence implied that after releasing the game once, you couldn't change the jsondb anymore in future releases, and I think it's not at all what it meant.
> JSONDB doc

- renpy/common/000statements.rpy
- renpy/lint.py
Prevents lint flagging issues with bottom and detached layers
> Use computed layer list in lint

- renpy/common/_audio.js
Fix #4594.
Only the movie audio will fade out obviously, no fade to black.
> Implement fadeout for movies on Web.

- launcher/game/tl/finnish/common.rpy
- launcher/game/tl/finnish/launcher.rpy
I made some corrections to the machine-translated Finnish in common.rpy and launcher.rpy, and fixed a typo in the old translation.
> Finnish translation fixes

- launcher/game/tl/japanese/common.rpy
- launcher/game/tl/japanese/developer.rpy
- launcher/game/tl/japanese/error.rpy
- launcher/game/tl/japanese/gui.rpy
- launcher/game/tl/japanese/launcher.rpy
- launcher/game/tl/japanese/options.rpy
- launcher/game/tl/japanese/screens.rpy
I checked the machine-translated Japanese and corrected any words that needed correction or could be better worded.
I have also translated some words that were not translated or were translated incorrectly.
Translated target: `launcher/game/tl/japanese`
If you have any questions or problems, please let me know.
> Translation of Japanese

- the_question/game/screens.rpy
- the_question/game/tl/czech/common.rpy
- the_question/game/tl/czech/options.rpy
- the_question/game/tl/czech/screens.rpy
- the_question/game/tl/czech/script.rpy
> Czech Translation of The Question

- renpy/ast.py
- renpy/exports.py
- renpy/parser.py
- sphinx/source/changelog.rst
- sphinx/source/label.rst
Still doesn't extend to Call and Jump, which would be much more complex to do.
> Enable jump/call expression to local labels

- renpy/exports.py
> Add last_say function.

- sphinx/source/screens.rst
Fixed minor typo in documentation.
> Fixed typo in documentation

- renpy/display/screen.py
- renpy/exports.py
Add some safety in the case the object ends up in save data
> Tweaks to renpy.last_say

- renpy.py
- renpy/bootstrap.py
This change will explicitly customize the path to the log directory.
> add: `path_to_logdir`

- renpy/common/00action_other.rpy
- renpy/common/00splines.rpy
- renpy/display/dragdrop.py
- renpy/display/motion.py
- renpy/display/render.pyx
- renpy/gl2/live2d.py
- sphinx/source/atl.rst
- sphinx/source/changelog.rst
- sphinx/source/style_properties.rst
First part of a sectionning of #3214 into several sub-tasks.
Update parts of the code that were not supporting the position feature entirely.
Remains one in the testcase area (already fixed in the testcase-ex branch), and one in #4707 which is probably a bug.
> Support position (absolute) everywhere

- sphinx/source/dialogue.rst
Fixed minor typo in dialogue.rst
> Fixed Typo in dialogue.rst

- renpy/common/00action_menu.rpy
better apparent signature, better documenting how args and kwargs work
Should have gone into fix. Whatever.
> Update the ShowMenu doc entry

- renpy/display/layout.py
- sphinx/source/config.rst
> Clarify clipping behaviour as it relates to layers and Layer

- renpy/common/00inputvalues.rpy
Add LocalVariableValue, factorize a bunch of code, use the same doc-generating model as with bar values.
> Rework Inputvalues

- launcher/game/preferences.rpy
- renpy/lint.py
- renpy/text/extras.py
I don't think it's a good addition, but the code is there.
> Allow linting unclosed tags

- launcher/game/preferences.rpy
Per #3668, notwithstanding the option of adding other, more user-friendly ways to add or remove paths from consideration (as discussed there).
> Open/create projects.txt from the launcher preferences

- renpy/common/00sync.rpy
> py2: Alternate timestamp calculation in sync

- renpy/common/00stylepreferences.rpy
Not knowing this was a source of some annoyance when an animation would replay after calling StylePreference.
> docs: Add note for StylePreference about update event getting called

- launcher/game/front_page.rpy
- launcher/game/preferences.rpy
- renpy/lint.py
From Mal's idea in #5083.
I had objections, but they were overcome by InvertSelected and the fact that we don't need a separate and complete list of options now : they can be written manually in the screen.
> Better manage lint toggles V2

- renpy/common/00gamemenu.rpy
> typo in _enter_menu()

- renpy/display/core.py
Underlying mouse movement events may be merged or dropped by Ren'Py for performance reasons. As a result, the relative movement would only be that of the most recent mouse event, rather than an accurate measure of movement since the last (published) event.
Instead of dropping mouse motion events outright, this change instead opts to consume them in a tight loop accumulating their relative values. Combined with accumulation during merges, this allows published events to give an accurate picture of the relative movement.
The code is a little verbose, but it benchmarked the best of the 3-4 options available.
> Update rel values of combined mouse events

- renpy/display/movetransition.py
Hotfix of #5123, but actually a fix of #4844.
> Fix interpolation of move transitions wrt the position type

- sphinx/source/changelog.rst
Once you see it, you can't unsee it.
> Fix tyops in the changlog

- launcher/game/tl/japanese/common.rpy
- launcher/game/tl/japanese/developer.rpy
- launcher/game/tl/japanese/gui.rpy
- launcher/game/tl/japanese/launcher.rpy
- launcher/game/tl/japanese/screens.rpy
- the_question/game/tl/japanese/common.rpy
- the_question/game/tl/japanese/options.rpy
- the_question/game/tl/japanese/screens.rpy
- tutorial/game/tl/japanese/common.rpy
- tutorial/game/tl/japanese/screens.rpy
> translate japanese 231231

- renpy.py
- renpy/main.py
Currently, the search can be modified, but the initial initialization of the archives is done with the initial paths.
>  feature: search control before initialization

- renpy/common/00action_menu.rpy
- renpy/common/00gui.rpy
- renpy/common/00layout.rpy
- sphinx/source/screen_special.rst
The other pr was deleted due to an error in my fork. (#4921)
Closes #4901
> action Continue(): re-PR

- launcher/game/web.rpy
- sphinx/source/cli.rst
Intentionally haven't documented the launch since I can't see that it makes sense in a CI environment, but the code to support it is there since android_build had it.
Tested with The Question.
> Add CLI for web builds

- renpy/atl.py
- renpy/display/transform.py
- sphinx/source/atl.rst
Roughly fixes #5162.
A jolly cocktail meant to be cherrypickable.
> Fix polar anchor and some ATL docs improvements

- renpy/ast.py
By calling up to the Say class which holds the logic for dealing with say attributes and other aspects of Say statements which we need to proxy though.
> Fully prep for prediction in TranslateSay

- renpy/exports.py
> Better urllib import

- sphinx/source/changelog.rst
posssible -> possible
gtlphs -> glyphs
> Fix typos in changelog.rst

- sphinx/source/label.rst
> Fix 'if' typo

- renpy/common/00nvl_mode.rpy
> Fix nvl hide

- renpy/atl.py
> fix `warp` interpolation

- renpy/compat/pickle.py
Currently ren'py 8 cannot even load .rpyc files that contain the compiled result of screen language version 1. I've validated this with several files from ren'py 6.17, which was the last version using old-style screens.
Ren'py 8 still has all the code needed to support these files, but as the ast module of python has changed between 2.7 and 3.9 it has become impossible to even load these files as the unpickling process would error due to unknown classes. This means nearly any ren'py 6.17 game or before cannot be ported over without a recompile.
This commit fixes this by intercepting the construction of these classes using pre-existing mechanisms in renpy.compat.pickle. When not needed this adds only a single equality check to the critical path of unpickling files.
I've tested this by …
> Allow ren'py 8 to load .rpyc files using old-style screens.

- sphinx/source/label.rst
Add examples and clearer explanations.
> Tweak label documentation

- renpy/common/00sync.rpy
**Not tested** but noticed this and it seems like an obvious fix.
> Respect config.savegame_suffix in sync

- the_question/game/screens.rpy
- the_question/game/tl/italian/common.rpy
- the_question/game/tl/italian/options.rpy
- the_question/game/tl/italian/screens.rpy
- the_question/game/tl/italian/script.rpy
Fully tested in-game with the v8.2.1 SDK, everything appears working. I also added the required button for switching the Language to Italian in Preferences.
> Create full Italian translation of The Question

- launcher/game/tl/japanese/screens.rpy
- the_question/game/tl/japanese/screens.rpy
- tutorial/game/tl/japanese/screens.rpy
- tutorial/game/tl/japanese/tutorial_playing.rpy
> Japanese update 240621

- launcher/game/tl/japanese/common.rpy
- launcher/game/tl/japanese/screens.rpy
- the_question/game/tl/japanese/common.rpy
- the_question/game/tl/japanese/screens.rpy
- tutorial/game/tl/japanese/common.rpy
- tutorial/game/tl/japanese/screens.rpy
fix japanese translation 240628
> fix japanese translation 240628

- sphinx/source/gui.rst
- sphinx/source/quickstart.rst
I added a brief description of each file in the project to the quick tutorial to help beginners get an overview of the file structure
> [Doc]add describes for files

- sphinx/source/web.rst
add the description that live2d is not supported in web platform.
> [Doc]add the description that live2d is not supported in web plattform

- launcher/game/tl/russian/options.rpy
- launcher/game/tl/russian/screens.rpy
Just removed `# Automatic translation.` where translation is OK.
Fixed where it was obviously not OK.
> Fixed some obvious translation "bugs"

- launcher/game/distribute.rpy
These code lines appear to do nothing, as `file_hash` is a local string, `hash_file` has no side effects, and one line is a duplicate.
> remove unused code

- renpy/loader.py
Install-time asset packs are served as APKs and can be processed by existing APK routines.
This satisfies Google's expectation of games being in a playable state without any fast-follow packs present.
To be applied with  https://github.com/renpy/renpy-build/pull/141.
Fixes #5010.
> android: Install-time asset pack support.

- renpy/display/behavior.py
- renpy/text/text.py
should fix #5929 while preserving #5913
> input mask regression

- launcher/game/tl/portuguese/editor.rpy
- launcher/game/tl/russian/launcher.rpy
- launcher/game/tl/spanish/common.rpy
> fix some newline typos

- renpy/main.py
- sphinx/source/changelog.rst
in case the lib in question is a dev tool
> search for rpe files in /libs

- scripts/setuplib.py
Running all the cython tasks in parallel at once is a bit violent. On my Docker container for instance, it makes some processes be killed before they complete because of resources exhaustion.
Using a ThreadPoolExecutor instance to limit the number of parallel tasks guarantees there will be at least as much processes at the number of CPU plus 4 (up to 32) so that should be as fast as before without risking to reach the host resources limit.
> Limit the number of cython processes ran in parallel

- launcher/game/preferences.rpy
- launcher/game/project.rpy
I noticed that console output isnt available on Macos, so i decided to make my own fix.
> Enable console output in the Mac OS Launcher

- tutorial/game/tl/russian/indepth_style.rpy
- tutorial/game/tl/russian/indepth_transitions.rpy
- tutorial/game/tl/russian/indepth_translations.rpy
- tutorial/game/tl/russian/tutorial_atl.rpy
- tutorial/game/tl/russian/tutorial_quickstart.rpy
- tutorial/game/tl/russian/tutorial_screen_displayables.rpy
- tutorial/game/tl/russian/tutorial_screens.rpy
Hi! 
I didn't change the wording, I just corrected typos.
> Fix typos in russian translation

- renpy/error.py
> traceback: More ANSI colour tweaks

- renpy/pyanalysis.py
`from module import name`
if `name.subname` is const, then also mark `in_module.name.subname` as const
and some renaming
> When doing a `from` import, also check subnames for constness

- renpy/display/accelerator.pyx
A collection of minor tweaks and readability improvements originating from the investigation in #6435.
> Minor transform make_mesh tweaks

- renpy/common/00layeredimage_ren.py
- sphinx/source/changelog.rst
- sphinx/source/layeredimage.rst
> Changes to if_attr

- renpy/arguments.py
- renpy/lint.py
- renpy/script.py
> Lint incorrect calls to Ren'Py translate functions.

- renpy/display/behavior.py
Remove blinking during position change and add a bigger delay before starting to blink.
Before:
https://github.com/user-attachments/assets/f4b20002-3c29-4382-876d-0fddaff4f251
After:
https://github.com/user-attachments/assets/6bd85758-ce9e-46a1-9d94-71f36a9153fb
> Fix caret blinking

- renpy/common/00barvalues.rpy
Adding a bar value `CallableValue` that displays the result of a function call. It can be useful for displaying any dynamic value.
For example, a bar displaying seconds:
```renpy
init python:
import time
def get_seconds():
t = time.localtime()
return t.tm_sec
```
```renpy
screen test:
bar value CallableValue(get_seconds, 60, .0)
```
> Add `CallableValue`.

- renpy/common/00steam.rpy
https://steamcommunity.com/groups/steamworks/announcements/detail/4480612432780198328
This also fixes https://github.com/renpy/renpy/issues/6521 which was marked as completed but isn't as of the latest release.
> Rename timeline functions wrt new steam changes
